import Link from 'next/link';
import {ArrowRight,BookOpen,Mail,ShieldCheck} from 'lucide-react';
import {MarketingShell,marketingMetadata} from '../../components/marketing-site';
import {publicContact} from '../../lib/public-contact';
import s from '../home.module.css';
export const dynamic='force-dynamic';
export const metadata=marketingMetadata('Central de suporte','Orientações para usar a Askadia: acesso à conta, perfil da academia, estratégia, calendário, atendimento e publicação do site.','/suporte');
const groups=[
 {id:'acesso',title:'Acesso e primeiros passos',items:[['Esqueci minha senha. Como recupero?','Abra a página de login e escolha “Esqueci minha senha”. Informe o e-mail da sua conta e siga as instruções recebidas. Se não localizar a mensagem, confira spam e se o endereço foi digitado corretamente.'],['Por onde começo depois de criar a conta?','Confirme seu e-mail, entre no sistema e cadastre a academia. Na conversa inicial, confirme os dados do negócio e envie logo, fotos e referências. Depois, acompanhe a preparação da estratégia.'],['Como atualizo as informações da academia?','Abra Perfil e marca para consultar o que foi confirmado. Na Estratégia, use “Consultar e atualizar” para abrir a conversa e revisar as informações. Mudanças podem exigir nova estratégia e novas aprovações.']]},
 {id:'conteudo-ajuda',title:'Estratégia e publicações',items:[['Minha estratégia está pronta. O que faço agora?','Revise diagnóstico, posicionamento, objetivos e temas. Você pode editar pontos ou pedir para refazer com seu feedback. Ao aprovar, siga para o calendário e revise cada peça.'],['Por que o botão de gerar está desabilitado?','Confira a mensagem ao lado do botão. A geração manual pode exigir estratégia aprovada, permissão de edição e disponibilidade do provedor. O andamento da preparação em segundo plano aparece no calendário.'],['Como finalizo uma publicação em vídeo?','Abra a publicação na data indicada, consulte o roteiro e grave e edite o material. Envie o arquivo final pelo calendário e revise a peça antes de aprovar.'],['Uma publicação com data já está nas redes sociais?','Não. A data representa planejamento. A postagem automática nas redes ainda está em evolução. Aprovação da peça e autorização do canal são etapas distintas.']]},
 {id:'conexoes-ajuda',title:'Atendimento e integrações',items:[['Conectei o WhatsApp, mas a IA não responde.','Conectar o número não ativa a automação. Abra Configuração de Atendimento, selecione IA ou fluxo, confira as informações, faça o teste e habilite a opção de responder automaticamente. Ao assumir uma conversa, o atendimento humano pausa a IA.'],['Não consigo enviar uma mensagem pelo chat.','Verifique se o canal está conectado e assuma o atendimento da conversa para habilitar o envio. Se houver erro, preserve o texto e confira a mensagem apresentada antes de tentar novamente.'],['Instagram e Facebook não mostram mensagens.','Confira em Integrações as permissões de mensagens e a Página selecionada. Autorizar publicações não significa autorizar o Direct ou Messenger. A disponibilidade também depende dos requisitos e da homologação da Meta.'],['Como uso aniversários e dias de ausência em campanhas?','Importe dados atualizados de alunos ou configure o recebimento pela API da empresa. Revise os consentimentos, as condições, os destinatários e os horários antes de ativar a campanha.']]},
 {id:'site-ajuda',title:'Site e endereço da academia',items:[['Como edito o site sem mudar a página publicada?','Em Meu site, clique em Editar site. As alterações ficam no rascunho enquanto você revisa a prévia. Publicar é uma ação separada. Salve os textos antes de configurar o domínio.'],['Reservei um subdomínio, mas ele não abre.','Reservar o nome não publica a página. Confira se o site foi publicado e se DNS, encaminhamento e HTTPS foram configurados. A aba Domínio e endereço mostra a situação e as orientações disponíveis.']]},
];
export default function Support(){const contact=publicContact();return <MarketingShell><section className={s.pageHero}><span className={s.eyebrow}>CENTRAL DE SUPORTE</span><h1>Vamos encontrar seu próximo passo.</h1><p>Respostas para as dúvidas mais comuns e orientações para continuar usando a Askadia.</p><div className={s.actions}><Link href="/login" className={s.primary}>Acessar minha conta <ArrowRight size={17}/></Link><a className={s.textLink} href="#acesso">Ver orientações <ArrowRight size={16}/></a></div></section><div className={s.contentNarrow}><nav className={s.supportLinks} aria-label="Tópicos de suporte">{groups.map(group=><a key={group.id} href={'#'+group.id}><BookOpen size={18}/>{group.title}<ArrowRight size={16}/></a>)}</nav>{groups.map(group=><section key={group.id} id={group.id} className={s.helpGroup}><h2>{group.title}</h2><div className={s.questions}>{group.items.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>)}<section className={s.infoCard}><ShieldCheck size={26}/><h2>Precisa de ajuda com o seu caso?</h2><p>Informe a empresa, a tela em que ocorreu o problema e os passos para reproduzi-lo. Se enviar uma captura de tela, oculte dados de alunos e informações privadas. Nunca envie senhas, tokens ou chaves de API.</p>{contact.supportEmail?<a className={s.primary} href={'mailto:'+contact.supportEmail+'?subject=Ajuda%20com%20a%20Askadia'}><Mail size={17}/>Falar com o suporte</a>:<><p className={s.note}>O canal direto de suporte está em preparação. As orientações desta central continuam disponíveis.</p><Link href="/contato" className={s.secondary}>Ver opções de contato <ArrowRight size={17}/></Link></>}</section></div></MarketingShell>;}
