import {afterAll,afterEach,beforeAll,describe,expect,it,vi} from 'vitest';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync,readdirSync} from 'node:fs';
import {createHash,randomUUID} from 'node:crypto';
import {adSpecSchema,type AdSpec} from '../packages/contracts/src/ad-execution';
import {accountDate,AdProviderError,CampaignProvider,classifyAdError,googleCampaignOperations} from '../apps/api/src/campaigns/ad-provider';
import {confirmedMonthlyBudget} from '../apps/api/src/campaigns/ad-plan-preparation';
const owner=randomUUID(),other=randomUUID(),marketer=randomUUID(),image=randomUUID();let db:PGlite,company:string,foreign:string,plan:string,execution:string;
const spec:AdSpec={name:'Academia fixture',format:'meta_traffic_image',accountId:'act_123456789',accountName:'Conta fixture',pageId:'987654321',currency:'BRL',budgetCents:10000,startsAt:new Date(Date.now()+86400000).toISOString(),endsAt:new Date(Date.now()+8*86400000).toISOString(),timezone:'America/Sao_Paulo',destination:'https://example.test/academia',location:{latitude:-23.5,longitude:-46.6,label:'Local fixture',placeId:'fixture'},copy:{headline:'Conheça nossa academia',text:'Conheça os serviços confirmados da academia.',headlines:['Conheça a academia','Treine perto de casa','Veja nossas modalidades'],descriptions:['Conheça as modalidades disponíveis na nossa academia.','Fale com a equipe e tire suas dúvidas sobre os serviços.'],keywords:['academia local','treino local','musculação local'],radiusKm:5,maxCpcCents:200},imageId:image,imageSha256:createHash('sha256').update('image-fixture').digest('hex'),siteRevision:null};
async function as(id:string){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');}
async function server(){await db.exec('reset role;set role service_role');}
async function scalar<T=unknown>(query:string,args:unknown[]=[]):Promise<T>{return Object.values((await db.query<Record<string,T>>(query,args)).rows[0]!)[0]!;}
type Job={id:string;action:string;lease_token:string};
async function due(){await db.exec('reset role');await db.query("update public.company_ad_executions set next_attempt_at=now()-interval '1 minute',lease_until=null where id=$1",[execution]);await server();return scalar<Job>('select public.claim_ad_execution_server()');}
const finish=(j:Job,value:unknown)=>scalar('select public.finish_ad_execution_server($1,$2,$3)',[j.id,j.lease_token,value]);
describe('Ad scheduling database security and durable execution',()=>{
 beforeAll(async()=>{db=new PGlite();await db.exec("create role anon nologin;create role authenticated nologin;create role service_role nologin;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets(id),name text);alter table storage.objects enable row level security;grant usage on schema storage to authenticated,anon;grant select,insert,update,delete on storage.objects to authenticated;");for(const f of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db.exec(readFileSync('supabase/migrations/'+f,'utf8').replace('create extension if not exists pgcrypto;',''));
 for(const id of [owner,other,marketer]){await db.query('insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())',[id,id+'@example.test']);await db.query('insert into public.profiles(id,display_name) values($1,$2)',[id,'Fixture']);}
 await as(owner);company=(await scalar<{companyId:string}>('select public.begin_company_onboarding($1)',[randomUUID()])).companyId;await as(other);foreign=(await scalar<{companyId:string}>('select public.begin_company_onboarding($1)',[randomUUID()])).companyId;
 await db.exec('reset role');await db.query("insert into public.company_profile_versions(company_id,version,facts,confirmed_by) values($1,1,'{}',$2)",[company,owner]);await db.query('update public.company_onboarding set profile_version=1,confirmed_revision=revision where company_id=$1',[company]);
 // Explicit local fixture of the five strategy reviews; external providers are never called.
 for(let stage=1;stage<=5;stage++)await db.query("insert into public.company_marketing_approvals(company_id,profile_version,stage,basis,snapshot,approved_by) values($1,1,$2,md5(private.journey_basis($1,$2)::text),'{}',$3)",[company,stage,owner]);
 await db.query("insert into public.company_members(company_id,user_id,role) values($1,$2,'marketing')",[company,marketer]);await db.query("insert into public.company_ad_connections(company_id,provider,account_id,name,source_page,status) values($1,'meta','act_123456789','Fixture','987654321','connected')",[company]);
 const path=company+'/onboarding/'+image+'.png';await db.query("insert into storage.objects(bucket_id,name) values('company-assets',$1)",[path]);await db.query("insert into public.onboarding_attachments(id,company_id,name,mime,size,object_path,uploaded_by) values($1,$2,'Fixture','image/png',10,$3,$4)",[image,company,path,owner]);
 await as(owner);plan=randomUUID();await scalar('select public.begin_paid_plan($1,$2,200,7)',[company,plan]);await server();await scalar('select public.finish_paid_plan_server($1,$2,$3,$4,$5)',[company,owner,plan,{summary:'Fixture',campaigns:[{name:'Academia fixture',provider:'meta',investment:100}],unknowns:[]},'fixture']);await as(owner);execution=await scalar<string>('select id from public.company_ad_executions where plan_id=$1',[plan]);
 },120000);
 afterAll(async()=>{await db?.close();});
 it('enforces Google total budget minimum in both API contract and database',async()=>{
  const google={...spec,format:'google_search' as const,accountId:'123456789',endsAt:new Date(Date.parse(spec.startsAt)+2*86400000).toISOString()};
  expect(adSpecSchema.safeParse(google).success).toBe(false);
  expect(adSpecSchema.safeParse({...google,endsAt:new Date(Date.parse(spec.startsAt)+3*86400000).toISOString()}).success).toBe(true);
  await db.exec('reset role');
  await db.query("insert into public.company_ad_connections(company_id,provider,account_id,name,status) values($1,'google','123456789','Fixture','connected')",[company]);
  const fixture=await scalar<Record<string,unknown>>('select to_jsonb(e) from public.company_ad_executions e where id=$1',[execution]);
  await expect(db.query('select private.validate_ad_spec(jsonb_populate_record(null::public.company_ad_executions,$1),$2)',[{...fixture,provider:'google'},google])).rejects.toThrow('3 e 90 dias');
 });
 it('automatically queues drafts and hides them from another tenant',async()=>{expect(execution).toBeTruthy();await as(other);expect(await scalar('select count(*)::int from public.company_ad_executions where company_id=$1',[company])).toBe(0);await expect(scalar('select public.approve_ad_execution($1,$2,1)',[company,execution])).rejects.toThrow('permission');await expect(scalar('select public.claim_ad_execution_server()')).rejects.toThrow();await server();expect(await scalar("select public.claim_ad_execution_server('execute')")).toBeNull();const j=await scalar<Job>("select public.claim_ad_execution_server('prepare')");expect(j.action).toBe('prepare');expect(await finish({...j,lease_token:randomUUID()},{status:'draft',spec})).toBe(false);expect(await finish(j,{status:'draft',spec})).toBe(true);});
 it('checks full plan budget delegation, exact revision, future schedule and explicit client approval',async()=>{await as(owner);await expect(scalar('select public.approve_ad_execution($1,$2,2)',[company,execution])).rejects.toThrow('changed');await scalar('select public.set_company_permission($1,$2,$3,true,15000)',[company,marketer,'ads.approve']);await as(marketer);await expect(scalar('select public.approve_ad_execution($1,$2,1)',[company,execution])).rejects.toThrow('Budget');await as(owner);await expect(scalar('select public.edit_ad_execution($1,$2,1,$3)',[company,execution,{...spec,budgetCents:10100}])).rejects.toThrow('budget');await scalar('select public.approve_ad_execution($1,$2,1)',[company,execution]);await scalar('select public.approve_ad_execution($1,$2,1)',[company,execution]);expect(await scalar("select count(*)::int from public.audit_logs where company_id=$1 and action='ads.approved'",[company])).toBe(1);});
 it('invalidates an approval after editing and rejects account or creative substitution',async()=>{await as(owner);await expect(scalar('select public.edit_ad_execution($1,$2,1,$3)',[company,execution,{...spec,imageId:randomUUID()}])).rejects.toThrow('creative');await scalar('select public.edit_ad_execution($1,$2,1,$3)',[company,execution,{...spec,name:'Texto revisado'}]);expect(await scalar('select approved_revision from public.company_ad_executions where id=$1',[execution])).toBeNull();await expect(scalar('select public.approve_ad_execution($1,$2,1)',[company,execution])).rejects.toThrow('changed');await scalar('select public.approve_ad_execution($1,$2,2)',[company,execution]);});
 it('creates paused resources once, reconciles unknown outcomes, and never activates early',async()=>{const j=await due();expect(j.action).toBe('provision');const hash='a'.repeat(64);expect(await scalar('select public.ad_step_server($1,$2,$3,$4)',[execution,j.lease_token,'campaign',hash])).toEqual({status:'execute'});expect(await scalar('select public.ad_step_server($1,$2,$3,$4)',[execution,j.lease_token,'campaign',hash])).toEqual({status:'reconcile'});await expect(scalar('select public.ad_step_server($1,$2,$3,$4)',[execution,j.lease_token,'campaign','b'.repeat(64)])).rejects.toThrow('changed');await scalar('select public.ad_step_server($1,$2,$3,$4,$5)',[execution,j.lease_token,'campaign',hash,'123456789']);expect(await scalar('select public.ad_step_server($1,$2,$3,$4)',[execution,j.lease_token,'campaign',hash])).toEqual({status:'done',id:'123456789'});await finish(j,{status:'scheduled',complete:true});expect(await due()).toBeNull();});
 it('persists insufficient funds without claiming available credit and requires no new start approval',async()=>{await db.exec('reset role');const running={...spec,name:'Texto revisado',startsAt:new Date(Date.now()-3600000).toISOString()};await db.query("update public.company_ad_executions set spec=$2,approved_hash=md5($2::jsonb::text) where id=$1",[execution,running]);const j=await due();expect(j.action).toBe('activate');await finish(j,{status:'blocked',kind:'insufficient_funds',error:'Saldo insuficiente informado pela Meta.'});await as(owner);expect(await scalar('select error_kind from public.company_ad_executions where id=$1',[execution])).toBe('insufficient_funds');const retry=await due();expect(retry.action).toBe('activate');await finish(retry,{status:'active',observed:{status:'ACTIVE'}});});
 it('revalidates permissions after approval and queues a compensating pause',async()=>{await db.exec('reset role');await db.query('update public.company_ad_executions set approved_by=$2 where id=$1',[execution,marketer]);const j=await due();expect(j.action).toBe('invalidate');expect(await scalar('select public.ad_execution_guard_server($1,$2)',[execution,j.lease_token])).toBe(false);await finish(j,{status:'stale'});await as(owner);expect(await scalar('select status from public.company_ad_executions where id=$1',[execution])).toBe('stale');});
 it('does not let another company control a campaign or access credentials',async()=>{await as(other);await expect(scalar('select public.control_ad_execution($1,$2,2,$3)',[foreign,execution,'cancel'])).rejects.toThrow('changed');await expect(scalar('select public.ad_execution_context_server($1,$2)',[execution,randomUUID()])).rejects.toThrow();});
});
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();});
describe('Provider campaign creation and billing',()=>{
 it('verifies Google audience and keywords and rejects unapproved changes',async()=>{
  const p=new CampaignProvider({...spec,format:'google_search',accountId:'123456789'},{token:'fixture'},'fixture');
  let radius=5,matchType='PHRASE';
  vi.spyOn(p,'search').mockImplementation(async(query:string)=>{
   if(query.includes('FROM campaign WHERE'))return [{campaign:{startDateTime:accountDate(spec.startsAt,spec.timezone),endDateTime:accountDate(spec.endsAt,spec.timezone),advertisingChannelType:'SEARCH'},campaignBudget:{period:'CUSTOM_PERIOD',totalAmountMicros:String(spec.budgetCents*10000)}}];
   if(query.includes('FROM ad_group_ad'))return [{adGroupAd:{ad:{finalUrls:[spec.destination],responsiveSearchAd:{headlines:spec.copy.headlines.map(text=>({text})),descriptions:spec.copy.descriptions.map(text=>({text}))}}},adGroup:{cpcBidMicros:String(spec.copy.maxCpcCents*10000)}}];
   if(query.includes('FROM campaign_criterion'))return [{campaignCriterion:{type:'PROXIMITY',negative:false,proximity:{radius,radiusUnits:'KILOMETERS',geoPoint:{latitudeInMicroDegrees:String(Math.round(spec.location.latitude*1e6)),longitudeInMicroDegrees:String(Math.round(spec.location.longitude*1e6))}}}},{campaignCriterion:{type:'LANGUAGE',negative:false,language:{languageConstant:'languageConstants/1014'}}}];
   return spec.copy.keywords.map(text=>({adGroupCriterion:{type:'KEYWORD',negative:false,keyword:{text,matchType}}}));
  });
  const remote={google:'customers/123456789/campaigns/123'};
  await expect(p.verify(remote)).resolves.toBeUndefined();
  radius=50;await expect(p.verify(remote)).rejects.toThrow('região');
  radius=5;matchType='BROAD';await expect(p.verify(remote)).rejects.toThrow('palavras-chave');
 });
 it('does not equate an eligible Google status with measured ad delivery',async()=>{
  const p=new CampaignProvider({...spec,format:'google_search',accountId:'123456789'},{token:'fixture'},'fixture');
  vi.spyOn(p,'account').mockResolvedValue();
  vi.spyOn(p,'search').mockResolvedValue([{campaign:{status:'ENABLED',primaryStatus:'ELIGIBLE',servingStatus:'SERVING'}}]);
  expect(await p.observe({google:'customers/123456789/campaigns/123'})).toMatchObject({deliveryConfirmed:false,eligible:true});
 });
 it('uses an exact total Google budget and account timezone, not a multiplied daily budget',()=>{const s={...spec,format:'google_search' as const,accountId:'123456789',pageId:null,imageId:null,imageSha256:null};const ops=googleCampaignOperations(s,'fixture');expect(ops[0]).toMatchObject({campaignBudgetOperation:{create:{period:'CUSTOM_PERIOD',totalAmountMicros:'100000000',explicitlyShared:false}}});expect(ops[1]).toMatchObject({campaignOperation:{create:{status:'PAUSED',advertisingChannelType:'SEARCH'}}});expect(accountDate('2026-09-28T12:30:00Z','America/Sao_Paulo')).toBe('2026-09-28 09:30:00');expect(JSON.stringify(ops)).not.toContain('amountMicros');});
 it('distinguishes insufficient funds, billing, authorization and uncertain outcomes',()=>{expect(classifyAdError('meta',400,{error:{message:'Insufficient funds'}}).kind).toBe('insufficient_funds');expect(classifyAdError('meta',400,{error:{message:'Payment failed'}}).kind).toBe('billing');expect(classifyAdError('meta',400,{error:{message:'Invalid parameter'}}).kind).toBe('provider');expect(classifyAdError('google',503,{}).definitive).toBe(false);expect(classifyAdError('meta',401,{error:{code:190}}).kind).toBe('authorization');});
 it('requires explicit unambiguous budget and rejects bad campaigns',()=>{expect(confirmedMonthlyBudget('R$ 1.500,00 por mês')).toBe(150000);expect(confirmedMonthlyBudget('1500 reais mensais')).toBe(150000);for(const raw of ['entre 1000 e 2000','R$ 50 por dia','a definir','2 mil','500 por semana','US$ 1500','1500 anual','Sem orçamento, talvez 1000','0'])expect(confirmedMonthlyBudget(raw)).toBeNull();expect(adSpecSchema.safeParse({...spec,destination:'http://127.0.0.1/'}).success).toBe(false);expect(adSpecSchema.safeParse({...spec,imageId:null}).success).toBe(false);});
 it('uploads approved bytes, creates the entire Meta hierarchy paused, and enables the parent last',async()=>{vi.stubEnv('META_GRAPH_API_VERSION','v26.0');const writes:{path:string;body:Record<string,unknown>}[]=[];const fetcher=vi.fn(async(input:URL,options?:RequestInit)=>{const path=input.pathname,body=options?.body?JSON.parse(String(options.body)):null;if(body){writes.push({path,body});return new Response(JSON.stringify(path.endsWith('/adimages')?{images:{fixture:{hash:'hash'}}}:{id:path.endsWith('/campaigns')?'111':path.endsWith('/adsets')?'222':path.endsWith('/ads')?'333':'444'}));}return new Response(JSON.stringify({currency:'BRL',timezone_name:'America/Sao_Paulo',account_status:1}));});vi.stubGlobal('fetch',fetcher);const approved={...spec,startsAt:new Date(Date.now()-3600000).toISOString()};const provider=new CampaignProvider(approved,{token:'fixture'},'fixture');const remote=await provider.provision(async(_key,_payload,create)=>create(),Buffer.from('image-fixture'));expect(writes.filter(w=>['/campaigns','/adsets','/ads'].some(e=>w.path.endsWith(e))).every(w=>w.body.status==='PAUSED')).toBe(true);expect(writes.find(w=>w.path.endsWith('/adsets'))!.body.lifetime_budget).toBe(10000);expect(writes.find(w=>w.path.endsWith('/adimages'))!.body.bytes).toBe(Buffer.from('image-fixture').toString('base64'));vi.spyOn(provider,'verify').mockResolvedValue();const guard=vi.fn(async()=>{});await provider.activate(remote,guard);expect(writes.slice(-3).map(w=>w.path.split('/').at(-1))).toEqual(['333','222','111']);expect(guard).toHaveBeenCalledTimes(3);});

 it('blocks activation when the remote Google total budget differs from the reviewed version',async()=>{vi.stubEnv('GOOGLE_ADS_API_VERSION','v25');vi.stubEnv('GOOGLE_ADS_DEVELOPER_TOKEN','fixture');const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({results:[{campaign:{startDateTime:accountDate(spec.startsAt,spec.timezone),endDateTime:accountDate(spec.endsAt,spec.timezone),advertisingChannelType:'SEARCH'},campaignBudget:{period:'DAILY',totalAmountMicros:'999999999'}}]})));vi.stubGlobal('fetch',fetcher);const p=new CampaignProvider({...spec,format:'google_search',accountId:'123456789'},{token:'fixture',managerId:'998877665'},'fixture');await expect(p.verify({google:'customers/123456789/campaigns/123'})).rejects.toThrow('Orçamento');expect(fetcher.mock.calls.every(c=>String(c[0]).endsWith('googleAds:search'))).toBe(true);expect(fetcher.mock.calls[0]![1].headers['login-customer-id']).toBe('998877665');});
 it('never uploads a replaced creative and stops activation immediately if approval is revoked',async()=>{vi.stubEnv('META_GRAPH_API_VERSION','v26.0');const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({currency:'BRL',timezone_name:'America/Sao_Paulo',account_status:1})));vi.stubGlobal('fetch',fetcher);const p=new CampaignProvider({...spec,startsAt:new Date(Date.now()-3600000).toISOString()},{token:'fixture'},'fixture');await expect(p.provision(async()=>{throw Error('Should not create');},Buffer.from('replaced'))).rejects.toThrow('mudou');fetcher.mockResolvedValue(new Response(JSON.stringify({currency:'BRL',timezone_name:'America/Sao_Paulo',account_status:1})));vi.spyOn(p,'verify').mockResolvedValue();await expect(p.activate({campaign:'1',adset:'2',ad:'3'},async()=>{throw new AdProviderError('changed','Revoked');})).rejects.toThrow('Revoked');expect(fetcher.mock.calls.every(c=>!c[1]?.body)).toBe(true);});
});
