import {afterAll,beforeAll,describe,expect,it} from 'vitest';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync,readdirSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {parseStudentsCsv,personalizeCampaign,messageCampaignSchema} from '../packages/contracts/src/campaigns';
import {metaAccess,metaPermissions} from '../packages/contracts/src/meta';
let db:PGlite,a:string,b:string;
const owner='90000000-0000-4000-8000-000000000001',other='90000000-0000-4000-8000-000000000002',attendant='90000000-0000-4000-8000-000000000003';
async function as(id:string){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');}
async function scalar<T=unknown>(sql:string,args:unknown[]=[]):Promise<T>{return Object.values((await db.query<Record<string,T>>(sql,args)).rows[0]!)[0]!;}
const input=(id=randomUUID())=>({id,revision:0,name:'Aniversários',trigger:'birthday',absenceDays:7,sendTime:'09:00',message:'Parabéns, {{nome}}! {{academia}}',tag:'',activeOnly:true,startDate:'2020-01-01',endDate:null,maxDataAgeDays:2,dailyLimit:20});
const student=(externalId:string,phone:string,extra:Record<string,unknown>={})=>({externalId,name:'Aluno fictício',phone,birthday:new Date().toISOString().slice(0,10),lastAttendance:'2020-01-01T12:00:00Z',status:'active',consent:true,tag:'',...extra});
describe('Campaign conditions and company isolation',()=>{
 beforeAll(async()=>{db=new PGlite();await db.exec(`create role anon nologin;create role authenticated nologin;create role service_role nologin;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets(id),name text);alter table storage.objects enable row level security;grant usage on schema storage to authenticated,anon;grant select,insert,update,delete on storage.objects to authenticated;`);
 for(const file of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db.exec(readFileSync('supabase/migrations/'+file,'utf8').replace('create extension if not exists pgcrypto;',''));
 for(const id of [owner,other,attendant]){await db.query('insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())',[id,id+'@example.test']);await db.query('insert into public.profiles(id,display_name) values($1,$2)',[id,'Teste']);}
 await as(owner);a=(await scalar<{companyId:string}>('select public.begin_company_onboarding($1)',[randomUUID()])).companyId;
 await as(other);b=(await scalar<{companyId:string}>('select public.begin_company_onboarding($1)',[randomUUID()])).companyId;
 await db.exec('reset role');await db.query("update public.companies set timezone='UTC' where id in($1,$2)",[a,b]);await db.query("insert into public.company_members(company_id,user_id,role) values($1,$2,'attendant')",[a,attendant]);await as(owner);
 },120000);
 afterAll(async()=>{await db?.close();});
 it('parses CSV without assuming consent or unknown attendance and rejects duplicate IDs',()=>{const header='id_aluno;nome;telefone;nascimento;ultima_presenca;situacao;autoriza_mensagens;grupo\n';const row='1;"Ana; Maria";+5511999999999;;;ativo;nao;';const parsed=parseStudentsCsv(header+row);expect(parsed[0]).toMatchObject({name:'Ana; Maria',consent:false,lastAttendance:null,birthday:null});expect(()=>parseStudentsCsv(header+row+'\n'+row)).toThrow('duplicado');expect(messageCampaignSchema.safeParse({...input(),message:'{{senha}}'}).success).toBe(false);expect(personalizeCampaign('Olá {{ nome }} da {{academia}}',{name:'Ana',daysAbsent:null},'Academia')).toBe('Olá Ana da Academia');});
 it('does not infer Meta readiness from an unrelated permission or missing Page task',()=>{expect(metaPermissions([])).not.toContain('read_insights');expect(metaPermissions(['ads','messaging'])).toContain('pages_messaging');expect(metaAccess(['instagram_content_publish'],null).instagramPublishing).toBe(false);expect(metaAccess(['pages_manage_posts','pages_read_engagement'],null,[]).facebookPublishing).toBe(false);expect(metaAccess(['pages_manage_posts','pages_read_engagement'],null,['CREATE_CONTENT']).facebookPublishing).toBe(true);});
 it('imports per company and denies direct tables and attendant campaign changes',async()=>{await scalar('select public.import_campaign_students($1,$2::jsonb)',[a,JSON.stringify([student('one','+5511999999001')])]);expect(await scalar('select count(*)::int from public.campaign_students')).toBe(1);await expect(db.query("update public.campaign_students set consent=true")).rejects.toThrow();await as(other);expect(await scalar('select count(*)::int from public.campaign_students')).toBe(0);await expect(scalar('select public.import_campaign_students($1,$2::jsonb)',[a,JSON.stringify([student('leak','+5511999999002')])])).rejects.toThrow('Access denied');await as(attendant);await expect(scalar('select public.save_message_campaign($1,$2::jsonb)',[a,JSON.stringify(input())])).rejects.toThrow('Access denied');await as(owner);});
 it('previews only fresh, consented, active birthdays and requires current revision',async()=>{await scalar('select public.import_campaign_students($1,$2::jsonb)',[a,JSON.stringify([student('no-consent','+5511999999002',{consent:false}),student('inactive','+5511999999003',{status:'inactive'}),student('unknown','+5511999999004',{birthday:null}),student('stale','+5511999999005')])]);await db.exec('reset role');await db.query("update public.campaign_students set updated_at=now()-interval '10 days' where external_id='stale'");await as(owner);const campaign=input();await scalar('select public.save_message_campaign($1,$2::jsonb)',[a,JSON.stringify(campaign)]);expect((await scalar<{total:number}>('select public.preview_message_campaign($1,$2)',[a,campaign.id])).total).toBe(1);await expect(scalar('select public.save_message_campaign($1,$2::jsonb)',[a,JSON.stringify(campaign)])).rejects.toThrow('Campaign changed');await expect(scalar('select public.activate_message_campaign($1,$2,1,true)',[a,campaign.id])).rejects.toThrow('Connect WhatsApp');});
 it('rechecks changed attendance before dispatch and prevents duplicates after uncertain sends',async()=>{const campaign={...input(),trigger:'absence',tag:'absence-test'};await db.exec('reset role');await db.query("update public.campaign_students set tag='absence-test' where company_id=$1 and external_id='one'",[a]);await as(owner);await scalar('select public.save_message_campaign($1,$2::jsonb)',[a,JSON.stringify(campaign)]);await db.exec('reset role');await db.query("insert into public.company_channels(company_id,provider,remote_id,name,status) values($1,'evolution','askadia-'||$1::uuid::text,'Fixture','connected')",[a]);await db.query("update public.message_campaigns set send_time=(now() at time zone 'UTC')::time-interval '1 minute' where id=$1",[campaign.id]);await as(owner);await scalar('select public.activate_message_campaign($1,$2,1,true)',[a,campaign.id]);await db.exec('reset role;set role service_role');const job=await scalar<{id:string;token:string;companyId:string}>('select public.claim_message_campaign()');expect(job.companyId).toBe(a);expect(await scalar('select public.claim_message_campaign()')).toBeNull();await db.exec('reset role');await db.query("update public.campaign_students set last_attendance=now() where company_id=$1 and external_id='one'",[a]);await db.exec('set role service_role');expect(await scalar('select public.prepare_message_campaign($1,$2)',[job.id,job.token])).toBe(false);
 await db.exec('reset role');await db.query("update public.campaign_students set last_attendance=now()-interval '8 days' where company_id=$1 and external_id='one'",[a]);await db.exec('set role service_role');const next=await scalar<{id:string;token:string}>('select public.claim_message_campaign()');expect(await scalar('select public.prepare_message_campaign($1,$2)',[next.id,next.token])).toBe(true);await scalar('select public.finish_message_campaign($1,$2,false,null)',[next.id,next.token]);expect(await scalar('select public.claim_message_campaign()')).toBeNull();await as(owner);const count=await scalar<number>("select count(*)::int from public.message_campaign_deliveries where state='uncertain'");expect(count).toBe(1);
 });
 it('revokes integration keys, rejects stale/replayed changed data and cannot choose a different company',async()=>{await as(owner);await scalar('select public.set_management_ingestion_key($1,$2,$3)',[a,randomUUID(),'a'.repeat(64)]);const event=randomUUID(),data=JSON.stringify([student('api-one','+5511999999006')]),observed=new Date().toISOString();await db.exec('reset role;set role service_role');expect(await scalar('select public.ingest_management_students($1,$2,$3,$4::jsonb,$5)',['a'.repeat(64),event,observed,data,'b'.repeat(64)])).toEqual({duplicate:false,imported:1});expect(await scalar('select public.ingest_management_students($1,$2,$3,$4::jsonb,$5)',['a'.repeat(64),event,observed,data,'b'.repeat(64)])).toEqual({duplicate:true,imported:0});await expect(scalar('select public.ingest_management_students($1,$2,$3,$4::jsonb,$5)',['a'.repeat(64),event,observed,data,'c'.repeat(64)])).rejects.toThrow('Event changed');await as(other);expect(await scalar('select count(*)::int from public.campaign_students')).toBe(0);await expect(scalar('select public.set_management_ingestion_key($1,$2,$3)',[a,randomUUID(),'d'.repeat(64)])).rejects.toThrow('Owner required');await as(owner);await scalar('select public.set_management_ingestion_key($1,$2,null)',[a,randomUUID()]);await db.exec('reset role;set role service_role');await expect(scalar('select public.ingest_management_students($1,$2,$3,$4::jsonb,$5)',['a'.repeat(64),randomUUID(),observed,data,'b'.repeat(64)])).rejects.toThrow('Invalid integration authorization');await as(owner);});
});
