import {afterEach,describe,expect,it,vi} from 'vitest';
import {sealChannel,openChannel,metaConfigured,ensureEvolutionInstance} from '../apps/api/src/onboarding/channels';
import {designCreative} from '../apps/api/src/onboarding/content';
import {strategyOutputSchema} from '../packages/contracts/src/strategy';
import type {CalendarItem} from '../packages/contracts/src/calendar';
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();});
describe('Creative references and tenant credential vault',()=>{
 it('keeps Meta OAuth unavailable until the HTTPS deployment origin is configured',()=>{vi.stubEnv('META_APP_ID','123');vi.stubEnv('META_APP_SECRET','test');vi.stubEnv('META_GRAPH_API_VERSION','v26.0');vi.stubEnv('SECRETS_ENCRYPTION_KEY','a'.repeat(64));vi.stubEnv('WEB_ORIGIN','http://127.0.0.1:3000');expect(metaConfigured()).toBe(false);vi.stubEnv('WEB_ORIGIN','https://askadia.example');expect(metaConfigured()).toBe(true);});
 it('creates the company instance after Evolution 404 and reuses an existing instance',async()=>{vi.stubEnv('EVOLUTION_API_URL','https://evolution.example');vi.stubEnv('EVOLUTION_API_KEY','fixture');const mock=vi.fn().mockResolvedValueOnce(new Response('{}',{status:404})).mockResolvedValueOnce(new Response('{}',{status:201})).mockResolvedValueOnce(new Response(JSON.stringify([{name:'askadia-company'}]),{status:200}));vi.stubGlobal('fetch',mock);await ensureEvolutionInstance('askadia-company');expect(mock.mock.calls[1]![0].pathname).toBe('/instance/create');expect(JSON.parse(mock.mock.calls[1]![1].body).instanceName).toBe('askadia-company');await ensureEvolutionInstance('askadia-company');expect(mock).toHaveBeenCalledTimes(3);});
 it('does not create instances after an authentication error',async()=>{vi.stubEnv('EVOLUTION_API_URL','https://evolution.example');vi.stubEnv('EVOLUTION_API_KEY','fixture');const mock=vi.fn().mockResolvedValue(new Response('{}',{status:401}));vi.stubGlobal('fetch',mock);await expect(ensureEvolutionInstance('askadia-company')).rejects.toThrow('credencial');expect(mock).toHaveBeenCalledTimes(1);});
 it('encrypts credentials with authenticated company binding',()=>{vi.stubEnv('SECRETS_ENCRYPTION_KEY','a'.repeat(64));const sealed=sealChannel('company-a',{token:'private-fixture'});expect(sealed).not.toContain('private-fixture');expect(openChannel('company-a',sealed)).toEqual({token:'private-fixture'});expect(()=>openChannel('company-b',sealed)).toThrow();expect(()=>openChannel('company-a',sealed.slice(0,-5))).toThrow();});
 it('passes selected real image bytes and approved directions to Gemini',async()=>{vi.stubEnv('GEMINI_API_KEY','test');vi.stubEnv('GEMINI_IMAGE_MODEL','gemini-3-pro-image');const mocked=vi.fn().mockResolvedValue(new Response(JSON.stringify({candidates:[{content:{parts:[{inlineData:{mimeType:'image/png',data:Buffer.from('test-image').toString('base64')}}]}}]}),{status:200}));vi.stubGlobal('fetch',mocked);
  const item={format:'imagem',idea:'Apresentar estrutura',direction:'Valorizar espaço real',details:{title:'Conheça nosso espaço',designBrief:'Preservar logo',slides:[]}} as unknown as CalendarItem;
  const file={mime:'image/png',data:Buffer.from('customer-logo').toString('base64'),name:'logo.png'};const result=await designCreative({facts:{},item},0,[file]);expect(result.mime).toBe('image/png');const sent=JSON.parse(mocked.mock.calls[0]![1].body);expect(sent.contents[0].parts[0].text).toContain('Valorizar espaço real');expect(sent.contents[0].parts[2].inlineData).toEqual({mimeType:'image/png',data:file.data});
 });
 it('reports quota failures without claiming a creative exists',async()=>{vi.stubEnv('GEMINI_API_KEY','test');vi.stubEnv('GEMINI_IMAGE_MODEL','gemini-3-pro-image');vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('{}',{status:429})));await expect(designCreative({facts:{},item:{format:'imagem',details:{title:'Título',designBrief:'Marca'},idea:'Ideia'} as CalendarItem},0)).rejects.toThrow('limite ou crédito');});
 it('requires exactly twelve ideas for every new strategy',()=>{const item={week:1,format:'imagem',theme:'Tema',brief:'Intenção',needsClientVideo:false};const output={positioning:'Posição',objectives:[{goal:'Meta',metric:'Métrica',suggestedTarget:'Proposta'}],calendar:Array.from({length:12},()=>item),ads:[],keywords:Array.from({length:20},(_,i)=>'palavra '+i),unknowns:[]};expect(strategyOutputSchema.safeParse(output).success).toBe(true);expect(strategyOutputSchema.safeParse({...output,calendar:output.calendar.slice(0,4)}).success).toBe(false);});
});
