import {afterEach,describe,expect,it,vi} from 'vitest';
import {conversationMetrics} from '../apps/api/src/inbox/customer-history';
import {encodeMetaThread,decodeMetaThread,metaThreads,metaMessages,type MetaContext} from '../apps/api/src/inbox/meta';
import {metaAccess} from '../packages/contracts/src/meta';
import {validatePaidBudget,paidPlanSchema} from '../apps/api/src/campaigns/ads-controller';
import type {InboxMessage} from '../packages/contracts/src/inbox';
const company='90000000-0000-4000-8000-000000000010';
const msg=(id:string,time:string|null,fromMe=false):InboxMessage=>({id,time,fromMe,body:id,kind:'text',status:'received'});
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();});
describe('Customer history and advertising isolation',()=>{
 it('pairs incoming bursts with first response, deduplicates and keeps unpaired messages pending',()=>{const sample=[msg('1','2026-09-22T09:00:00Z'),msg('2','2026-09-22T09:01:00Z'),msg('3','2026-09-22T09:05:00Z',true),msg('3','2026-09-22T09:05:00Z',true),msg('4','2026-09-22T10:00:00Z'),msg('5',null)];const m=conversationMetrics(sample.reverse());expect(m.firstResponseMs).toBe(300000);expect(m.averageResponseMs).toBe(300000);expect(m.responseCount).toBe(1);expect(m.awaitingSince).toBe('2026-09-22T10:00:00.000Z');expect(conversationMetrics([]).firstResponseMs).toBeNull();});
 it('binds a Meta conversation to company and page, denying tampering',()=>{vi.stubEnv('SECRETS_ENCRYPTION_KEY','a'.repeat(64));const ref={company,page:'123456789',channel:'instagram' as const,conversation:'t_1234',peer:'998877'};const token=encodeMetaThread(ref);expect(decodeMetaThread(token,company,ref.page)).toEqual(ref);expect(()=>decodeMetaThread(token,'90000000-0000-4000-8000-000000000011',ref.page)).toThrow();expect(()=>decodeMetaThread(token,company,'999')).toThrow();expect(()=>decodeMetaThread(token.slice(0,-5)+'aaaaa',company,ref.page)).toThrow();});
 it('requests only the bound Page and never follows provider next URLs',async()=>{vi.stubEnv('SECRETS_ENCRYPTION_KEY','a'.repeat(64));vi.stubEnv('META_GRAPH_API_VERSION','v26.0');const context:MetaContext={page:'123456789',instagram:'987654321',token:'fixture',access:metaAccess(['instagram_basic','instagram_manage_messages'], '987654321',['MESSAGING'])};const fetcher=vi.fn().mockResolvedValue(new Response(JSON.stringify({data:[{id:'t_123',participants:{data:[{id:'987654321'},{id:'111111111',name:'Cliente'}]},messages:{data:[{id:'m',message:'Olá'}]}}],paging:{next:'https://attacker.example/steal',cursors:{after:'cursor'}}})));vi.stubGlobal('fetch',fetcher);const list=await metaThreads(context,company,'instagram');expect(list.threads[0]?.channel).toBe('instagram');expect(new URL(fetcher.mock.calls[0]![0]).pathname).toBe('/v26.0/123456789/conversations');expect(fetcher).toHaveBeenCalledTimes(1);expect(()=>decodeMetaThread(list.threads[0]!.id,company,'9999')).toThrow();});
 it('denies missing Meta permission before fetching and filters unrelated message participants',async()=>{vi.stubEnv('META_GRAPH_API_VERSION','v26.0');const denied:MetaContext={page:'123456789',instagram:null,token:'fixture',access:metaAccess([],null)};const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);await expect(metaThreads(denied,company,'facebook')).rejects.toThrow('Permissão');expect(fetcher).not.toHaveBeenCalled();const granted={...denied,access:metaAccess(['pages_messaging'],null,['MESSAGING'])};fetcher.mockResolvedValue(new Response(JSON.stringify({data:[{id:'one',message:'Olá',from:{id:'111111111'}},{id:'wrong',message:'Outro contato',from:{id:'222222222'}}]})));const result=await metaMessages(granted,{company,page:granted.page,channel:'facebook',conversation:'t_123',peer:'111111111'});expect(result.messages.map(m=>m.id)).toEqual(['one']);});
 it('rejects proposals exceeding budget and missing fields',()=>{const campaign={name:'Busca local',provider:'google' as const,objective:'Visitas',investment:1000,audience:'Local',region:'São Paulo',media:['Pesquisa'],creativeBrief:'Texto',copy:'Conheça',rationale:'Procura local'};expect(validatePaidBudget({summary:'Proposta',campaigns:[campaign],unknowns:[]},1000)).toBe(true);expect(validatePaidBudget({summary:'Proposta',campaigns:[campaign,{...campaign,investment:1}],unknowns:[]},1000)).toBe(false);expect(validatePaidBudget({summary:'',campaigns:[],unknowns:[]},1000)).toBe(false);expect(paidPlanSchema.safeParse({campaigns:[{name:'Fake'}]}).success).toBe(false);});
});
