import { describe,it,expect } from 'vitest';
import { calculateFinance,aggregateAds,engagement,comparisonPeriod,presetPeriod,dateInZone,LatestRequest,dashboardQuerySchema,keywordCandidates,trendGroups,parseCsv,csvCell,parseDashboardCsv,type DashboardFact,type PaymentFact,type TrendFact } from '../packages/contracts/src/dashboard';
import { buildDashboard,type DashboardRaw } from '../apps/api/src/dashboard/engine';
const id='50000000-0000-4000-8000-000000000001';
const query=dashboardQuerySchema.parse({companyId:id,start:'2026-09-01',end:'2026-09-21',timezone:'America/Sao_Paulo',comparison:'none'});
const input={mediaCents:300000,otherAcquisitionCents:100000,newCustomers:20,mediaCustomers:20,attributedNetCents:1000000,mediaAttributedNetCents:1000000,variableCostCents:300000,scopeComplete:true};
const payment:PaymentFact={kind:'payment',id:'p1',date:'2026-09-02',customerId:'c1',netCents:10000,variableCostCents:2000,acquisitionDate:'2026-09-02',customerHistoryKnown:true,customerPreexisting:false,channel:'meta_ads',campaignId:'campaign1',evidence:'lead:1',classification:'acquisition'};
function raw(facts:DashboardFact[]):DashboardRaw{return {company:{id,name:'Empresa de teste',city:'São Paulo',segment:'gym',timezone:query.timezone},permissions:{digital:true,finance:true,writeDigital:true,writeFinance:true},facts:facts.map(payload=>({payload,source:'test-only',revision:1,updatedAt:'2026-09-21T12:00:00Z'})),coverage:[{source:'test-only',domain:'finance',start:query.start,end:query.end,complete:true,note:'Fixture de teste, nunca produção',updatedAt:'2026-09-21T12:00:00Z'}],crm:[]};}
describe('Dashboard deterministic finance and scope',()=>{
 it('reproduces the requested 75% example without display rounding',()=>{const m=Object.fromEntries(calculateFinance(input).map(m=>[m.id,m]));expect(m.cac_media!.value).toBe(150);expect(m.cac!.value).toBe(200);expect(m.roas!.value).toBeCloseTo(10/3);expect(m.margin!.value).toBe(7000);expect(m.roi!.value).toBe(75);});
 it('keeps missing costs distinct from explicitly confirmed zero',()=>{expect(calculateFinance({...input,otherAcquisitionCents:null}).find(m=>m.id==='roi')?.value).toBeNull();expect(calculateFinance({...input,variableCostCents:null}).find(m=>m.id==='roi')?.value).toBeNull();expect(calculateFinance({...input,otherAcquisitionCents:0}).find(m=>m.id==='roi')?.value).toBeCloseTo(133.333333);});
 it('does not divide by zero clients or zero media',()=>{for(const m of calculateFinance({...input,mediaCents:0,otherAcquisitionCents:0,newCustomers:0,mediaCustomers:0}).filter(m=>['cac','cac_media','roas','roi'].includes(m.id)))expect(m.value).toBeNull();});
 it('weights ad rates by totals and refuses incompatible scopes',()=>{const base={currency:'BRL',timezone:query.timezone,dateBasis:'interaction',clickType:'all'};const a=[{...base,spendCents:1000,impressions:100,clicks:10},{...base,spendCents:1000,impressions:1000,clicks:10}];expect(aggregateAds(a).ctr).toBeCloseTo(20/1100*100);expect(aggregateAds(a).cpc).toBe(1);expect(()=>aggregateAds([...a,{...a[0]!,timezone:'UTC'}])).toThrow();expect(aggregateAds([a[0]!,{...a[1]!,clickType:'link'}]).clicks).toBeNull();expect(engagement([1,null,2,3],100)).toBeNull();});
 it('uniquely counts first paid customers and excludes preexisting, renewal, reactivation and unknown history',()=>{const r=raw([payment,{...payment,id:'p2',classification:'renewal'},{...payment,id:'p3',customerId:'old',customerPreexisting:true},{...payment,id:'p4',customerId:'unknown',customerHistoryKnown:false},{...payment,id:'p5',customerId:'reactivation',classification:'reactivation'}]);const s=buildDashboard(r,query);expect(s.metrics.find(m=>m.id==='customers')?.value).toBe(1);expect(s.metrics.find(m=>m.id==='revenue')?.value).toBe(200);});
 it('late refunds change cohort net revenue and appear on the event day, without a second sale',()=>{const r=raw([payment,{kind:'refund',id:'r1',paymentId:'p1',date:'2026-10-01',cents:3000,variableCostReversalCents:0}]);const before=buildDashboard(r,query);expect(before.metrics.find(m=>m.id==='revenue')?.value).toBe(100);const after=buildDashboard(r,{...query,mode:'cohort',observationEnd:'2026-10-02'});expect(after.metrics.find(m=>m.id==='revenue')?.value).toBe(70);expect(after.series.find(p=>p.date==='2026-10-01')?.attributedRevenueBRL).toBe(-30);expect(after.series.reduce((sum,p)=>sum+(p.attributedRevenueBRL??0),0)).toBe(70);expect(after.metrics.find(m=>m.id==='customers')?.value).toBe(1);expect(after.metrics.find(m=>m.id==='roi')?.value).toBeNull();});

 it('an invalid Instagram record does not suppress valid financial facts',()=>{const r=raw([payment]);r.facts.push({source:'instagram-test',revision:1,updatedAt:'2026-09-21T12:00:00Z',payload:{kind:'social',id:'invalid'}});const s=buildDashboard(r,query);expect(s.metrics.find(m=>m.id==='revenue')?.value).toBe(100);expect(s.limitations.some(l=>l.includes('incompatível'))).toBe(true);});
 it('does not count a future first payment as an acquisition in the current period',()=>{const s=buildDashboard(raw([{...payment,date:'2026-10-01'}]),query);expect(s.metrics.find(m=>m.id==='customers')?.value).toBe(0);});
 it('account filters cannot produce fake zero financial results',()=>{const s=buildDashboard(raw([payment]),{...query,account:'ad-account'});expect(s.metrics.find(m=>m.id==='customers')?.value).toBeNull();});
 it('never includes revenue from old cohorts into new acquisition return',()=>{const s=buildDashboard(raw([{...payment,acquisitionDate:'2026-08-01'}]),query);expect(s.metrics.find(m=>m.id==='revenue')?.value).toBe(0);});
 it('blocks financial details and cross-company snapshots',()=>{const r=raw([payment]);r.permissions.finance=false;const s=buildDashboard(r,query);expect(s.metrics.find(m=>m.id==='revenue')?.state).toBe('forbidden');expect(s.series[0]?.attributedRevenueBRL).toBeNull();expect(()=>buildDashboard(r,{...query,companyId:crypto.randomUUID()})).toThrow('Empresa');});
 it('requires matching snapshot temporal scope for Instagram activity and never sums reach',()=>{const social:DashboardFact={kind:'social',id:'ig1',date:'2026-09-10',accountId:'ig',publishedAt:'2026-09-03T12:00:00Z',caption:'Teste',permalink:'https://www.instagram.com/p/test/',format:'image',temporal:'lifetime',intervalStart:null,intervalEnd:null,reach:100,likes:10,comments:2,saves:3,shares:1,views:null,collectedAt:'2026-09-21T12:00:00Z'};const r=raw([social,{...social,id:'ig2',reach:80}]);expect(buildDashboard(r,query).social).toHaveLength(2);expect(buildDashboard(r,{...query,socialMode:'activity'}).social).toHaveLength(0);});
});
describe('Dashboard dates, races and imports',()=>{
 it('uses equal duration for partial month and handles year/leap boundaries',()=>{expect(presetPeriod('month','2026-09-21')).toEqual({start:'2026-09-01',end:'2026-09-21'});expect(comparisonPeriod({...query,comparison:'previous'})).toEqual({start:'2026-08-11',end:'2026-08-31'});expect(comparisonPeriod({start:'2024-02-29',end:'2024-02-29',comparison:'year'})).toEqual({start:'2023-02-28',end:'2023-02-28'});expect(dateInZone(new Date('2026-09-01T01:00:00Z'),query.timezone)).toBe('2026-08-31');});
 it('invalidates responses after rapid company changes even when transport cannot abort',()=>{const latest=new LatestRequest();const a=latest.begin(),b=latest.begin();expect(a.signal.aborted).toBe(true);expect(a.current()).toBe(false);expect(b.current()).toBe(true);latest.cancel();expect(b.current()).toBe(false);});
 it('preserves quoted CSV, delimiter and neutralizes spreadsheet formula injection',()=>{expect(parseCsv('kind;id;note\npayment;p1;"a,b; c"')[1]).toEqual(['payment','p1','a,b; c']);expect(csvCell('=HYPERLINK("bad")')).toContain("'=");expect(()=>parseCsv('a,"unterminated')).toThrow();});
 it('validates import metadata and rejects duplicate source keys',()=>{const headers=Object.keys(payment);const csv=[headers.join(','),headers.map(k=>JSON.stringify(payment[k as keyof PaymentFact]??'')).join(',')].join('\n');const metadata={source:'gestao',domain:'finance' as const,coverageStart:query.start,coverageEnd:query.end,coverage:'complete' as const,note:'Arquivo de teste'};expect(parseDashboardCsv(csv,metadata).records).toHaveLength(1);expect(()=>parseDashboardCsv(csv+'\n'+csv.split('\n')[1],metadata)).toThrow('duplicado');});
});
describe('Trends evidence',()=>{
 it('produces 20 editorial candidates without unconfirmed services',()=>{const terms=keywordCandidates({confirmed:true,city:'Curitiba',segment:'gym',services:['musculação']});expect(terms).toHaveLength(20);expect(terms.every(t=>!t.measured)).toBe(true);expect(terms.some(t=>/pilates|spinning|TotalPass|24 horas/.test(t.term))).toBe(false);expect(keywordCandidates({confirmed:false,city:'',segment:'gym',services:[]})).toEqual([]);});
 it('keeps normalized batches and regions separate and refuses unequal periods',()=>{const t:TrendFact={kind:'trend',id:'t1',date:'2026-09-01',term:'academia',termType:'search_term',region:'Brasil',language:'pt-BR',searchType:'web',batchId:'b1',scale:'relative_0_100',value:100,coverage:'sufficient',sourceUrl:'https://trends.google.com/trends/explore',collectedAt:'2026-09-21T12:00:00Z'};expect(trendGroups([t,{...t,id:'t2',batchId:'b2'}])).toHaveLength(2);expect(trendGroups([t,{...t,id:'t3',region:'Curitiba'}])).toHaveLength(2);const group=trendGroups([t,{...t,id:'t4',date:'2026-09-02'},{...t,id:'t5',term:'estúdio'}])[0]!;expect(group.ranking.find(r=>r.term==='estúdio')?.interest).toBeNull();});
});
