import { beforeAll,afterAll,describe,it,expect } from 'vitest';
import { PGlite } from '@electric-sql/pglite';
import { readFileSync,readdirSync } from 'node:fs';
const owner='51000000-0000-4000-8000-000000000001',other='51000000-0000-4000-8000-000000000002',marketing='51000000-0000-4000-8000-000000000003';
let db:PGlite,a:string,b:string;
async function as(user:string){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);await db.exec('set role authenticated');}
async function scalar<T>(sql:string,args:unknown[]=[]):Promise<T>{return Object.values((await db.query<Record<string,T>>(sql,args)).rows[0]!)[0]!;}
const record={kind:'payment',id:'pay1',date:'2026-09-01',customerId:'client1',netCents:10000,variableCostCents:2000,acquisitionDate:'2026-09-01',customerHistoryKnown:true,customerPreexisting:false,channel:'meta_ads',campaignId:'campaign1',evidence:'lead1',classification:'acquisition'};
const document={source:'gestao-teste',domain:'finance',coverageStart:'2026-09-01',coverageEnd:'2026-09-21',coverage:'complete',note:'Fixture local, não produção',records:[record]};
describe('Dashboard PostgreSQL authorization, audit and revisions',()=>{
 beforeAll(async()=>{
  db=new PGlite();
  await db.exec(`
   create role anon nologin;create role authenticated nologin;
   create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');
   create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
   grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;
   create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
   create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets(id),name text);
   alter table storage.objects enable row level security;grant usage on schema storage to authenticated,anon;grant select,insert,update,delete on storage.objects to authenticated;
  `);
  for(const file of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db.exec(readFileSync('supabase/migrations/'+file,'utf8').replace('create extension if not exists pgcrypto;',''));
  for(const user of [owner,other,marketing]){await db.query("insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())",[user,user+'@example.test']);await db.query("insert into public.profiles(id,display_name) values($1,'Teste')",[user]);}
  await as(owner);const wa=await scalar<string>("select public.create_workspace('Workspace A')");
  a=(await scalar<{id:string}>("select row_to_json(public.create_company($1,'Empresa A','gym','','America/Sao_Paulo'))",[wa])).id;
  await as(other);const wb=await scalar<string>("select public.create_workspace('Workspace B')");
  b=(await scalar<{id:string}>("select row_to_json(public.create_company($1,'Empresa B','gym','','America/Sao_Paulo'))",[wb])).id;
  await db.exec('reset role');await db.query("insert into public.company_members(company_id,user_id,role) values($1,$2,'marketing')",[a,marketing]);
 },90000);
 afterAll(async()=>{await db?.close();});
 it('allows owner import and makes replay exactly idempotent',async()=>{await as(owner);expect(await scalar('select dashboard_import($1,$2)',[a,JSON.stringify(document)])).toMatchObject({written:1,duplicate:false});expect(await scalar('select dashboard_import($1,$2)',[a,JSON.stringify(document)])).toMatchObject({written:0,duplicate:true});expect(await scalar("select count(*)::int from dashboard_facts")).toBe(1);});
 it('versions corrections and records audit without changing customer/payment identity',async()=>{await as(owner);const changed={...document,records:[{...record,netCents:8000}]};expect(await scalar('select dashboard_import($1,$2)',[a,JSON.stringify(changed)])).toMatchObject({written:1});expect(await scalar("select revision from dashboard_facts where external_id='pay1'")).toBe(2);expect(await scalar("select count(*)::int from dashboard_fact_revisions where external_id='pay1'")).toBe(2);expect(await scalar("select count(*)::int from audit_logs where action='dashboard.imported'")).toBe(2);});
 it('rejects unauthorized read, import, export and direct table mutations',async()=>{await as(other);expect(await scalar("select count(*)::int from dashboard_facts")).toBe(0);await expect(db.query('select dashboard_read($1)',[a])).rejects.toThrow('access denied');await expect(db.query('select dashboard_import($1,$2)',[a,JSON.stringify(document)])).rejects.toThrow('Access denied');await expect(db.query("select dashboard_record_export($1,'{}','{}','test')",[a])).rejects.toThrow('permission');await expect(db.query("update dashboard_facts set revision=999 where company_id=$1",[a])).rejects.toThrow('permission');});
 it('requires separate financial rights for marketing and revocation applies immediately',async()=>{await as(marketing);const empty=await scalar<{facts:unknown[];permissions:{finance:boolean}}>('select dashboard_read($1)',[a]);expect(empty.permissions.finance).toBe(false);expect(empty.facts).toEqual([]);await expect(db.query('select dashboard_import($1,$2)',[a,JSON.stringify(document)])).rejects.toThrow('Access denied');await as(owner);await db.query('select dashboard_grant($1,$2,true,false)',[a,marketing]);await as(marketing);expect((await scalar<{facts:unknown[]}>('select dashboard_read($1)',[a])).facts).toHaveLength(1);await expect(db.query('select dashboard_import($1,$2)',[a,JSON.stringify(document)])).rejects.toThrow('Access denied');await as(owner);await db.query('select dashboard_grant($1,$2,false,false)',[a,marketing]);await as(marketing);expect((await scalar<{facts:unknown[]}>('select dashboard_read($1)',[a])).facts).toEqual([]);});
 it('rolls back cross-domain records and cannot overwrite another company import',async()=>{await as(owner);const invalid={...document,source:'invalid',domain:'digital'};await expect(db.query('select dashboard_import($1,$2)',[a,JSON.stringify(invalid)])).rejects.toThrow('Invalid record scope');expect(await scalar("select count(*)::int from dashboard_imports where source='invalid'")).toBe(0);await expect(db.query('select dashboard_import($1,$2)',[b,JSON.stringify(document)])).rejects.toThrow('Access denied');});
 it('stores a private reproducible export and audits it',async()=>{await as(owner);const snapshot={company:{id:a},methodVersion:'test',metrics:[{id:'revenue',value:80}]};const id=await scalar<string>("select dashboard_record_export($1,$2,$3,'test')",[a,JSON.stringify({companyId:a}),JSON.stringify(snapshot)]);expect(await scalar("select snapshot from dashboard_exports where id=$1",[id])).toEqual(snapshot);await as(other);expect(await scalar("select count(*)::int from dashboard_exports where id=$1",[id])).toBe(0);});

 it('persists only confirmed service keywords with tenant authorization',async()=>{await as(marketing);await db.query("select dashboard_set_keywords($1,ARRAY['musculação'],'Centro')",[a]);const r=await scalar<{keywordProfile:{services:string[];revision:number}}>('select dashboard_read($1)',[a]);expect(r.keywordProfile.services).toEqual(['musculação']);expect(r.keywordProfile.revision).toBe(1);await expect(db.query("select dashboard_set_keywords($1,ARRAY['serviço não permitido'],'')",[a])).rejects.toThrow('Invalid');await as(other);await expect(db.query("select dashboard_set_keywords($1,ARRAY['pilates'],'')",[a])).rejects.toThrow('permission');});
 it('rejects foreign export snapshots, extra sensitive fields and duplicate IDs in a batch',async()=>{await as(owner);await expect(db.query("select dashboard_record_export($1,$2,$3,'test')",[a,JSON.stringify({companyId:b}),JSON.stringify({company:{id:b}})])).rejects.toThrow('mismatch');await expect(db.query('select dashboard_import($1,$2)',[a,JSON.stringify({...document,records:[{...record,healthInformation:'must never be imported'}]})])).rejects.toThrow('Invalid record fields');await expect(db.query('select dashboard_import($1,$2)',[a,JSON.stringify({...document,records:[record,record]})])).rejects.toThrow('Duplicate');});
});
