import { describe,it,expect,vi } from 'vitest';
import { Ga4ReportingAdapter,SearchConsoleReportingAdapter,MetaAdsReportingAdapter,GoogleAdsReportingAdapter,InstagramMediaReportingAdapter,PendingManagementProvider,ReportError,type ReportingSecurity } from '../packages/integrations/src/reporting';
import { processReportingPage,type ReportingJob,type ReportingJobStore } from '../packages/integrations/src/reporting-sync';
import { executivePdf } from '../apps/api/src/dashboard/pdf';
import { parseTrendsCsv } from '../packages/contracts/src/dashboard/csv';
const scope={companyId:'company1',connectionId:'connection1',resource:'12345',start:'2026-09-01',end:'2026-09-21',timezone:'America/Sao_Paulo'};
function setup(body:unknown,status=200){
 const authorize=vi.fn(async()=>{}),credentials=vi.fn(async()=>({accessToken:'test-token',developerToken:'test-developer-token'}));
 const security:ReportingSecurity={authorize,credentials};const transport=vi.fn<typeof fetch>(async()=>new Response(JSON.stringify(body),{status}));
 return {authorize,credentials,security,transport};
}
describe('Reporting read adapters — isolated HTTP fixtures, no external calls',()=>{
 it('checks authorization before exposing credentials or calling the provider',async()=>{const s=setup({});s.authorize.mockRejectedValue(new Error('forbidden'));await expect(new Ga4ReportingAdapter(s.security,s.transport).read(scope)).rejects.toThrow('forbidden');expect(s.credentials).not.toHaveBeenCalled();expect(s.transport).not.toHaveBeenCalled();});
 it('GA4 requests instrumented metrics without claiming unique-user totals or complete coverage',async()=>{const s=setup({rows:[{dimensionValues:[{value:'20260901'}],metricValues:[{value:'10'}]}],rowCount:2});const page=await new Ga4ReportingAdapter(s.security,s.transport).read(scope);expect(page.cursor).toBe('1');expect(page.coverage).toBe('partial');const [,options]=s.transport.mock.calls[0]!;expect(JSON.parse(String(options?.body)).dateRanges).toEqual([{startDate:scope.start,endDate:scope.end}]);expect(options?.redirect).toBe('error');});
 it('Search Console preserves incomplete top-row coverage',async()=>{const s=setup({rows:[]});const page=await new SearchConsoleReportingAdapter(s.security,s.transport).read({...scope,resource:'sc-domain:example.test'});expect(page.coverage).toBe('partial');expect(String(s.transport.mock.calls[0]![0])).toContain('sc-domain%3Aexample.test');});
 it('Meta never follows a provider supplied next URL or sends tokens in URLs',async()=>{const s=setup({data:[],paging:{next:'https://malicious.test/?access_token=secret',cursors:{after:'cursor2'}}});const page=await new MetaAdsReportingAdapter(s.security,'v99.0',s.transport).read(scope);expect(page.cursor).toBe('cursor2');expect(s.transport).toHaveBeenCalledOnce();expect(String(s.transport.mock.calls[0]![0])).not.toContain('access_token');expect(String(s.transport.mock.calls[0]![0])).toContain('/insights?');});
 it('Google Ads rejects resource/query injection and only uses search reporting',async()=>{const s=setup({results:[]});const adapter=new GoogleAdsReportingAdapter(s.security,'v99',s.transport);await expect(adapter.read({...scope,resource:"1' OR 1=1"})).rejects.toThrow('Invalid');expect(s.transport).not.toHaveBeenCalled();await adapter.read(scope);const [url,options]=s.transport.mock.calls[0]!;expect(String(url)).toContain('/googleAds:search');expect(JSON.parse(String(options?.body)).query).toContain("BETWEEN '2026-09-01' AND '2026-09-21'");});
 it('Instagram declares accumulated data and leaves interval insights unsupported',async()=>{const s=setup({data:[]});const adapter=new InstagramMediaReportingAdapter(s.security,'v99.0',s.transport);expect(adapter.supportsIntervalActivity).toBe(false);expect((await adapter.read(scope)).temporal).toBe('lifetime');});
 it('sanitizes provider failures and keeps missing management connector disabled',async()=>{const s=setup({message:'sensitive-token-body'},401);await expect(new Ga4ReportingAdapter(s.security,s.transport).read(scope)).rejects.toThrow('revoked');const pending=new PendingManagementProvider();expect((await pending.testConnection('company1')).state).toBe('unconfigured');await expect(pending.syncPayments(scope)).rejects.toThrow('NOT_CONFIGURED');});
});
describe('Reporting worker handler — repository ports only; not an active consumer',()=>{
 const job:ReportingJob={id:'job1',scope,cursor:null,attempt:0,generation:1};
 function store():ReportingJobStore{return {claim:vi.fn(async()=>true),authorized:vi.fn(async()=>true),commitPage:vi.fn(async()=>{}),fail:vi.fn(async()=>{})};}
 const page={rows:[],cursor:null,temporal:'interval' as const,coverage:'partial' as const,limitations:[]};
 it('does not rerun duplicate jobs',async()=>{const s=store();s.claim=vi.fn(async()=>false);const provider={provider:'test',read:vi.fn(async()=>page)};expect(await processReportingPage(job,provider,s)).toBe('duplicate');expect(provider.read).not.toHaveBeenCalled();});
 it('checks revocation again before committing a response in flight',async()=>{const s=store();s.authorized=vi.fn().mockResolvedValueOnce(true).mockResolvedValueOnce(false);expect(await processReportingPage(job,{provider:'test',read:async()=>page},s)).toBe('revoked');expect(s.commitPage).not.toHaveBeenCalled();});
 it('uses bounded retries and sanitized failures',async()=>{const s=store();const provider={provider:'test',read:async()=>{throw new ReportError('rate_limited',120);}};expect(await processReportingPage(job,provider,s,new Date('2026-09-21T00:00:00Z'))).toBe('retry');expect(s.fail).toHaveBeenCalledWith(job,'rate_limited','2026-09-21T00:02:00.000Z');expect(await processReportingPage({...job,attempt:5},provider,s)).toBe('failed');});
});
describe('Export and Trends provenance',()=>{
 it('creates a private multipage PDF with exact byte cross references and escaped content',()=>{const pdf=executivePdf([['Empresa (ação)'],...Array.from({length:120},(_,i)=>['Linha',i,'R$ 150,00'])]);const text=pdf.toString('latin1');expect(text.startsWith('%PDF-1.4')).toBe(true);expect(text).toContain('/Count 3');expect(text).toContain('Empresa \\(ação\\)');const xref=Number(text.match(/startxref\n(\d+)/)![1]);expect(pdf.subarray(xref,xref+4).toString()).toBe('xref');const rows=text.slice(xref).split('\n').slice(3).filter(r=>/^\d{10} 00000 n/.test(r));for(const [index,row] of rows.entries())expect(pdf.subarray(Number(row.slice(0,10))).toString('latin1').startsWith((index+1)+' 0 obj')).toBe(true);expect(text).not.toContain('/URI');});
 it('requires exact geographic provenance from the Google Trends CSV header',()=>{const meta={batchId:'test',region:'Brasil',collectedAt:'2026-09-21T12:00:00Z',sourceUrl:'https://trends.google.com/trends/explore',language:'pt-BR',searchType:'web',termType:'search_term' as const};expect(parseTrendsCsv('Dia,academia: (Brasil)\n2026-09-01,100',meta)).toHaveLength(1);expect(()=>parseTrendsCsv('Dia,academia: (Brasil)\n2026-09-01,100',{...meta,region:'Curitiba'})).toThrow('região');});
});
