import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {provisionPublishedSite} from '../apps/api/src/sites/hosting';
const fetcher=vi.fn();
beforeEach(()=>{vi.stubGlobal('fetch',fetcher);fetcher.mockReset();for(const [k,v] of Object.entries({WEB_ORIGIN:'https://askadia.com.br',SITES_PLATFORM_DOMAIN:'askadia.com.br',EASYPANEL_API_URL:'http://easypanel:3000/api',EASYPANEL_API_TOKEN:'test-only',EASYPANEL_SITE_PROJECT:'askadia',EASYPANEL_SITE_SERVICE:'askadia',EASYPANEL_CERTIFICATE_RESOLVER:'letsencrypt'}))vi.stubEnv(k,v);});
afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();});
describe('Automatic domain setup after site publication',()=>{
 it('creates the reserved hostname on the fixed company service with HTTPS',async()=>{fetcher.mockResolvedValueOnce(new Response('[]')).mockResolvedValueOnce(new Response('{}'));expect((await provisionPublishedSite('company-a','academia-teste',null)).status).toBe('requested');const [url,options]=fetcher.mock.calls[1]!;expect(String(url)).toBe('http://easypanel:3000/api/createDomain');expect(JSON.parse(options.body)).toMatchObject({host:'academia-teste.askadia.com.br',https:true,path:'/',wildcard:false,destinationType:'service',serviceDestination:{projectName:'askadia',serviceName:'askadia',protocol:'http',port:3000}});});
 it('reuses a matching mapping without creating duplicates when republishing',async()=>{fetcher.mockResolvedValue(new Response(JSON.stringify([{host:'academia-teste.askadia.com.br',https:true,serviceDestination:{projectName:'askadia',serviceName:'askadia',port:3000}}])));expect((await provisionPublishedSite('company-a','academia-teste',null)).status).toBe('requested');expect(fetcher).toHaveBeenCalledTimes(1);});
 it('never provisions an unverified customer domain',async()=>{expect((await provisionPublishedSite('company-a',null,{hostname:'www.academia.com.br',dns_verified_at:null})).status).toBe('pending_verification');expect(fetcher).not.toHaveBeenCalled();});
 it('reports missing server configuration without claiming a live address',async()=>{vi.stubEnv('EASYPANEL_API_TOKEN','');expect((await provisionPublishedSite('company-a','academia-teste',null)).status).toBe('pending_configuration');expect(fetcher).not.toHaveBeenCalled();});
 it('preserves publication on provider failure and refuses a foreign destination',async()=>{fetcher.mockResolvedValue(new Response(JSON.stringify([{host:'academia-teste.askadia.com.br',https:true,serviceDestination:{projectName:'other',serviceName:'other',port:3000}}])));expect((await provisionPublishedSite('company-a','academia-teste',null)).status).toBe('failed');expect(fetcher).toHaveBeenCalledTimes(1);});
 it('requests a verified custom hostname and reports a provider outage for retry',async()=>{fetcher.mockResolvedValue(new Response('unavailable',{status:503}));expect((await provisionPublishedSite('company-a',null,{hostname:'www.academia.com.br',dns_verified_at:'2026-09-23'})).status).toBe('failed');expect(fetcher).toHaveBeenCalledTimes(1);});
});
