import {afterAll,beforeAll,describe,expect,it} from 'vitest';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync,readdirSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {renderSite,siteContentSchema,siteDomain,type SiteContent} from '../packages/contracts/src/site';
import {respectsWeeklyLimit,seasonalContext} from '../apps/api/src/onboarding/seasonal';
let db:PGlite,a:string,b:string;const owner=randomUUID(),other=randomUUID(),staff=randomUUID();
async function as(id:string){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');}
async function scalar<T=unknown>(sql:string,args:unknown[]=[]):Promise<T>{return Object.values((await db.query<Record<string,T>>(sql,args)).rows[0]!)[0]!;}
const content:SiteContent={name:'Academia de teste',headline:'<script>alert(1)</script>',intro:'Rotina',about:'Estrutura confirmada',services:[{title:'Musculação',description:'Orientação'}],address:'Local confirmado',hours:'',offer:'',whatsapp:'5511999999999',cta:'Fale conosco',color:'#25272a',background:'light',images:[],logo:null};
describe('Hosted sites and new authorization bridges',()=>{
 beforeAll(async()=>{db=new PGlite();await db.exec(`create role anon nologin;create role authenticated nologin;create role service_role nologin;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets(id),name text);alter table storage.objects enable row level security;grant usage on schema storage to authenticated,anon;grant select,insert,update,delete on storage.objects to authenticated;`);for(const f of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db.exec(readFileSync('supabase/migrations/'+f,'utf8').replace('create extension if not exists pgcrypto;',''));for(const id of [owner,other,staff]){await db.query('insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())',[id,id+'@example.test']);await db.query('insert into public.profiles(id,display_name) values($1,$2)',[id,'Teste']);}await as(owner);a=(await scalar<{companyId:string}>('select public.begin_company_onboarding($1)',[randomUUID()])).companyId;await as(other);b=(await scalar<{companyId:string}>('select public.begin_company_onboarding($1)',[randomUUID()])).companyId;await db.exec('reset role');await db.query("insert into public.company_members(company_id,user_id,role) values($1,$2,'attendant')",[a,staff]);await db.query("insert into public.company_profile_versions(company_id,version,facts,confirmed_by) values($1,1,'{}',$2),($3,1,'{}',$4)",[a,owner,b,other]);await as(owner);},120000);
 afterAll(async()=>{await db?.close();});
 it('escapes model text and validates URLs, colors and image identifiers',()=>{const html=renderSite(content,id=>id);expect(html).toContain('&lt;script&gt;');expect(html).not.toContain('<script>');expect(html).toContain('https://wa.me/5511999999999');expect(siteContentSchema.safeParse({...content,color:'red; background:url(x)'}).success).toBe(false);for(const d of ['127.0.0.1','localhost','host.internal','https://gym.com','gym.com/path','gym.com:3000','bad..com'])expect(()=>siteDomain(d)).toThrow();expect(siteDomain('WWW.Academia.com.br')).toBe('www.academia.com.br');});
 it('enforces two posts per ISO week even across months',()=>{expect(respectsWeeklyLimit(['2026-09-28','2026-10-01'])).toBe(true);expect(respectsWeeklyLimit(['2026-10-01'],['2026-09-28','2026-09-30'])).toBe(false);expect(respectsWeeklyLimit(['2026-10-01','2026-10-05','2026-10-07'])).toBe(true);expect(seasonalContext('2026-04').verifiedDates[0]?.source).toContain('who.int');expect(seasonalContext('2026-02').verifiedDates).toEqual([]);});
 it('denies cross-company editing, staff changes, direct writes and private image use',async()=>{await as(staff);await expect(scalar('select public.save_company_site($1,0,1,$2)',[a,JSON.stringify(content)])).rejects.toThrow('Access denied');await as(other);await expect(scalar('select public.save_company_site($1,0,1,$2)',[a,JSON.stringify(content)])).rejects.toThrow('Access denied');await as(owner);await expect(db.query("insert into public.company_sites(company_id) values($1)",[a])).rejects.toThrow();await expect(scalar('select public.save_company_site($1,0,1,$2)',[a,JSON.stringify({...content,images:[randomUUID()]})])).rejects.toThrow('Company materials required');await scalar('select public.save_company_site($1,0,1,$2)',[a,JSON.stringify(content)]);await expect(scalar('select public.save_company_site($1,0,1,$2)',[a,JSON.stringify(content)])).rejects.toThrow('Site changed');});
 it('serves only published revisions and keeps edits private until publication',async()=>{await db.exec('reset role;set role service_role');expect(await scalar('select public.read_published_site_server($1,null)',[a])).toBeNull();await as(owner);await scalar('select public.publish_company_site($1,1,true)',[a]);await scalar('select public.save_company_site($1,1,1,$2)',[a,JSON.stringify({...content,headline:'Novo rascunho privado'})]);await db.exec('reset role;set role service_role');expect(await scalar<{content:SiteContent;revision:number}>('select public.read_published_site_server($1,null)',[a])).toMatchObject({revision:1,content:{headline:content.headline}});await as(owner);await scalar('select public.publish_company_site($1,2,false)',[a]);await db.exec('reset role;set role service_role');expect(await scalar('select public.read_published_site_server($1,null)',[a])).toBeNull();await as(owner);});
 it('binds domain verification to owner, domain token and company',async()=>{await as(owner);await scalar('select public.set_site_domain($1,$2)',[a,'www.testgym.com']);const d=await scalar<{hostname:string;verification_token:string}>("select to_jsonb(d) from public.company_site_domains d where company_id=$1",[a]);await as(other);await expect(scalar('select public.set_site_domain($1,$2)',[a,'other.com'])).rejects.toThrow('Owner required');await db.exec('reset role;set role service_role');await expect(scalar('select public.verify_site_domain_server($1,$2,$3,$4)',[a,other,d.hostname,d.verification_token])).rejects.toThrow('Owner required');await scalar('select public.verify_site_domain_server($1,$2,$3,$4)',[a,owner,d.hostname,randomUUID()]);await as(owner);expect(await scalar('select dns_verified_at from public.company_site_domains where company_id=$1',[a])).toBeNull();await db.exec('reset role;set role service_role');await scalar('select public.verify_site_domain_server($1,$2,$3,$4)',[a,owner,d.hostname,d.verification_token]);await as(owner);expect(await scalar('select dns_verified_at from public.company_site_domains where company_id=$1',[a])).not.toBeNull();await scalar('select public.set_site_domain($1,$2)',[a,'new.testgym.com']);expect(await scalar('select dns_verified_at from public.company_site_domains where company_id=$1',[a])).toBeNull();});
 it('protects credential bridges and consumes Google OAuth only for its owner once',async()=>{await as(owner);await expect(scalar('select public.read_company_meta_server($1,$2,$3)',[a,owner,'crm.read'])).rejects.toThrow();await expect(scalar('select public.ad_credentials_server($1,$2,$3,null)',[a,owner,'google'])).rejects.toThrow();const id=randomUUID();await scalar('select public.begin_google_ads($1,$2,$3)',[a,id,'a'.repeat(64)]);await as(other);await expect(scalar('select public.consume_google_ads($1,$2)',[id,'a'.repeat(64)])).rejects.toThrow('OAuth state unavailable');await as(owner);expect(await scalar('select public.consume_google_ads($1,$2)',[id,'a'.repeat(64)])).toBe(a);await expect(scalar('select public.consume_google_ads($1,$2)',[id,'a'.repeat(64)])).rejects.toThrow('OAuth state unavailable');await db.exec('reset role;set role service_role');await expect(scalar('select public.ad_credentials_server($1,$2,$3,$4)',[a,other,'google',JSON.stringify({status:'connected'})])).rejects.toThrow('Access denied');await expect(scalar('select public.read_company_meta_server($1,$2,$3)',[a,other,'crm.read'])).rejects.toThrow('Access denied');await as(owner);});
 it('reserves unique subdomains and never exposes an unpublished site by slug',async()=>{await as(owner);await scalar('select public.set_site_slug($1,$2)',[a,'academia-teste']);await expect(scalar('select public.set_site_slug($1,$2)',[a,'admin'])).rejects.toThrow('Invalid subdomain');await as(other);await expect(scalar('select public.set_site_slug($1,$2)',[b,'academia-teste'])).rejects.toThrow();await expect(scalar('select public.set_site_slug($1,$2)',[a,'academia-outra'])).rejects.toThrow('Owner required');await db.exec('reset role;set role service_role');expect(await scalar('select public.read_published_site_server(null,null,$1)',['academia-teste'])).toBeNull();await as(owner);await scalar('select public.publish_company_site($1,2,true)',[a]);await db.exec('reset role;set role service_role');expect(await scalar<{companyId:string}>('select public.read_published_site_server(null,null,$1)',['academia-teste'])).toMatchObject({companyId:a});await as(owner);await scalar('select public.set_site_slug($1,$2)',[a,'academia-nova']);await db.exec('reset role;set role service_role');expect(await scalar('select public.read_published_site_server(null,null,$1)',['academia-teste'])).toBeNull();await as(owner);});

 it('keeps image catalog private and binds completion to the leased company and token',async()=>{
  const asset=randomUUID();await db.exec('reset role');await db.query("insert into public.onboarding_attachments(id,company_id,name,mime,size,object_path,uploaded_by) values($1,$2,'foto.png','image/png',100,$3,$4)",[asset,a,a+'/foto.png',owner]);
  await as(owner);await expect(scalar('select public.claim_image_description_server()')).rejects.toThrow();await as(other);expect((await db.query('select id from public.onboarding_attachments where id=$1',[asset])).rows).toHaveLength(0);
  await db.exec('reset role;set role service_role');const job=await scalar<{id:string;companyId:string;token:string}>('select public.claim_image_description_server()');expect(job.id).toBe(asset);expect(await scalar('select public.claim_image_description_server()')).toBeNull();
  const description=JSON.stringify({description:'Sala ampla de musculação',category:'space'});
  expect(await scalar('select public.finish_image_description_server($1,$2,$3,$4,$5)',[b,asset,job.token,description,'gemini-test'])).toBe(false);
  expect(await scalar('select public.finish_image_description_server($1,$2,$3,$4,$5)',[a,asset,randomUUID(),description,'gemini-test'])).toBe(false);
  expect(await scalar('select public.finish_image_description_server($1,$2,$3,$4,$5)',[a,asset,job.token,description,'gemini-test'])).toBe(true);
  expect(await scalar('select public.claim_image_description_server()')).toBeNull();await as(owner);expect(await scalar('select description_status from public.onboarding_attachments where id=$1',[asset])).toBe('ready');
 });

});
