import {createCipheriv,createDecipheriv,randomBytes,createHash,randomUUID} from 'node:crypto';
import {BadRequestException,Body,Controller,ForbiddenException,Get,Param,Post,Req,ServiceUnavailableException,UseGuards} from '@nestjs/common';
import {z} from 'zod';
import {AuthGuard,type AuthRequest} from '../identity/auth';
import {result} from '../identity/service';
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
function secretKey(){const s=process.env.SECRETS_ENCRYPTION_KEY;if(!s||!/^[a-f0-9]{64}$/i.test(s))throw new ServiceUnavailableException('O cofre de conexões precisa ser configurado.');return Buffer.from(s,'hex');}
export function sealChannel(company:string,value:unknown){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',secretKey(),iv);cipher.setAAD(Buffer.from(company));const encrypted=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return [iv,cipher.getAuthTag(),encrypted].map(b=>b.toString('base64url')).join('.');}
export function openChannel<T>(company:string,value:string):T{const [iv,tag,encrypted]=value.split('.').map(v=>Buffer.from(v,'base64url'));if(!iv||!tag||!encrypted)throw new Error('Invalid secret');const decipher=createDecipheriv('aes-256-gcm',secretKey(),iv);decipher.setAAD(Buffer.from(company));decipher.setAuthTag(tag);return JSON.parse(Buffer.concat([decipher.update(encrypted),decipher.final()]).toString());}
function parse<T>(s:z.ZodType<T>,v:unknown){const p=s.safeParse(v);if(!p.success)throw new BadRequestException('Confira os dados da conexão.');return p.data;}
async function owner(r:AuthRequest,company:string){parse(z.uuid(),company);const c=result<{actions:string[]}>(await r.actor.client.rpc('company_capabilities',{p_company_id:company}));if(!c.actions.includes('billing.manage'))throw new ForbiddenException('O proprietário precisa autorizar a conexão da empresa.');}
export function metaConfigured(){let secureOrigin=false;try{const origin=new URL(process.env.WEB_ORIGIN||'http://127.0.0.1:3000');secureOrigin=origin.protocol==='https:'&&!['localhost','127.0.0.1'].includes(origin.hostname);}catch{/* Invalid deployment origin keeps OAuth unavailable. */}return secureOrigin&&Boolean(process.env.META_APP_ID&&process.env.META_APP_SECRET&&/^v\d+\.\d+$/.test(process.env.META_GRAPH_API_VERSION??'')&&process.env.SECRETS_ENCRYPTION_KEY);}
function metaVersion(){if(!metaConfigured())throw new ServiceUnavailableException('Configure o aplicativo Meta e a origem pública HTTPS da Askadia. Cada empresa fará sua própria autorização depois.');return process.env.META_GRAPH_API_VERSION!;}
const redirect=()=>new URL('/api/connections/meta/callback',process.env.WEB_ORIGIN||'http://127.0.0.1:3000').href;
type MetaPage={id:string;name:string;access_token:string;tasks?:string[];instagram_business_account?:{id:string;username?:string}};
async function graph<T>(path:string,token:string,params:Record<string,string>={}):Promise<T>{const url=new URL('https://graph.facebook.com/'+metaVersion()+'/'+path);for(const [k,v] of Object.entries(params))url.searchParams.set(k,v);const r=await fetch(url,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(12000),redirect:'error'});if(!r.ok)throw new ServiceUnavailableException('A Meta recusou a consulta. Confira as permissões e reconecte a conta.');return r.json() as Promise<T>;}
async function metaPages(token:string){const out:MetaPage[]=[];let after:string|undefined;for(let n=0;n<10;n++){const p: {data:MetaPage[];paging?:{cursors?:{after?:string};next?:string}}=await graph('me/accounts',token,{fields:'id,name,access_token,tasks,instagram_business_account{id,username}',limit:'100',...(after?{after}:{})});out.push(...p.data);if(!p.paging?.next)break;after=p.paging.cursors?.after;if(!after)break;}return out;}
export class EvolutionError extends ServiceUnavailableException{constructor(public readonly providerStatus:number){super(providerStatus===401||providerStatus===403?'A Evolution recusou a credencial. Confira a chave configurada no servidor.':providerStatus===404?'A instância ainda não existe na Evolution.':providerStatus===429?'A Evolution atingiu o limite de solicitações. Tente novamente em instantes.':'A Evolution não concluiu a operação. Confira o servidor e tente novamente.');}}
export async function findEvolutionInstance(instance:string){try{const list=await evolutionRequest('/instance/fetchInstances?instanceName='+encodeURIComponent(instance)) as unknown as {name?:string;instance?:{instanceName?:string}}[];if(!Array.isArray(list))throw new ServiceUnavailableException('A Evolution retornou uma lista de instâncias inválida.');return list.some(i=>(i.name??i.instance?.instanceName)===instance);}catch(e){if(e instanceof EvolutionError&&e.providerStatus===404)return false;throw e;}}
export async function ensureEvolutionInstance(instance:string){if(await findEvolutionInstance(instance))return;try{await evolutionRequest('/instance/create',{instanceName:instance,integration:'WHATSAPP-BAILEYS',qrcode:true,groupsIgnore:true,syncFullHistory:false,readMessages:false,readStatus:false});}catch(e){if(e instanceof EvolutionError&&[400,409].includes(e.providerStatus)&&await findEvolutionInstance(instance))return;throw e;}}
export async function evolutionRequest(path:string,body?:unknown,options?:{timeout:number;maxBytes:number}){const raw=process.env.EVOLUTION_API_URL,key=process.env.EVOLUTION_API_KEY;if(!raw||!key)throw new ServiceUnavailableException('Servidor Evolution ainda não configurado.');const base=new URL(raw);if(base.protocol!=='https:'||base.username||base.password)throw new ServiceUnavailableException('Configure uma URL HTTPS válida para a Evolution.');const response=await fetch(new URL(path,base),{method:body?'POST':'GET',headers:{apikey:key,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(options?.timeout??15000),redirect:'error'});if(!response.ok)throw new EvolutionError(response.status);if(options&&response.body){const reader=response.body.getReader();const chunks:Uint8Array[]=[];let size=0;try{for(;;){const next=await reader.read();if(next.done)break;size+=next.value.length;if(size>options.maxBytes){await reader.cancel();throw new ServiceUnavailableException('Arquivo acima do limite permitido.');}chunks.push(next.value);}return JSON.parse(Buffer.concat(chunks).toString('utf8')) as Record<string,unknown>;}finally{reader.releaseLock();}}return response.json() as Promise<Record<string,unknown>>;}
@Controller('onboarding')
@UseGuards(AuthGuard)
export class ChannelsController{
 @Get('companies/:id/channels') async list(@Req() r:AuthRequest,@Param('id') company:string){parse(z.uuid(),company);const c=result<{actions:string[]}>(await r.actor.client.rpc('company_capabilities',{p_company_id:company}));if(!c.actions.includes('marketing.read'))throw new ForbiddenException();return {channels:result(await r.actor.client.from('company_channels').select('*').eq('company_id',company)),metaConfigured:metaConfigured(),evolutionConfigured:Boolean(process.env.EVOLUTION_API_URL&&process.env.EVOLUTION_API_KEY),canConnect:c.actions.includes('billing.manage'),webhookConfigured:false};}
 @Post('companies/:id/channels/meta/start') async start(@Req() r:AuthRequest,@Param('id') company:string){await owner(r,company);const version=metaVersion(),session=randomUUID(),nonce=randomBytes(32).toString('hex');result(await r.actor.client.rpc('begin_meta_session',{p_company_id:company,p_id:session,p_hash:hash(nonce)}));const url=new URL('https://www.facebook.com/'+version+'/dialog/oauth');url.searchParams.set('client_id',process.env.META_APP_ID!);url.searchParams.set('redirect_uri',redirect());url.searchParams.set('state',session+'.'+nonce);url.searchParams.set('response_type','code');url.searchParams.set('scope','pages_show_list,pages_read_engagement,pages_manage_posts,read_insights,instagram_basic,instagram_content_publish,instagram_manage_insights');return {url:url.href};}
 @Post('channels/meta/callback') async callback(@Req() r:AuthRequest,@Body() body:unknown){
  const input=parse(z.object({state:z.string().regex(/^[a-f0-9-]{36}\.[a-f0-9]{64}$/),code:z.string().min(1).max(4000)}).strict(),body);const [session,nonce]=input.state.split('.');const company=result<string>(await r.actor.client.rpc('consume_meta_session',{p_id:session,p_hash:hash(nonce!)}));await owner(r,company);
  const exchange=new URL('https://graph.facebook.com/'+metaVersion()+'/oauth/access_token');const tokenResponse=await fetch(exchange,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.META_APP_ID!,client_secret:process.env.META_APP_SECRET!,redirect_uri:redirect(),code:input.code}),signal:AbortSignal.timeout(12000),redirect:'error'});if(!tokenResponse.ok)throw new BadRequestException('A autorização Meta expirou ou foi recusada. Tente conectar novamente.');const token=await tokenResponse.json() as {access_token:string;expires_in?:number};if(!token.access_token)throw new BadRequestException('A Meta não retornou autorização.');
  const pages=await metaPages(token.access_token);const permissions=await graph<{data:{permission:string;status:string}[]}>('me/permissions',token.access_token);result(await r.actor.client.rpc('save_meta_selection',{p_id:session,p_cipher:sealChannel(company,{pages,scopes:permissions.data.filter(p=>p.status==='granted').map(p=>p.permission),expiresAt:token.expires_in?new Date(Date.now()+token.expires_in*1000).toISOString():null})}));return {companyId:company,sessionId:session};
 }
 @Post('companies/:id/channels/meta/pages') async pages(@Req() r:AuthRequest,@Param('id') company:string,@Body() body:unknown){await owner(r,company);const {sessionId}=parse(z.object({sessionId:z.uuid()}).strict(),body);const cipher=result<string>(await r.actor.client.rpc('read_meta_selection',{p_company_id:company,p_id:sessionId}));const s=openChannel<{pages:MetaPage[]}>(company,cipher);return {pages:s.pages.map(p=>({id:p.id,name:p.name,instagramId:p.instagram_business_account?.id,instagramName:p.instagram_business_account?.username}))};}
 @Post('companies/:id/channels/meta/select') async select(@Req() r:AuthRequest,@Param('id') company:string,@Body() body:unknown){await owner(r,company);const input=parse(z.object({sessionId:z.uuid(),pageId:z.string().regex(/^\d+$/)}).strict(),body);const cipher=result<string>(await r.actor.client.rpc('read_meta_selection',{p_company_id:company,p_id:input.sessionId}));const session=openChannel<{pages:MetaPage[];scopes:string[];expiresAt:string|null}>(company,cipher);const page=session.pages.find(p=>p.id===input.pageId);if(!page)throw new ForbiddenException('Selecione uma página autorizada.');await graph(page.id,page.access_token,{fields:'id'});return result(await r.actor.client.rpc('save_company_channel',{p_company_id:company,p_provider:'meta',p_remote:page.id,p_name:page.name,p_status:'connected',p_metadata:{instagramId:page.instagram_business_account?.id??null,instagramName:page.instagram_business_account?.username??null,scopes:session.scopes,expiresAt:session.expiresAt,publishingReady:session.scopes.includes('instagram_content_publish')&&Boolean(page.instagram_business_account),insightsReady:session.scopes.includes('instagram_manage_insights')&&Boolean(page.instagram_business_account)},p_cipher:sealChannel(company,{token:page.access_token}),p_session:input.sessionId}));}
 @Post('companies/:id/channels/evolution/connect') async connect(@Req() r:AuthRequest,@Param('id') company:string){await owner(r,company);secretKey();const instance='askadia-'+company;await ensureEvolutionInstance(instance);
  const current=await evolutionRequest('/instance/connectionState/'+encodeURIComponent(instance));if((current.instance as {state?:string}|undefined)?.state==='open'){await this.state(r,company);return {qr:null,message:'WhatsApp já conectado. Abra a Caixa de entrada para consultar suas conversas.'};}
  const qr=await evolutionRequest('/instance/connect/'+encodeURIComponent(instance));result(await r.actor.client.rpc('save_company_channel',{p_company_id:company,p_provider:'evolution',p_remote:instance,p_name:'WhatsApp da empresa',p_status:'pending',p_metadata:{webhookReady:false,transport:'WHATSAPP-BAILEYS'},p_cipher:sealChannel(company,{instance})}));const base64=typeof qr.base64==='string'&&qr.base64.startsWith('data:image/png;base64,')?qr.base64:null;return {qr:base64,message:base64?'Leia o QR code no WhatsApp da empresa.':'QR code indisponível. Confira o estado da instância.'};
 }
 @Post('companies/:id/channels/evolution/status') async state(@Req() r:AuthRequest,@Param('id') company:string){await owner(r,company);const instance='askadia-'+company;const state=await evolutionRequest('/instance/connectionState/'+encodeURIComponent(instance));const status=(state.instance as {state?:string}|undefined)?.state;return result(await r.actor.client.rpc('save_company_channel',{p_company_id:company,p_provider:'evolution',p_remote:instance,p_name:'WhatsApp da empresa',p_status:status==='open'?'connected':'pending',p_metadata:{webhookReady:false,connectionState:status??'unknown',transport:'WHATSAPP-BAILEYS'},p_cipher:sealChannel(company,{instance})}));}
 @Post('companies/:id/channels/disconnect') async disconnect(@Req() r:AuthRequest,@Param('id') company:string,@Body() body:unknown){await owner(r,company);const input=parse(z.object({provider:z.enum(['meta','evolution'])}).strict(),body);result(await r.actor.client.rpc('disconnect_company_channel',{p_company_id:company,p_provider:input.provider}));return {ok:true};}
}
