import {automationReady} from './automation';
import {evolutionMedia,validateMedia} from './media';
import type {PostgrestError} from '@supabase/supabase-js';
import {BadRequestException,Body,Controller,ConflictException,ForbiddenException,Get,Param,Post,Query,Req,ServiceUnavailableException,UseGuards} from '@nestjs/common';
import {z} from 'zod';
import {inboxChannelSchema,serviceSettingsSchema,quickReplySchema,type InboxConnection,type ServiceSettings} from '@askadia/contracts';
import {AuthGuard,type AuthRequest} from '../identity/auth';
import {result} from '../identity/service';
import {evolutionRequest} from '../onboarding/channels';
import {decodeThread,evolutionChats,evolutionMessages,record} from './evolution';
import {ATTENDANCE_MODEL,draftServiceReply,generateServicePrompt} from './assistant';
function parse<T>(s:z.ZodType<T>,v:unknown):T{const p=s.safeParse(v);if(!p.success)throw new BadRequestException('Confira os campos do atendimento.');return p.data;}
async function access(r:AuthRequest,id:string,write=false){parse(z.uuid(),id);const c=result<{actions:string[]}>(await r.actor.client.rpc('company_capabilities',{p_company_id:id}));if(!c.actions.includes(write?'crm.write':'crm.read'))throw new ForbiddenException('Você não tem acesso ao atendimento desta empresa.');return c;}
function settingsDto(v:ServiceSettings){return {channel:v.channel,revision:v.revision,mode:v.mode,prompt:v.prompt,rules:v.rules,fallback:v.fallback,flow:v.flow??null,automatic:v.automatic??false};}
function inboxResult<T>(r:{data:T|null;error:PostgrestError|null}){if(r.error?.message==='Automatic reply in flight')throw new ConflictException('A IA está concluindo uma resposta. Aguarde alguns segundos e tente assumir novamente.');if(r.error?.message==='Confirm company profile first')throw new BadRequestException('Confirme o perfil da empresa antes de gerar o prompt.');if(r.error?.code==='40001')throw new ConflictException('A configuração foi alterada em outra sessão. Recarregue antes de salvar.');if(r.error&&['PGRST205','PGRST202','42P01'].includes(r.error.code))throw new ServiceUnavailableException('Instale a atualização de Caixa de Entrada no Supabase (askadia-caixa-entrada.sql). Seus dados existentes serão preservados.');return result(r);}
async function instance(r:AuthRequest,id:string){await access(r,id);const c=result<{remote_id:string;status:string}|null>(await r.actor.client.from('company_channels').select('remote_id,status').eq('company_id',id).eq('provider','evolution').maybeSingle());if(!c||c.status==='disconnected'||c.remote_id!=='askadia-'+id)throw new BadRequestException('Conecte o WhatsApp desta empresa em Integrações.');return c.remote_id;}
function thread(value:unknown){const id=parse(z.string().max(160),value);try{return decodeThread(id);}catch{throw new BadRequestException('Conversa inválida.');}}
@Controller('onboarding/companies/:id/inbox')
@UseGuards(AuthGuard)
export class InboxController {
 @Get() async bootstrap(@Req() r:AuthRequest,@Param('id') id:string){const cap=await access(r,id);const [settings,replies,channels]=await Promise.all([r.actor.client.from('company_service_settings').select('*').eq('company_id',id),r.actor.client.from('company_quick_replies').select('id,shortcut,title,body').eq('company_id',id).order('shortcut'),r.actor.client.from('company_channels').select('provider,status,remote_id').eq('company_id',id)]);const rows=inboxResult(settings);const quickReplies=inboxResult(replies);const connections:InboxConnection[]=[];const evo=result(channels)?.find((c:{provider:string})=>c.provider==='evolution');let connected=false,message='Conecte o WhatsApp desta empresa em Integrações.';if(evo&&evo.status!=='disconnected'&&evo.remote_id==='askadia-'+id){try{const live=await evolutionRequest('/instance/connectionState/'+encodeURIComponent(evo.remote_id));connected=record(live.instance).state==='open';message=connected?'WhatsApp conectado · histórico consultado na Evolution.':'WhatsApp desconectado. Verifique o pareamento em Integrações.';}catch{message='Não foi possível verificar a Evolution. Tente atualizar.';}}connections.push({channel:'whatsapp',available:Boolean(process.env.EVOLUTION_API_URL&&process.env.EVOLUTION_API_KEY),connected,message});for(const channel of ['instagram','facebook','tiktok'] as const)connections.push({channel,connected:false,available:false,message:channel==='tiktok'?'Aguardando acesso e integração da API de mensagens TikTok.':'Aguardando permissões de mensagens e webhook Meta. Autorizar publicações não conecta o Direct.'});return {connections,settings:(rows??[]).map(settingsDto),quickReplies,canWrite:cap.actions.includes('crm.write'),canConfigure:cap.actions.includes('marketing.write'),model:ATTENDANCE_MODEL,automaticReady:automationReady()};}
 @Get('threads') async threads(@Req() r:AuthRequest,@Param('id') id:string,@Query() q:unknown){const query=parse(z.object({search:z.string().max(150).default(''),page:z.coerce.number().int().min(1).max(10000).default(1)}).strict(),q);const name=await instance(r,id);const all=await evolutionChats(name);const filtered=all.filter(c=>c.name.toLocaleLowerCase('pt-BR').includes(query.search.toLocaleLowerCase('pt-BR'))||c.preview.toLocaleLowerCase('pt-BR').includes(query.search.toLocaleLowerCase('pt-BR')));await access(r,id);return {threads:filtered.slice((query.page-1)*60,query.page*60),total:filtered.length,hasMore:query.page*60<filtered.length};}
 @Get('messages') async messages(@Req() r:AuthRequest,@Param('id') id:string,@Query() q:unknown){const query=parse(z.object({thread:z.string().max(160),page:z.coerce.number().int().min(1).max(10000).default(1)}).strict(),q),jid=thread(query.thread);const name=await instance(r,id);const data=await evolutionMessages(name,jid,query.page);await access(r,id);const handoff=inboxResult<{actor_id:string;revision:number}|null>(await r.actor.client.from('inbox_handoffs').select('actor_id,revision').eq('company_id',id).eq('channel','whatsapp').eq('thread',jid).is('released_at',null).maybeSingle());return {...data,mine:handoff?.actor_id===r.actor.id,assigned:Boolean(handoff)};}
 @Get('media') async media(@Req() r:AuthRequest,@Param('id') id:string,@Query() q:unknown){const query=parse(z.object({thread:z.string().max(160),messageId:z.string().regex(/^[a-zA-Z0-9_-]{1,200}$/)}).strict(),q);const name=await instance(r,id);const media=await evolutionMedia(name,thread(query.thread),query.messageId);await access(r,id);return media;}
 @Post('takeover') async takeover(@Req() r:AuthRequest,@Param('id') id:string,@Body() body:unknown){await access(r,id,true);const input=parse(z.object({thread:z.string().max(160)}).strict(),body);return inboxResult(await r.actor.client.rpc('take_inbox_conversation',{p_company_id:id,p_channel:'whatsapp',p_thread:thread(input.thread)}));}
 @Post('crm-sync') async syncCrm(@Req() r:AuthRequest,@Param('id') id:string,@Body() body:unknown){await access(r,id,true);const input=parse(z.object({page:z.number().int().min(1).max(1000).default(1)}).strict(),body);const name=await instance(r,id);const chats=(await evolutionChats(name)).filter(c=>!c.group);const batch=chats.slice((input.page-1)*200,input.page*200).map(c=>({jid:decodeThread(c.id),name:c.name.slice(0,150),preview:c.preview.slice(0,1000),time:c.time}));const saved=inboxResult<{added:number;linked:number}>(await r.actor.client.rpc('sync_whatsapp_crm',{p_company_id:id,p_contacts:batch}));return {...saved,hasMore:input.page*200<chats.length,total:chats.length};}
 @Post('release') async release(@Req() r:AuthRequest,@Param('id') id:string,@Body() body:unknown){await access(r,id,true);const input=parse(z.object({thread:z.string().max(160)}).strict(),body);inboxResult(await r.actor.client.rpc('release_inbox_conversation',{p_company_id:id,p_thread:thread(input.thread)}));return {ok:true};}
 @Post('settings') async settings(@Req() r:AuthRequest,@Param('id') id:string,@Body() body:unknown){await access(r,id);const parsed=parse(serviceSettingsSchema,body);if(parsed.automatic&&!automationReady())throw new ServiceUnavailableException('O processamento automático não está disponível. Salve sem ativar e confira o servidor.');return settingsDto(inboxResult<ServiceSettings>(await r.actor.client.rpc('save_service_settings',{p_company_id:id,p_settings:parsed})));}
 @Post('quick-replies') async quickReply(@Req() r:AuthRequest,@Param('id') id:string,@Body() body:unknown){await access(r,id);inboxResult(await r.actor.client.rpc('save_quick_reply',{p_company_id:id,p_reply:parse(quickReplySchema,body)}));return {ok:true};}
 @Post('suggest') async suggest(@Req() r:AuthRequest,@Param('id') id:string,@Body() body:unknown){await access(r,id,true);const input=parse(z.object({thread:z.string().max(160),channel:inboxChannelSchema}).strict(),body);if(input.channel!=='whatsapp')throw new BadRequestException('Este canal de mensagens ainda não está conectado.');const name=await instance(r,id);const history=await evolutionMessages(name,thread(input.thread),1);const context=inboxResult<{settings:ServiceSettings;profile:unknown}>(await r.actor.client.rpc('inbox_ai_context',{p_company_id:id,p_channel:input.channel}));const draft=await draftServiceReply(context.settings,context.profile,history.messages);await access(r,id,true);return draft;}
 @Post('generate-prompt') async generatePrompt(@Req() r:AuthRequest,@Param('id') id:string,@Body() body:unknown){const cap=await access(r,id,true);if(!cap.actions.includes('marketing.write'))throw new ForbiddenException('Você não pode configurar o atendimento.');const input=parse(z.object({channel:inboxChannelSchema}).strict(),body);const profile=inboxResult(await r.actor.client.rpc('inbox_prompt_context',{p_company_id:id}));const draft=await generateServicePrompt(profile,input.channel);const current=await access(r,id,true);if(!current.actions.includes('marketing.write'))throw new ForbiddenException();return draft;}
 @Post('preview') async preview(@Req() r:AuthRequest,@Param('id') id:string,@Body() body:unknown){await access(r,id,true);const input=parse(z.object({channel:inboxChannelSchema,text:z.string().trim().min(1).max(2000)}).strict(),body);const context=inboxResult<{settings:ServiceSettings;profile:unknown}>(await r.actor.client.rpc('inbox_ai_context',{p_company_id:id,p_channel:input.channel}));const draft=await draftServiceReply(context.settings,context.profile,[{id:'preview',body:input.text,fromMe:false,time:null,kind:'text',status:'preview'}]);await access(r,id,true);return draft;}
 @Post('media-send') async sendMedia(@Req() r:AuthRequest,@Param('id') id:string,@Body() body:unknown){await access(r,id,true);const input=parse(z.object({thread:z.string().max(160),requestId:z.uuid(),caption:z.string().trim().max(3000),base64:z.string().max(11184812),mimetype:z.string().max(160),fileName:z.string().min(1).max(150)}).strict(),body);const jid=thread(input.thread);if(jid.endsWith('@g.us'))throw new BadRequestException('Grupos são somente leitura.');const file=validateMedia(input);const name=await instance(r,id);const state=await evolutionRequest('/instance/connectionState/'+encodeURIComponent(name));if(record(state.instance).state!=='open')throw new BadRequestException('Reconecte o WhatsApp antes de enviar.');if(!(await evolutionChats(name)).some(c=>c.id===input.thread))throw new BadRequestException('Selecione uma conversa existente.');if(file.kind==='audio'&&input.caption)throw new BadRequestException('Envie o áudio sem legenda.');const reserved=inboxResult<boolean>(await r.actor.client.rpc('reserve_inbox_dispatch',{p_company_id:id,p_thread:jid,p_id:input.requestId,p_body:'[Arquivo '+file.hash+'] '+file.fileName+'\n'+input.caption}));if(!reserved)return {state:'duplicate',message:'Solicitação já registrada. Confira o histórico antes de enviar novamente.'};try{await access(r,id,true);const sent=file.kind==='audio'?await evolutionRequest('/message/sendWhatsAppAudio/'+encodeURIComponent(name),{number:jid,audio:file.base64},{timeout:45000,maxBytes:1048576}):await evolutionRequest('/message/sendMedia/'+encodeURIComponent(name),{number:jid,mediatype:file.kind,mimetype:file.mimetype,fileName:file.fileName,caption:input.caption,media:file.base64},{timeout:45000,maxBytes:1048576});const providerId=record(sent.key).id;if(typeof providerId!=='string')throw new Error('Unconfirmed');inboxResult(await r.actor.client.rpc('finish_inbox_dispatch',{p_company_id:id,p_id:input.requestId,p_state:'sent',p_provider_id:providerId}));return {state:'sent',message:'Arquivo aceito pela Evolution.'};}catch{await r.actor.client.rpc('finish_inbox_dispatch',{p_company_id:id,p_id:input.requestId,p_state:'uncertain',p_provider_id:null});throw new ServiceUnavailableException('Não foi possível confirmar o envio do arquivo. Confira o WhatsApp antes de tentar novamente.');}}
 @Post('send') async send(@Req() r:AuthRequest,@Param('id') id:string,@Body() body:unknown){await access(r,id,true);const input=parse(z.object({thread:z.string().max(160),requestId:z.uuid(),text:z.string().trim().min(1).max(6000)}).strict(),body),jid=thread(input.thread);if(jid.endsWith('@g.us'))throw new BadRequestException('Grupos estão disponíveis somente para leitura nesta etapa.');const name=await instance(r,id);const live=await evolutionRequest('/instance/connectionState/'+encodeURIComponent(name));if(record(live.instance).state!=='open')throw new BadRequestException('WhatsApp desconectado. Reconecte antes de enviar.');const exists=(await evolutionChats(name)).some(c=>c.id===input.thread);if(!exists)throw new BadRequestException('Selecione uma conversa existente desta empresa.');const reserved=inboxResult<boolean>(await r.actor.client.rpc('reserve_inbox_dispatch',{p_company_id:id,p_thread:jid,p_id:input.requestId,p_body:input.text}));if(!reserved)return {state:'duplicate',message:'Esta solicitação já foi registrada. Atualize o histórico antes de tentar novamente.'};
  try{await access(r,id,true);const sent=await evolutionRequest('/message/sendText/'+encodeURIComponent(name),{number:jid,text:input.text});const providerId=record(sent.key).id;if(typeof providerId!=='string')throw new Error('Missing confirmation');inboxResult(await r.actor.client.rpc('finish_inbox_dispatch',{p_company_id:id,p_id:input.requestId,p_state:'sent',p_provider_id:providerId}));return {state:'sent',message:'Mensagem aceita pela Evolution.'};}catch{await r.actor.client.rpc('finish_inbox_dispatch',{p_company_id:id,p_id:input.requestId,p_state:'uncertain',p_provider_id:null});throw new ServiceUnavailableException('Não foi possível confirmar o envio. Confira o WhatsApp antes de tentar novamente; a solicitação não será reenviada automaticamente.');}
 }
}
