import {createHash} from 'node:crypto';
import {Controller,Get,Post,Body,Param,Query,Req,UseGuards,BadRequestException,ServiceUnavailableException} from '@nestjs/common';
import {z} from 'zod';
import {AuthGuard,type AuthRequest} from '../identity/auth';
import {result} from '../identity/service';
import {metaContext,metaThreads,metaMessages,decodeMetaThread,metaGraph} from './meta';
function parse<T>(schema:z.ZodType<T>,value:unknown){const p=schema.safeParse(value);if(!p.success)throw new BadRequestException('Confira os dados da conversa.');return p.data;}
const key=(thread:string)=>'meta:'+createHash('sha256').update(thread).digest('hex');
@Controller('onboarding/companies/:id/inbox/meta')
@UseGuards(AuthGuard)
export class MetaInboxController {
 @Get('threads') async threads(@Req() r:AuthRequest,@Param('id') company:string,@Query() q:unknown){const input=parse(z.object({channel:z.enum(['instagram','facebook']),page:z.coerce.number().int().min(1).max(20).default(1)}).strict(),q);const context=await metaContext(r,company);const data=await metaThreads(context,company,input.channel,input.page);await metaContext(r,company);return data;}
 @Get('messages') async messages(@Req() r:AuthRequest,@Param('id') company:string,@Query() q:unknown){const input=parse(z.object({thread:z.string().max(2000),page:z.coerce.number().int().min(1).max(20).default(1)}).strict(),q);const context=await metaContext(r,company),ref=decodeMetaThread(input.thread,company,context.page);const data=await metaMessages(context,ref,input.page);const handoff=result<{actor_id:string}|null>(await r.actor.client.from('inbox_handoffs').select('actor_id').eq('company_id',company).eq('channel',ref.channel).eq('thread',key(input.thread)).is('released_at',null).maybeSingle());await metaContext(r,company);return {...data,mine:handoff?.actor_id===r.actor.id,assigned:Boolean(handoff)};}
 @Post('takeover') async takeover(@Req() r:AuthRequest,@Param('id') company:string,@Body() body:unknown){const input=parse(z.object({thread:z.string().max(2000)}).strict(),body);const context=await metaContext(r,company,'crm.write'),ref=decodeMetaThread(input.thread,company,context.page);return result(await r.actor.client.rpc('take_inbox_conversation',{p_company_id:company,p_channel:ref.channel,p_thread:key(input.thread)}));}
 @Post('send') async send(@Req() r:AuthRequest,@Param('id') company:string,@Body() body:unknown){const input=parse(z.object({thread:z.string().max(2000),requestId:z.uuid(),text:z.string().trim().min(1).max(1000)}).strict(),body);const context=await metaContext(r,company,'crm.write'),ref=decodeMetaThread(input.thread,company,context.page);const history=await metaMessages(context,ref);const inbound=history.messages.filter(m=>!m.fromMe&&m.time).at(-1);if(!inbound||Date.now()-Date.parse(inbound.time!)>24*3600000)throw new BadRequestException('A janela de resposta de 24 horas deste canal está encerrada ou não pôde ser verificada. Aguarde uma nova mensagem do contato.');
  const reserved=result(await r.actor.client.rpc('reserve_meta_dispatch',{p_company_id:company,p_channel:ref.channel,p_thread:key(input.thread),p_id:input.requestId,p_body:input.text}));if(!reserved)return {state:'duplicate',message:'Solicitação já registrada. Confira o histórico antes de reenviar.'};
  try{const fresh=await metaContext(r,company,'crm.write');if(fresh.page!==context.page||fresh.instagram!==context.instagram)throw new Error('Channel changed');const sent=await metaGraph<{message_id?:string}>(fresh.page+'/messages',fresh.token,{}, {recipient:{id:ref.peer},message:{text:input.text},...(ref.channel==='facebook'?{messaging_type:'RESPONSE'}:{})});if(!sent.message_id)throw new Error();result(await r.actor.client.rpc('finish_inbox_dispatch',{p_company_id:company,p_id:input.requestId,p_state:'sent',p_provider_id:sent.message_id}));return {state:'sent',message:'Mensagem aceita pela Meta.'};}catch{await r.actor.client.rpc('finish_inbox_dispatch',{p_company_id:company,p_id:input.requestId,p_state:'uncertain',p_provider_id:null});throw new ServiceUnavailableException('Não foi possível confirmar o envio pela Meta. Confira o aplicativo de origem antes de tentar novamente.');}
 }
}
