'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Button} from '@askadia/ui';
import {MessageCircle,Megaphone,Plus} from 'lucide-react';
import {messageCampaignSchema,type MessageCampaign,type MessageCampaignInput,type OnboardingSnapshot,type GeneratedStrategy} from '@askadia/contracts';
import {journeyApi} from '../lib/journey-api';
import styles from './campaigns.module.css';
type CampaignData={campaigns:MessageCampaign[];studentCount:number;timezone:string;companyName:string;canWrite:boolean;deliveryReady:boolean;deliveries:{id:string;campaign_id:string;state:string;created_at:string}[]};
type Preview={revision:number;total:number;students:{student_id:string;name:string;phone:string;message:string}[]};
const csv='id_aluno;nome;telefone;nascimento;ultima_presenca;situacao;autoriza_mensagens;grupo\n';
export function CampaignsPanel({companyId,profile,crm}:{companyId:string;profile:OnboardingSnapshot['confirmedProfile']|undefined;crm:boolean}){
 const [tab,setTab]=useState<'messages'|'ads'>('messages'),[data,setData]=useState<CampaignData|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState<MessageCampaignInput|null>(null),[preview,setPreview]=useState<{campaign:MessageCampaign;result:Preview}|null>(null),[strategy,setStrategy]=useState<GeneratedStrategy|null>(null);const lock=useRef(false);const base='companies/'+companyId+'/campaigns';
 const load=useCallback(async(signal?:AbortSignal)=>{const result=await journeyApi<CampaignData>(base,undefined,signal);if(!signal?.aborted)setData(result);},[base]);
 useEffect(()=>{const c=new AbortController();if(crm)void load(c.signal).catch(e=>{if(!c.signal.aborted)setError(e.message);});journeyApi<{output:GeneratedStrategy|null}[]>('companies/'+companyId+'/strategy',undefined,c.signal).then(rows=>{if(!c.signal.aborted)setStrategy(rows[0]?.output??null);}).catch(()=>{});return()=>c.abort();},[load,companyId,crm]);
 async function act(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await action();}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir.');}finally{lock.current=false;setBusy(false);}}
 function create(){setPreview(null);setForm({id:crypto.randomUUID(),revision:0,name:'',trigger:'birthday',absenceDays:7,sendTime:'09:00',message:'Olá, {{nome}}! A equipe da {{academia}} deseja um feliz aniversário! 🎉',tag:'',activeOnly:true,startDate:new Date().toLocaleDateString('en-CA',{timeZone:data?.timezone??'America/Sao_Paulo'}),endDate:null,maxDataAgeDays:2,dailyLimit:30});}
 async function save(e:FormEvent){e.preventDefault();if(!form)return;await act(async()=>{await journeyApi(base+'/save',form);setForm(null);setPreview(null);await load();setNotice('Campanha salva como rascunho. Revise os destinatários antes de ativar.');});}
 function template(){const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='askadia-alunos.csv';a.click();URL.revokeObjectURL(url);}
 async function importFile(file:File){await act(async()=>{if(file.size>240000)throw new Error('Use arquivos de até 240 KB e 500 alunos.');const r=await journeyApi<{imported:number}>(base+'/students/import',{csv:await file.text()});await load();setNotice(r.imported+' alunos atualizados. Nenhuma mensagem foi enviada.');});}
 return <div><div className={styles.tabs} role="group" aria-label="Tipo de campanha"><button aria-pressed={tab==='messages'} onClick={()=>setTab('messages')}><MessageCircle size={22}/><span><strong>Campanha de mensagens</strong><small>Aniversários, frequência e relacionamento</small></span></button><button aria-pressed={tab==='ads'} onClick={()=>setTab('ads')}><Megaphone size={22}/><span><strong>Campanha de Tráfego Pago</strong><small>Anúncios, orçamento e aquisição</small></span></button></div>
 {error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {tab==='ads'?<section className={styles.card}><h2>Campanha de Tráfego Pago</h2><p>Prepare a proposta a partir da estratégia, escolha a conta de anúncios e revise o orçamento antes de veicular.</p><dl><dt>Público</dt><dd>{profile?.facts.audience?.value??'Confirme o perfil da empresa.'}</dd><dt>Objetivo</dt><dd>{profile?.facts.objective?.value??'Não informado'}</dd><dt>Orçamento informado</dt><dd>{profile?.facts.budget?.value??'Não informado'}</dd></dl>{strategy?.ads.map((a,i)=><article key={i} className={styles.proposal}><strong>{a.channel} · {a.objective}</strong><p>{a.audience}</p><p>{a.copy}</p><p>Proposta de verba: {a.budgetProposal}</p><small>Proposta da estratégia. Ainda não é um anúncio ativo.</small></article>)}<div className={styles.actions}><Link className="button button-primary" href={'/empresa/'+companyId+'/estrategia'}>Revisar propostas da estratégia</Link><Link className="button button-outline" href={'/empresa/'+companyId+'/integracoes'}>Conectar conta Meta</Link></div><p>A execução e os resultados dependem da conta autorizada e da integração com a API de anúncios. Conectar a conta não aprova verba.</p></section>:!crm?<section className={styles.card}>Seu perfil precisa de acesso ao CRM para consultar alunos e campanhas de mensagens.</section>:<>
 <section className={styles.card}><div className={styles.heading}><div><h2>Relacionamento no momento certo.</h2><p>Defina quem recebe, qual mensagem e em que horário. Envio pelo WhatsApp desta empresa.</p></div>{data?.canWrite&&<Button disabled={busy} onClick={create}><Plus size={16}/> Nova campanha</Button>}</div><p>{data?.studentCount??0} alunos na base · Fuso: {data?.timezone??'consultando'}</p><details><summary>Dados dos alunos e integrações</summary><p>Receba dados pela API de integração ou importe uma planilha atualizada. Wellhub (Gympass) e TotalPass precisam de credenciais e homologação próprias; não estão conectados automaticamente.</p><Link href={'/empresa/'+companyId+'/integracoes'}>Configurar sistema de gestão e parceiros</Link><p>CSV com separador “;”: telefone internacional (+55…), nascimento AAAA-MM-DD, última presença com data/hora/fuso, situação ativo/inativo e autorização sim/nao. O mesmo ID atualiza o aluno; registros ausentes não são apagados. Telefones duplicados precisam ser corrigidos.</p>{data?.canWrite&&<div className={styles.actions}><Button variant="outline" onClick={template}>Baixar modelo CSV</Button><label className={styles.upload}>Importar alunos<input type="file" accept=".csv,text/csv" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);e.target.value='';}}/></label></div>}</details></section>
 {form&&<form className={styles.card} onSubmit={save}><h2>{form.revision?'Editar campanha':'Nova campanha de mensagens'}</h2><div className={styles.fields}><label>Nome da campanha<input required maxLength={120} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Quando enviar<select value={form.trigger} onChange={e=>setForm({...form,trigger:e.target.value as 'birthday'|'absence'})}><option value="birthday">No aniversário do aluno</option><option value="absence">Após dias sem frequentar</option></select></label>{form.trigger==='absence'&&<label>Dias sem frequentar<input type="number" min={1} max={365} value={form.absenceDays} onChange={e=>setForm({...form,absenceDays:Number(e.target.value)})}/></label>}<label>Horário · {data?.timezone}<input type="time" required value={form.sendTime} onChange={e=>setForm({...form,sendTime:e.target.value})}/></label><label>Grupo (opcional)<input maxLength={80} value={form.tag} onChange={e=>setForm({...form,tag:e.target.value})} placeholder="Todos os grupos"/></label><label>Máximo de mensagens por dia<input type="number" min={1} max={200} value={form.dailyLimit} onChange={e=>setForm({...form,dailyLimit:Number(e.target.value)})}/></label><label>Início<input type="date" required value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>Fim (opcional)<input type="date" value={form.endDate??''} min={form.startDate} onChange={e=>setForm({...form,endDate:e.target.value||null})}/></label><label>Exigir dados atualizados nos últimos (dias)<input type="number" min={1} max={30} value={form.maxDataAgeDays} onChange={e=>setForm({...form,maxDataAgeDays:Number(e.target.value)})}/></label><label className={styles.check}><input type="checkbox" checked={form.activeOnly} onChange={e=>setForm({...form,activeOnly:e.target.checked})}/> Somente alunos ativos</label></div><label className={styles.message}>Mensagem<textarea required maxLength={2000} rows={5} value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/><small>Variáveis: {'{{nome}}'}, {'{{academia}}'}, {'{{dias_ausente}}'}</small></label><p>Somente alunos com autorização registrada recebem mensagens. Aniversário: uma vez ao ano. Ausência: uma vez por período de afastamento, até registrar uma nova presença. Dados desconhecidos ou desatualizados ficam fora do envio.</p><div className={styles.actions}><Button type="submit" disabled={busy}>Salvar rascunho</Button><Button type="button" variant="outline" onClick={()=>setForm(null)}>Cancelar</Button></div></form>}
 {data?.campaigns.map(c=><section key={c.id} className={styles.card}><div className={styles.heading}><h3>{c.name}</h3><span className="tag">{c.status==='active'?'Ativa':c.status==='paused'?'Pausada':'Rascunho'} · v{c.revision}</span></div><p>{c.trigger==='birthday'?'No aniversário':c.absenceDays+' dias sem frequentar'} · {c.sendTime} · {c.timezone}</p><p className={styles.text}>{c.message}</p><small>{data.deliveries.filter(d=>d.campaign_id===c.id&&d.state==='sent').length} envios aceitos entre os últimos 100 registros</small>{data.canWrite&&<div className={styles.actions}><Button variant="outline" disabled={busy} onClick={()=>{const input=Object.fromEntries(Object.entries(c).filter(([k])=>!['status','timezone','updatedAt'].includes(k)));setForm(messageCampaignSchema.parse(input));setPreview(null);}}>Editar</Button><Button variant="outline" disabled={busy} onClick={()=>void act(async()=>{const result=await journeyApi<Preview>(base+'/preview',{id:c.id});setPreview({campaign:c,result});})}>Revisar destinatários</Button>{c.status==='active'&&<Button variant="outline" disabled={busy} onClick={()=>void act(async()=>{await journeyApi(base+'/activation',{id:c.id,revision:c.revision,active:false,confirmed:true});await load();setNotice('Campanha pausada. Um envio já em andamento pode ser concluído.');})}>Pausar</Button>}</div>}</section>)}
 {data&&!data.campaigns.length&&!form&&<section className={styles.card}><h3>Sua primeira campanha.</h3><p>Comece com aniversários ou alunos que não visitam há alguns dias. Salvar uma campanha não inicia envios.</p></section>}
 {preview&&<section className={styles.card}><h2>Revisar: {preview.campaign.name}</h2><p>{preview.result.total} alunos elegíveis agora. A lista é recalculada no horário de envio; exibindo até 30 alunos.</p>{preview.result.students.map(s=><article key={s.student_id} className={styles.proposal}><strong>{s.name} · {s.phone}</strong><p className={styles.text}>{s.message}</p></article>)}{!preview.result.total&&<p>Nenhum aluno atende a todas as condições hoje. Confira a data, a presença, a autorização e a atualização dos dados.</p>}<p>Ao ativar, a Askadia enviará a mensagem no horário e nas condições configuradas. O envio ocorre durante até uma hora após o horário, com limite diário e sem repetir o mesmo evento.</p>{!data?.deliveryReady&&<p>Ativação indisponível: serviço de envio ainda não está configurado ou disponível.</p>}<Button disabled={busy||!data?.deliveryReady||preview.campaign.status==='active'} onClick={()=>void act(async()=>{await journeyApi(base+'/activation',{id:preview.campaign.id,revision:preview.result.revision,active:true,confirmed:true});setPreview(null);await load();setNotice('Campanha ativada para as próximas execuções no horário configurado.');})}>Confirmar e ativar campanha</Button></section>}
 </>}</div>;
}
