'use client';
import {SiteBuilder} from './site-builder';
import {StrategyWorkspace} from './strategy-workspace';
import {CampaignsPanel} from './campaigns-panel';
import {ManagementIntegration} from './management-integration';
import {CompanyChannels} from './company-channels';

import Link from 'next/link';
import { useEffect,useRef,useState } from 'react';
import { ArrowRight,Building2,Menu,X } from 'lucide-react';
import { type OnboardingSnapshot } from '@askadia/contracts';
import { EditorialCalendar } from './editorial-calendar';
import {InboxPanel} from './inbox-panel';
import {AttendanceSettings} from './attendance-settings';
import { CrmPanel } from './crm-panel';
import { OnboardingChat } from './onboarding-chat';
import { DraftImportPanel } from './draft-import';
import { CompanyPlan } from './company-plan';
import { journeyApi } from '../lib/journey-api';
import styles from './journey.module.css';
const titles:Record<string,string>={inicio:'Seu marketing, passo a passo.',agentes:'Agentes da sua empresa.',estrategia:'Uma direção para crescer.',conteudo:'Conteúdo da sua empresa.',campanhas:'Campanhas e aquisição.',crm:'Relacionamentos que viram oportunidades.',atendimento:'Conversas da sua empresa.','configuracao-atendimento':'Configuração de Atendimento.',integracoes:'Conexões da sua empresa.',site:'Meu site.',assinatura:'Assinatura da empresa.'};
export function CompanyJourney({company,area,actions,email,calendarDay}:{calendarDay?:string;company:{id:string;name:string};area:string;actions:string[];email:string}){
 const [data,setData]=useState<OnboardingSnapshot|null>(null),[error,setError]=useState(''),[mobile,setMobile]=useState(false);
 const marketing=actions.includes('marketing.read'),write=actions.includes('marketing.write'),billing=actions.includes('billing.manage');
 const [latestStrategy,setLatestStrategy]=useState<{status:string;generation:number}|null>(null);
 useEffect(()=>{if(area!=='inicio'||!marketing)return;const c=new AbortController();journeyApi<{status:string;generation:number}[]>('companies/'+company.id+'/strategy',undefined,c.signal).then(r=>{if(!c.signal.aborted)setLatestStrategy(r[0]??null);}).catch(()=>{});return()=>c.abort();},[company.id,area,marketing]);
 const menuButton=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!mobile)return;document.getElementById('company-navigation')?.querySelector<HTMLAnchorElement>('a')?.focus();const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMobile(false);requestAnimationFrame(()=>menuButton.current?.focus());}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);},[mobile]);
 const base='/empresa/'+company.id;
 useEffect(()=>{if(!marketing)return;const c=new AbortController();journeyApi<OnboardingSnapshot>('companies/'+company.id,undefined,c.signal).then(r=>{if(!c.signal.aborted)setData(r);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[company.id,marketing]);
 const complete=data?.step==='complete';const interviewing=['onboarding','perfil'].includes(area);
 const groups=[{title:'Início',items:[['inicio','Visão geral']]},{title:'Planejamento',items:[['estrategia','Estratégia']]},{title:'Conteúdo',items:[['conteudo','Calendário, estúdio e aprovações']]},{title:'Aquisição',items:[['campanhas','Campanhas'],...(actions.includes('crm.read')?[['crm','CRM'],['atendimento','Caixa de entrada'],...(write?[['configuracao-atendimento','Configuração de Atendimento']]:[])]:[])]},{title:'Resultados',items:[['resultados','Desempenho e retorno']]},{title:'Empresa',items:[['perfil','Perfil e marca'],['site','Meu site'],['integracoes','Integrações'],...(billing||actions.includes('members.manage')?[['equipe','Equipe e acessos']]:[]),...(billing?[['assinatura','Assinatura']]:[])]}];
 const nav=marketing?(complete?groups:[{title:'Primeiros passos',items:[['inicio','Visão geral'],['onboarding','Conhecer minha empresa'],['perfil','Perfil e materiais'],...(actions.includes('crm.read')?[['atendimento','Caixa de entrada'],...(write?[['configuracao-atendimento','Configuração de Atendimento']]:[])]:[]),...(billing?[['assinatura','Assinatura']]:[])]}]):[{title:'Atendimento',items:[['atendimento','Caixa de entrada'],['crm','CRM']]}];
 const href=(key:string)=>key==='resultados'?'/dashboard?companyId='+company.id:key==='equipe'?'/workspace?companyId='+company.id+'&view=team':base+(key==='inicio'?'':'/'+key);
 return <div className={styles.shell}>
  {mobile&&<button className={styles.scrim} aria-label="Fechar menu" onClick={()=>{setMobile(false);requestAnimationFrame(()=>menuButton.current?.focus());}}/>}
  <aside id="company-navigation" className={styles.sidebar} data-open={mobile}><div className={styles.brandRow}><Link href="/" className="brand"><span className="brand-mark">a</span>askadia.</Link><button className={styles.mobileButton} aria-label="Fechar menu" onClick={()=>setMobile(false)}><X size={20}/></button></div><Link className={styles.context} href="/entrada"><Building2 size={18}/><span><small>EMPRESA ATUAL</small><strong>{data?.state.facts.name?.value??company.name}</strong><small>Trocar empresa ou contexto</small></span></Link><nav aria-label="Navegação da empresa">{nav.map(g=><div className={styles.navGroup} key={g.title}><small>{g.title}</small>{g.items.map(([key,label])=><Link key={key} href={href(key!)} aria-current={area===key?'page':undefined}>{label}</Link>)}</div>)}</nav><footer><small>{email}</small><Link href="/workspace">Gerenciar meus negócios</Link></footer></aside>
  <div className={styles.main} inert={mobile}><header className={styles.topbar}><button ref={menuButton} className={styles.mobileButton} aria-expanded={mobile} aria-controls="company-navigation" aria-label="Abrir menu" onClick={()=>setMobile(true)}><Menu size={22}/></button><span>{company.name}</span><small>{billing?'Proprietário':marketing?'Marketing':'Atendente'} · acesso verificado</small></header><main className={area==='atendimento'?styles.inboxContent:styles.content}>
   {interviewing?<OnboardingChat companyId={company.id} readOnly={!write} summaryOnly={area==='perfil'}/>:<>{area!=='atendimento'&&<div className={styles.pageHeading}><p className="page-eyebrow">{marketing?'SUA AGÊNCIA DE MARKETING COM IA':'SUA OPERAÇÃO COMERCIAL'}</p><h1>{titles[area]??'Sua empresa.'}</h1></div>}{area!=='atendimento'&&error&&<div className="error-banner" role="alert">{error}<p>Atualize a página para tentar novamente. Seus dados existentes continuam preservados.</p></div>}
   {area==='inicio'&&data&&<><section className={styles.nextAction}><div className={styles.orb}>a</div><div><small>O QUE FAZER AGORA</small><h2>{complete?(latestStrategy?.status==='review'?'Revisar sua estratégia.':latestStrategy?.status==='approved'?'Organizar materiais e conteúdos.':'Preparar sua estratégia inicial.'):'Vamos conhecer sua empresa.'}</h2><p>{complete?'O perfil confirmado é a base da estratégia, dos conteúdos e das campanhas.':'Retome a conversa de onde parou. O essencial vem primeiro; materiais e conexões podem ficar para depois.'}</p><Link className="button button-primary" href={base+(complete?(latestStrategy?.status==='approved'?'/conteudo':'/estrategia'):'/onboarding')}>{complete?(latestStrategy?.status==='approved'?'Abrir conteúdo':latestStrategy?.status==='review'?'Revisar proposta':'Abrir estratégia'):'Continuar conversa'}<ArrowRight size={16}/></Link></div></section><div className={styles.overview}><section><h3>Perfil do negócio</h3><p>{complete?'Confirmado · versão '+data.state.profile_version:'Em construção · progresso salvo'}</p><Link href={base+'/perfil'}>Revisar informações</Link></section><section><h3>Materiais</h3><p>{data.attachments.length} arquivo(s) registrado(s)</p><Link href={base+'/onboarding'}>Enviar logo, fotos ou documentos</Link></section><section><h3>Conexões</h3><p>Informar um perfil não conecta uma conta.</p><Link href={base+'/integracoes'}>Ver dependências</Link></section></div></>}
   {area==='agentes'&&<><section className={styles.nextAction}><div className={styles.orb}>a</div><div><h2>Conhecer minha empresa</h2><p>Converse, consulte o histórico e atualize as informações que orientam os agentes.</p><Link className="button button-primary" href={base+'/onboarding'}>{complete?'Consultar e atualizar':'Continuar onboarding'}<ArrowRight size={16}/></Link></div></section><section className={styles.moduleCard}><h2>Estratégia e tráfego pago · OpenAI</h2><p>A estratégia começa pelo perfil confirmado. Publicação e orçamento continuam sujeitos às aprovações autorizadas.</p><Link href={base+'/estrategia'}>Preparar o planejamento</Link><h2>Design · Nano Banana Pro</h2><p>Materiais visuais usam o Gemini. A geração depende do fluxo de criação, do limite da empresa e da disponibilidade do provedor.</p><Link href={base+'/conteudo'}>Abrir conteúdo</Link></section></>}
   {area==='estrategia'&&<StrategyWorkspace companyId={company.id} data={data} write={write} approve={actions.includes('strategy.approve')}/>}
   {area==='conteudo'&&<><EditorialCalendar day={calendarDay} key={company.id} companyId={company.id} write={write} approve={actions.includes('content.approve')}/><details className={styles.moduleCard}><summary>Acervo e importação de rascunhos anteriores</summary><DraftImportPanel companyId={company.id} companyName={company.name}/></details></>}
   {area==='assinatura'&&<CompanyPlan companyId={company.id}/>}
   {area==='crm'&&<CrmPanel companyId={company.id} inbox={false} write={actions.includes('crm.write')}/>}
   {area==='atendimento'&&<InboxPanel key={company.id} companyId={company.id} companyName={company.name}/>}
   {area==='configuracao-atendimento'&&<AttendanceSettings key={company.id} companyId={company.id} companyName={company.name}/>}
   {area==='campanhas'&&<CampaignsPanel key={company.id} companyId={company.id} profile={data?.confirmedProfile} crm={actions.includes('crm.read')}/>}

   {area==='site'&&<SiteBuilder key={company.id} companyId={company.id} profile={data}/>}
   {area==='integracoes'&&<><CompanyChannels key={company.id} companyId={company.id}/><ManagementIntegration key={'management-'+company.id} companyId={company.id} owner={billing}/></>}
   {area==='integracoes'&&<section className={styles.moduleCard}><h2>Dependências por ação</h2><table><thead><tr><th>Serviço</th><th>Situação</th><th>Uso</th></tr></thead><tbody><tr><td>OpenAI</td><td>{data?.provider.mode==='configured'?'Credencial no servidor · uso sujeito a limite':'Configuração pendente'}</td><td>Interpretação do onboarding; estratégia e campanhas em evolução</td></tr><tr><td>Nano Banana Pro</td><td>Homologação da geração pendente</td><td>Design de publicações</td></tr><tr><td>Google Places</td><td>Consulte a disponibilidade na conversa</td><td>Localização e concorrentes, com alternativa manual</td></tr><tr><td>Meta Ads / Google Ads</td><td>Consulte os cartões de conexão acima</td><td>Execução e resultados de anúncios aprovados</td></tr><tr><td>Sistema de gestão</td><td>{data?.state.facts.management?.value??'Não informado'}</td><td>Matrículas e resultados financeiros</td></tr></tbody></table><p>As pendências afetam apenas as ações que dependem de cada serviço.</p></section>}
   </>}
  </main></div>
 </div>;
}
