'use client';
import {CompanyChannels} from './company-channels';

import Link from 'next/link';
import { useEffect,useRef,useState } from 'react';
import { ArrowRight,Building2,Menu,X,Check } from 'lucide-react';
import { Button } from '@askadia/ui';
import { type OnboardingSnapshot,type GeneratedStrategy,labels } from '@askadia/contracts';
import { EditorialCalendar } from './editorial-calendar';
import {InboxPanel} from './inbox-panel';
import {AttendanceSettings} from './attendance-settings';
import { CrmPanel } from './crm-panel';
import { OnboardingChat } from './onboarding-chat';
import { DraftImportPanel } from './draft-import';
import { CompanyPlan } from './company-plan';
import { journeyApi } from '../lib/journey-api';
import styles from './journey.module.css';
const titles:Record<string,string>={inicio:'Seu marketing, passo a passo.',agentes:'Agentes da sua empresa.',estrategia:'Uma direção para crescer.',conteudo:'Conteúdo da sua empresa.',campanhas:'Campanhas e aquisição.',crm:'Relacionamentos que viram oportunidades.',atendimento:'Conversas da sua empresa.','configuracao-atendimento':'Configuração de Atendimento.',integracoes:'Conexões da sua empresa.',site:'Meu site.',assinatura:'Assinatura da empresa.'};
export function CompanyJourney({company,area,actions,email,calendarDay}:{calendarDay?:string;company:{id:string;name:string};area:string;actions:string[];email:string}){
 const [data,setData]=useState<OnboardingSnapshot|null>(null),[error,setError]=useState(''),[mobile,setMobile]=useState(false);
 const marketing=actions.includes('marketing.read'),write=actions.includes('marketing.write'),billing=actions.includes('billing.manage');
 const [latestStrategy,setLatestStrategy]=useState<{status:string;generation:number}|null>(null);
 useEffect(()=>{if(area!=='inicio'||!marketing)return;const c=new AbortController();journeyApi<{status:string;generation:number}[]>('companies/'+company.id+'/strategy',undefined,c.signal).then(r=>{if(!c.signal.aborted)setLatestStrategy(r[0]??null);}).catch(()=>{});return()=>c.abort();},[company.id,area,marketing]);
 const menuButton=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!mobile)return;document.getElementById('company-navigation')?.querySelector<HTMLAnchorElement>('a')?.focus();const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMobile(false);requestAnimationFrame(()=>menuButton.current?.focus());}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);},[mobile]);
 const base='/empresa/'+company.id;
 useEffect(()=>{if(!marketing)return;const c=new AbortController();journeyApi<OnboardingSnapshot>('companies/'+company.id,undefined,c.signal).then(r=>{if(!c.signal.aborted)setData(r);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[company.id,marketing]);
 const complete=data?.step==='complete';const interviewing=['onboarding','perfil'].includes(area);
 const groups=[{title:'Início',items:[['inicio','Visão geral']]},{title:'Planejamento',items:[['agentes','Agentes'],['estrategia','Estratégia']]},{title:'Conteúdo',items:[['conteudo','Calendário, estúdio e aprovações']]},{title:'Aquisição',items:[['campanhas','Campanhas'],...(actions.includes('crm.read')?[['crm','CRM'],['atendimento','Caixa de entrada'],...(write?[['configuracao-atendimento','Configuração de Atendimento']]:[])]:[])]},{title:'Resultados',items:[['resultados','Desempenho e retorno']]},{title:'Empresa',items:[['perfil','Perfil e marca'],['site','Meu site'],['integracoes','Integrações'],...(billing||actions.includes('members.manage')?[['equipe','Equipe e acessos']]:[]),...(billing?[['assinatura','Assinatura']]:[])]}];
 const nav=marketing?(complete?groups:[{title:'Primeiros passos',items:[['inicio','Visão geral'],['onboarding','Conhecer minha empresa'],['perfil','Perfil e materiais'],...(actions.includes('crm.read')?[['atendimento','Caixa de entrada'],...(write?[['configuracao-atendimento','Configuração de Atendimento']]:[])]:[]),...(billing?[['assinatura','Assinatura']]:[])]}]):[{title:'Atendimento',items:[['atendimento','Caixa de entrada'],['crm','CRM']]}];
 const href=(key:string)=>key==='resultados'?'/dashboard?companyId='+company.id:key==='equipe'?'/workspace?companyId='+company.id+'&view=team':base+(key==='inicio'?'':'/'+key);
 return <div className={styles.shell}>
  {mobile&&<button className={styles.scrim} aria-label="Fechar menu" onClick={()=>{setMobile(false);requestAnimationFrame(()=>menuButton.current?.focus());}}/>}
  <aside id="company-navigation" className={styles.sidebar} data-open={mobile}><div className={styles.brandRow}><Link href="/" className="brand"><span className="brand-mark">a</span>askadia.</Link><button className={styles.mobileButton} aria-label="Fechar menu" onClick={()=>setMobile(false)}><X size={20}/></button></div><Link className={styles.context} href="/entrada"><Building2 size={18}/><span><small>EMPRESA ATUAL</small><strong>{data?.state.facts.name?.value??company.name}</strong><small>Trocar empresa ou contexto</small></span></Link><nav aria-label="Navegação da empresa">{nav.map(g=><div className={styles.navGroup} key={g.title}><small>{g.title}</small>{g.items.map(([key,label])=><Link key={key} href={href(key!)} aria-current={area===key?'page':undefined}>{label}</Link>)}</div>)}</nav><footer><small>{email}</small><Link href="/workspace">Gerenciar meus negócios</Link></footer></aside>
  <div className={styles.main} inert={mobile}><header className={styles.topbar}><button ref={menuButton} className={styles.mobileButton} aria-expanded={mobile} aria-controls="company-navigation" aria-label="Abrir menu" onClick={()=>setMobile(true)}><Menu size={22}/></button><span>{company.name}</span><small>{billing?'Proprietário':marketing?'Marketing':'Atendente'} · acesso verificado</small></header><main className={area==='atendimento'?styles.inboxContent:styles.content}>
   {interviewing?<OnboardingChat companyId={company.id} readOnly={!write} summaryOnly={area==='perfil'}/>:<>{area!=='atendimento'&&<div className={styles.pageHeading}><p className="page-eyebrow">{marketing?'SUA AGÊNCIA DE MARKETING COM IA':'SUA OPERAÇÃO COMERCIAL'}</p><h1>{titles[area]??'Sua empresa.'}</h1></div>}{area!=='atendimento'&&error&&<div className="error-banner" role="alert">{error}<p>Atualize a página para tentar novamente. Seus dados existentes continuam preservados.</p></div>}
   {area==='inicio'&&data&&<><section className={styles.nextAction}><div className={styles.orb}>a</div><div><small>O QUE FAZER AGORA</small><h2>{complete?(latestStrategy?.status==='review'?'Revisar sua estratégia.':latestStrategy?.status==='approved'?'Organizar materiais e conteúdos.':'Preparar sua estratégia inicial.'):'Vamos conhecer sua empresa.'}</h2><p>{complete?'O perfil confirmado é a base da estratégia, dos conteúdos e das campanhas.':'Retome a conversa de onde parou. O essencial vem primeiro; materiais e conexões podem ficar para depois.'}</p><Link className="button button-primary" href={base+(complete?(latestStrategy?.status==='approved'?'/conteudo':'/estrategia'):'/onboarding')}>{complete?(latestStrategy?.status==='approved'?'Abrir conteúdo':latestStrategy?.status==='review'?'Revisar proposta':'Abrir estratégia'):'Continuar conversa'}<ArrowRight size={16}/></Link></div></section><div className={styles.overview}><section><h3>Perfil do negócio</h3><p>{complete?'Confirmado · versão '+data.state.profile_version:'Em construção · progresso salvo'}</p><Link href={base+'/perfil'}>Revisar informações</Link></section><section><h3>Materiais</h3><p>{data.attachments.length} arquivo(s) registrado(s)</p><Link href={base+'/onboarding'}>Enviar logo, fotos ou documentos</Link></section><section><h3>Conexões</h3><p>Informar um perfil não conecta uma conta.</p><Link href={base+'/integracoes'}>Ver dependências</Link></section></div></>}
   {area==='agentes'&&<><section className={styles.nextAction}><div className={styles.orb}>a</div><div><h2>Conhecer minha empresa</h2><p>Converse, consulte o histórico e atualize as informações que orientam os agentes.</p><Link className="button button-primary" href={base+'/onboarding'}>{complete?'Consultar e atualizar':'Continuar onboarding'}<ArrowRight size={16}/></Link></div></section><section className={styles.moduleCard}><h2>Estratégia e tráfego pago · OpenAI</h2><p>A estratégia começa pelo perfil confirmado. Publicação e orçamento continuam sujeitos às aprovações autorizadas.</p><Link href={base+'/estrategia'}>Preparar o planejamento</Link><h2>Design · Nano Banana Pro</h2><p>Materiais visuais usam o Gemini. A geração depende do fluxo de criação, do limite da empresa e da disponibilidade do provedor.</p><Link href={base+'/conteudo'}>Abrir conteúdo</Link></section></>}
   {area==='estrategia'&&<Strategy companyId={company.id} data={data} write={write} approve={actions.includes('strategy.approve')}/>}
   {area==='conteudo'&&<><EditorialCalendar day={calendarDay} key={company.id} companyId={company.id} write={write} approve={actions.includes('content.approve')}/><details className={styles.moduleCard}><summary>Acervo e importação de rascunhos anteriores</summary><DraftImportPanel companyId={company.id} companyName={company.name}/></details></>}
   {area==='assinatura'&&<CompanyPlan companyId={company.id}/>}
   {area==='crm'&&<CrmPanel companyId={company.id} inbox={false} write={actions.includes('crm.write')}/>}
   {area==='atendimento'&&<InboxPanel key={company.id} companyId={company.id} companyName={company.name}/>}
   {area==='configuracao-atendimento'&&<AttendanceSettings key={company.id} companyId={company.id} companyName={company.name}/>}
   {area==='campanhas'&&<section className={styles.moduleCard}><h2>Briefing de aquisição</h2><p>Público: {data?.confirmedProfile?.facts.audience?.value??'Perfil ainda não confirmado'}</p><p>Objetivo: {data?.confirmedProfile?.facts.objective?.value??'Não informado'}</p><p>Orçamento informado: {data?.confirmedProfile?.facts.budget?.value??'Não informado'}</p><span className="tag">Integração não conectada</span><p>A OpenAI prepara a proposta. Para veicular anúncios, faltam as conexões Meta Ads ou Google Ads e a aprovação de verba e versão pelo responsável autorizado.</p><Link className="button button-outline" href={base+'/estrategia'}>Preparar estratégia e proposta</Link></section>}
   {area==='site'&&<section className={styles.moduleCard}><h2>Site e presença digital</h2><p>{data?.state.facts.channels?.value??'Site e canais não informados.'}</p><span className="tag">Publicação indisponível</span><p>Os canais informados no perfil orientam a criação. A conversa permite consultar o site por IA e confirmar sugestões. Hospedagem e publicação ainda dependem de implementação e configuração; nenhum endereço foi conectado automaticamente.</p><Link className="button button-outline" href={base+'/perfil'}>Atualizar canais e necessidade de site</Link></section>}
   {area==='integracoes'&&<CompanyChannels key={company.id} companyId={company.id}/>}
   {area==='integracoes'&&<section className={styles.moduleCard}><h2>Dependências por ação</h2><table><thead><tr><th>Serviço</th><th>Situação</th><th>Uso</th></tr></thead><tbody><tr><td>OpenAI</td><td>{data?.provider.mode==='configured'?'Credencial no servidor · uso sujeito a limite':'Configuração pendente'}</td><td>Interpretação do onboarding; estratégia e campanhas em evolução</td></tr><tr><td>Nano Banana Pro</td><td>Homologação da geração pendente</td><td>Design de publicações</td></tr><tr><td>Google Places</td><td>Consulte a disponibilidade na conversa</td><td>Localização e concorrentes, com alternativa manual</td></tr><tr><td>Meta Ads / Google Ads</td><td>Conta não conectada</td><td>Execução e resultados de anúncios aprovados</td></tr><tr><td>Sistema de gestão</td><td>{data?.state.facts.management?.value??'Não informado'}</td><td>Matrículas e resultados financeiros</td></tr></tbody></table><p>As pendências afetam apenas as ações que dependem de cada serviço.</p></section>}
   </>}
  </main></div>
 </div>;
}
function Strategy({companyId,data,write,approve}:{companyId:string;data:OnboardingSnapshot|null;write:boolean;approve:boolean}){
 const [briefs,setBriefs]=useState<{id:string;status:string;profile_version:number;created_at:string;generation:number;output:GeneratedStrategy|null}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{const c=new AbortController();journeyApi<typeof briefs>('companies/'+companyId+'/strategy',undefined,c.signal).then(r=>{if(!c.signal.aborted)setBriefs(r);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[companyId]);
 async function prepare(){setBusy(true);setError('');try{const b=await journeyApi<typeof briefs[number]>('companies/'+companyId+'/strategy',{});setBriefs(v=>[b,...v.filter(item=>item.id!==b.id)]);}catch(e){setError(e instanceof Error?e.message:'Não foi possível preparar.');}finally{setBusy(false);}}
 async function generate(){if(busy)return;setBusy(true);setError('');try{const b=await journeyApi<typeof briefs[number]>('companies/'+companyId+'/strategy/generate',{requestId:crypto.randomUUID()});setBriefs(v=>[b,...v.filter(item=>item.id!==b.id)]);}catch(e){setError(e instanceof Error?e.message:'A geração não foi concluída.');}finally{setBusy(false);}}
 async function accept(brief:typeof briefs[number]){if(busy)return;setBusy(true);setError('');try{const b=await journeyApi<typeof briefs[number]>('companies/'+companyId+'/strategy/approve',{briefId:brief.id,generation:brief.generation});setBriefs(v=>v.map(item=>item.id===b.id?b:item));if(write){await journeyApi('companies/'+companyId+'/calendar/plan-dates',{requestId:crypto.randomUUID(),month:new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date()).slice(0,7)});await journeyApi('companies/'+companyId+'/calendar/generate',{requestId:crypto.randomUUID()});}window.location.assign('/empresa/'+companyId+'/conteudo');}catch(e){setError(e instanceof Error?e.message:'Não foi possível aprovar.');}finally{setBusy(false);}}
 return <section className={styles.moduleCard}><h2>Estratégia a partir do perfil confirmado</h2>{error&&<p role="alert" className="form-error">{error}</p>}{data?.confirmedProfile?<><p>Base: versão {data.confirmedProfile.version}. Apenas fatos confirmados são utilizados; ofertas ou preços desconhecidos continuam pendentes.</p><details><summary>Informações confirmadas usadas na estratégia</summary><dl>{(['services','audience','objective','offers','budget'] as const).map(k=><div key={k}><dt>{labels[k]}</dt><dd>{data.confirmedProfile?.facts[k]?.value??'Não informado'}</dd></div>)}</dl></details></>:<p>Confirme o perfil para preparar a estratégia desta empresa.</p>}{data?.step==='complete'?<Button disabled={busy||!write} onClick={prepare}>{busy?'Preparando…':'Preparar briefing da estratégia'}</Button>:<Link className="button button-primary" href={'/empresa/'+companyId+'/onboarding'}>Concluir perfil</Link>}{data?.step==='complete'&&write&&<Button disabled={busy} onClick={generate} style={{marginLeft:10}}>{busy?'Aguarde…':'Gerar proposta com OpenAI'}</Button>}{briefs.map(b=><article className={styles.brief} key={b.id}><Check size={17}/><div><strong>Estratégia · perfil v{b.profile_version} · geração {b.generation}</strong><p>{b.status==='superseded'?'Perfil atualizado. Prepare um novo briefing.':b.status==='approved'?'Estratégia aprovada nesta versão. Isso não aprova peças individuais nem autoriza verba de anúncios.':b.status==='review'?'Proposta gerada. Revise antes de aprovar.':b.status==='generating'?'Geração em andamento. Reabra esta página para consultar o resultado.':b.status==='failed'?'A geração falhou. Você pode tentar novamente.':'Briefing persistido. Pronto para solicitar a geração.'}</p>{b.output&&<StrategyDetails output={b.output}/ >}{b.status==='approved'&&<Link className="button button-outline" href={'/empresa/'+companyId+'/conteudo'}>Abrir calendário detalhado</Link>}{b.status==='review'&&approve&&<Button disabled={busy} onClick={()=>void accept(b)}>Aprovar e detalhar calendário · versão {b.generation}</Button>}</div></article>)}<p className={styles.provider}>A geração de estratégia usa o perfil confirmado e tem limite diário por empresa. Cada nova geração requer nova aprovação. Preparar o briefing não publica, não ativa anúncios e não gera cobrança.</p></section>;
}

function StrategyDetails({output}:{output:GeneratedStrategy}){return <div><h3>{output.calendar.length} ideias para o mês</h3>{output.calendar.length!==12&&<p className="info-note">Esta versão foi criada antes da regra de 12 publicações. Para ampliar, gere e aprove uma nova estratégia. A versão anterior permanece no histórico.</p>}<div className={styles.calendarGrid}>{output.calendar.map((c,i)=><article className={styles.calendarPost} key={i}><small>#{i+1} · Semana {c.week} · {c.format}</small><h4>{c.theme}</h4><p>{c.brief}</p>{c.needsClientVideo&&<small>Vídeo gravado pelo cliente</small>}</article>)}</div><details><summary>Direção estratégica e propostas de tráfego</summary><h3>Posicionamento</h3><p>{output.positioning}</p>{output.objectives.map((o,i)=><p key={i}>{o.goal} · Métrica: {o.metric} · Meta sugerida: {o.suggestedTarget}</p>)}{output.ads.map((a,i)=><details key={i}><summary>{a.channel} · {a.objective}</summary><p>{a.audience}</p><p>{a.copy}</p><p>Orçamento proposto: {a.budgetProposal}</p><p>{a.requiredApprovals.join('; ')}</p></details>)}<h3>20 palavras-chave sugeridas</h3><p>{output.keywords.join(' · ')}</p><p>Não representam volume medido.</p></details><details><summary>Informações pendentes ({output.unknowns.length})</summary>{output.unknowns.map((u,i)=><p key={i}>{u}</p>)}</details></div>;}
