'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {Button} from '@askadia/ui';
import {journeyApi} from '../lib/journey-api';
import styles from './journey.module.css';
type CrmData={contacts:{id:string;name:string;phone_e164:string|null;email:string|null}[];opportunities:{id:string;contact_id:string;interest:string;stage:string}[];conversations:{id:string;contact_id:string;channel:string;mode:'human'|'ai'|'closed';revision:number;triage_summary:string|null;assigned_to:string|null}[];notes:{id:string;conversation_id:string;body:string;created_at:string}[]};
const stages:Record<string,string>={new:'Novo',in_progress:'Em atendimento',qualified:'Qualificado',referred:'Encaminhado',scheduled:'Visita agendada',attended:'Compareceu',enrolled:'Matriculado',lost:'Perdido'};
export function CrmPanel({companyId,inbox,write}:{companyId:string;inbox:boolean;write:boolean}){
 const [data,setData]=useState<CrmData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[showCreate,setShowCreate]=useState(false),[selected,setSelected]=useState(''),[moving,setMoving]=useState('');const alive=useRef(true),nonce=useRef<string|null>(null),lock=useRef(false);
 const refresh=useCallback(async(signal?:AbortSignal)=>{const result=await journeyApi<CrmData>('companies/'+companyId+'/crm',undefined,signal);if(alive.current&&!signal?.aborted)setData(result);},[companyId]);
 useEffect(()=>{alive.current=true;const c=new AbortController();void refresh(c.signal).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>{alive.current=false;c.abort();};},[refresh]);
 async function mutate(path:string,body:unknown){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await journeyApi('companies/'+companyId+'/crm/'+path,body);await refresh();if(alive.current){setMoving('');setShowCreate(false);nonce.current=null;}return true;}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Não foi possível salvar.');return false;}finally{lock.current=false;if(alive.current)setBusy(false);}}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const fields=new FormData(e.currentTarget);nonce.current??=crypto.randomUUID();await mutate('contacts',{requestId:nonce.current,name:String(fields.get('name')),phone:String(fields.get('phone')),email:String(fields.get('email')),interest:String(fields.get('interest'))});}
 const conversation=data?.conversations.find(c=>c.id===selected);
 return <section className={styles.moduleCard}>{error&&<div className="error-banner" role="alert">{error}</div>}{inbox&&<><span className="tag">Canal não conectado</span><h2>Atendimento e encaminhamentos</h2><p>WhatsApp e Instagram ainda não estão conectados. Os registros abaixo são internos; nenhuma mensagem será enviada. A conexão Evolution depende de instância, chave e webhook.</p></>}<div className={styles.cardHeading}><h2>{inbox?'Registros de atendimento':'CRM da empresa'}</h2>{write&&<Button variant="outline" disabled={busy} onClick={()=>setShowCreate(v=>!v)}>{showCreate?'Fechar cadastro':'Adicionar contato'}</Button>}</div>
 {showCreate&&<form className="form" onSubmit={create}><fieldset disabled={busy}><label>Nome<input name="name" required minLength={2} maxLength={150}/></label><label>Telefone com DDD<input name="phone" inputMode="tel" maxLength={25}/></label><label>E-mail<input name="email" type="email" maxLength={254}/></label><label>Interesse<textarea name="interest" maxLength={2000}/></label><Button type="submit">Salvar contato e oportunidade</Button></fieldset></form>}
 {!data?<p role="status">{error?'Não foi possível carregar os dados.':'Carregando…'}</p>:<><p>{data.contacts.length} contato(s) · {data.opportunities.length} oportunidade(s). Até 200 registros por lista.</p>{!data.contacts.length?<p>Nenhum contato cadastrado nesta empresa.</p>:<table><thead><tr><th>Contato</th><th>Telefone</th><th>Oportunidade</th>{write&&<th>Ações</th>}</tr></thead><tbody>{data.contacts.map(c=>{const opportunity=data.opportunities.find(o=>o.contact_id===c.id);return <tr key={c.id}><td>{c.name}<br/><small>{c.email??''}</small></td><td>{c.phone_e164??'Não informado'}</td><td>{opportunity?stages[opportunity.stage]:'Sem oportunidade'}<br/>{opportunity?.interest}</td>{write&&<td><Button size="small" variant="outline" disabled={busy} onClick={async()=>{await mutate('conversations',{contactId:c.id});setSelected('');}}>Registrar atendimento</Button>{opportunity&&<Button size="small" variant="ghost" onClick={()=>setMoving(opportunity.id)}>Mudar etapa</Button>}</td>}</tr>;})}</tbody></table>}
 {moving&&write&&<form className="form" style={{marginTop:20}} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate('stage',{id:moving,stage:String(f.get('stage')),reason:String(f.get('reason'))});}}><label>Nova etapa<select name="stage" defaultValue={data.opportunities.find(o=>o.id===moving)?.stage}>{Object.entries(stages).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Motivo ou contexto<textarea name="reason" minLength={2} maxLength={2000} required/></label><Button disabled={busy} type="submit">Registrar mudança</Button><Button variant="ghost" type="button" onClick={()=>setMoving('')}>Cancelar</Button></form>}
 {data.conversations.length>0&&<><h2 style={{marginTop:28}}>Atendimentos</h2><div className={styles.quickReplies}>{data.conversations.map(c=><button key={c.id} onClick={()=>setSelected(c.id)}>{data.contacts.find(p=>p.id===c.contact_id)?.name??'Contato'} · {c.mode==='ai'?'Triagem IA':c.mode==='closed'?'Encerrado':'Humano'}</button>)}</div>{conversation&&<div className={styles.moduleCard}><h3>{data.contacts.find(c=>c.id===conversation.contact_id)?.name??'Atendimento'}</h3><p>Resumo da triagem: {conversation.triage_summary??'Ainda não há triagem por IA.'}</p><p>{conversation.mode==='human'?'Atendimento humano. Novas respostas da IA ficam bloqueadas.':conversation.mode==='closed'?'Atendimento encerrado.':'Triagem automática. Assuma para interromper a IA.'}</p>{write&&conversation.mode!=='closed'&&<div className="row"><Button disabled={busy} onClick={()=>void mutate('mode',{id:conversation.id,revision:conversation.revision,mode:'human'})}>Assumir atendimento</Button><Button disabled={busy} variant="outline" onClick={()=>void mutate('mode',{id:conversation.id,revision:conversation.revision,mode:'closed'})}>Encerrar</Button></div>}{data.notes.filter(n=>n.conversation_id===conversation.id).reverse().map(n=><article className={styles.brief} key={n.id}><p style={{whiteSpace:'pre-wrap'}}>{n.body}<br/><small>{new Date(n.created_at).toLocaleString('pt-BR')}</small></p></article>)}{write&&conversation.mode==='human'&&<form className="form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const ok=await mutate('notes',{id:conversation.id,requestId:crypto.randomUUID(),body:String(new FormData(form).get('body'))});if(ok)form.reset();}}><label>Nota interna, tarefa ou encaminhamento<textarea name="body" required maxLength={6000} rows={3}/></label><p>Assuma o atendimento antes de registrar. Esta nota fica no sistema e não é enviada ao contato.</p><Button disabled={busy} type="submit">Registrar nota interna</Button></form>}</div>}</>}
 </>}
 </section>;
}
