'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Modal} from '@askadia/ui';
import type {InboxMessage} from '@askadia/contracts';
import {journeyApi} from '../lib/journey-api';
type History={contact:{name:string;created_at:string};thread:string|null;warning:string;hasMore:boolean;messages:InboxMessage[];metrics:{firstAvailableAt:string|null;firstResponseMs:number|null;averageResponseMs:number|null;responseCount:number;awaitingSince:string|null;lastInbound:InboxMessage|null;lastOutbound:InboxMessage|null};conversations:{id:string;triage_summary:string|null}[];notes:{id:string;body:string;created_at:string}[];stages:{id:string;stage:string;reason:string;created_at:string}[]};
const date=(v:string|null)=>v?new Date(v).toLocaleString('pt-BR'):'Não disponível';
const duration=(v:number|null)=>v===null?'Sem resposta registrada':v<60000?'Menos de 1 minuto':v<3600000?Math.round(v/60000)+' min':(v/3600000).toFixed(1)+' h';
export function CustomerHistory({companyId,contactId,close}:{companyId:string;contactId:string;close:()=>void}){
 const [data,setData]=useState<History|null>(null),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();setData(null);setError('');void journeyApi<History>('companies/'+companyId+'/crm/contacts/'+contactId+'/history',undefined,c.signal).then(d=>{if(!c.signal.aborted)setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[companyId,contactId]);
 return <Modal open onOpenChange={v=>{if(!v)close();}} title={data?.contact.name??'Histórico do cliente'} description="Mensagens e relacionamento desta empresa.">{error&&<p role="alert">{error}</p>}{!data&&!error?<p role="status">Consultando histórico…</p>:data&&<div style={{display:'grid',gap:18}}>{data.warning&&<p role="status">{data.warning}</p>}<dl><dt>Primeiro contato disponível no WhatsApp</dt><dd>{date(data.metrics.firstAvailableAt)}</dd><dt>Cadastrado no CRM</dt><dd>{date(data.contact.created_at)}</dd><dt>Primeira resposta na amostra</dt><dd>{duration(data.metrics.firstResponseMs)}</dd><dt>Tempo médio de resposta</dt><dd>{duration(data.metrics.averageResponseMs)} · {data.metrics.responseCount} resposta(s)</dd></dl><small>Cálculo sobre até 50 mensagens recentes, incluindo respostas humanas e da IA. O histórico sincronizado pode não conter o primeiro contato original.</small>{data.metrics.awaitingSince&&<p>Aguardando resposta desde {date(data.metrics.awaitingSince)}.</p>}<section><h3>Resumo das últimas mensagens</h3><p><strong>Cliente:</strong> {data.metrics.lastInbound?.body??'Sem mensagem recebida disponível.'}</p><p><strong>Empresa:</strong> {data.metrics.lastOutbound?.body??'Sem resposta disponível.'}</p>{data.conversations.filter(c=>c.triage_summary).map(c=><p key={c.id}><strong>Triagem registrada:</strong> {c.triage_summary}</p>)}</section>{data.thread&&<Link href={'/empresa/'+companyId+'/atendimento?thread='+encodeURIComponent(data.thread)}>Abrir conversa completa no WhatsApp</Link>}<details><summary>Últimas mensagens ({data.messages.length})</summary>{data.messages.slice(-20).map(m=><article key={m.id} style={{padding:'10px 0',borderBottom:'1px solid #e5e7eb'}}><small>{m.fromMe?'Empresa':'Cliente'} · {date(m.time)}</small><p style={{whiteSpace:'pre-wrap'}}>{m.body}</p></article>)}</details><section><h3>Histórico comercial e notas</h3>{[...data.notes.map(n=>({...n,label:'Nota interna',text:n.body})),...data.stages.map(n=>({...n,label:'Mudança de etapa',text:n.reason}))].sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(n=><article key={n.id}><small>{n.label} · {date(n.created_at)}</small><p>{n.text}</p></article>)}{!data.notes.length&&!data.stages.length&&<p>Ainda não há notas ou mudanças de etapa registradas.</p>}</section></div>}</Modal>;
}
