'use client';
import {BrandWordmark} from './brand';

import Link from 'next/link';
import { useEffect,useRef,useState,type FormEvent } from 'react';
import { ArrowUpRight,BarChart3,Download,FileUp,Info,RefreshCw,ShieldCheck,TrendingUp } from 'lucide-react';
import { Button,Modal } from '@askadia/ui';
import { dashboardQuerySchema,dateInZone,presetPeriod,LatestRequest,type DashboardQuery,type Metric } from '@askadia/contracts';
import type { DashboardSnapshot } from '../../api/src/dashboard/engine';
import './dashboard.css';
type Company={id:string;name:string;timezone:string;city:string;segment:string};
const tabs=[['overview','Visão geral'],['trends','Tendências'],['instagram','Instagram'],['traffic','Tráfego'],['site','Site'],['funnel','Funil'],['finance','Retorno financeiro']] as const;
const baseLabels:Record<string,string>={mediaCents:'Investimento em mídia',otherAcquisitionCents:'Outros custos de aquisição',newCustomers:'Novos clientes pagantes',mediaCustomers:'Novos clientes atribuídos à mídia',netCents:'Receita líquida atribuída',mediaAttributedNetCents:'Receita atribuída à mídia',attributedNetCents:'Receita líquida atribuída',variableCostCents:'Custos variáveis',marginCents:'Margem de contribuição',acquisitionCents:'Custos de aquisição',leads:'Contatos distintos'};
const quality:Record<string,string>={available:'Disponível',partial:'Parcial',estimated:'Estimado',no_history:'Sem histórico',no_basis:'Sem base',stale:'Desatualizado',disconnected:'Desconectado',unsupported:'Não suportado',forbidden:'Sem permissão'};
function value(m:Metric){if(m.value===null)return '—';if(m.unit==='BRL')return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(m.value);return m.value.toLocaleString('pt-BR',{maximumFractionDigits:m.unit==='count'?0:2})+(m.unit==='percent'?'%':m.unit==='multiple'?'x':'');}
async function request<T>(path:string,body?:unknown,signal?:AbortSignal):Promise<T>{
 const r=await fetch('/api/dashboard'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal,cache:'no-store'});
 const result=await r.json();if(!r.ok)throw new Error(result.message??'Não foi possível consultar os indicadores.');return result;
}
function Empty({title,text}:{title:string;text:string}){return <div className="db-empty"><BarChart3 size={27}/><h3>{title}</h3><p>{text}</p></div>;}
export function DashboardPanel({companies,initial,today}:{companies:Company[];initial:Partial<DashboardQuery>;today:string}){
 const first=companies.find(c=>c.id===initial.companyId)??companies[0];
 const [query,setQuery]=useState<DashboardQuery>(()=>dashboardQuerySchema.parse({...presetPeriod('30',today),...initial,companyId:first?.id??'00000000-0000-4000-8000-000000000000',timezone:first?.timezone??'America/Sao_Paulo'}));
 const [preset,setPreset]=useState('custom');
 const [data,setData]=useState<DashboardSnapshot|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 const [metric,setMetric]=useState<Metric|null>(null),[upload,setUpload]=useState(false),[exporting,setExporting]=useState(false);
 const latest=useRef(new LatestRequest());const [selectedKpis,setSelectedKpis]=useState(['media','leads','customers','revenue','cac','roas','roi']);
 useEffect(()=>{
  if(!first){setLoading(false);return;}
  const check=dashboardQuerySchema.safeParse(query);
  if(!check.success){latest.current.cancel();setData(null);setLoading(false);setError(check.error.issues[0]?.message??'Filtros inválidos.');return;}
  const req=latest.current.begin();setData(null);setLoading(true);setError('');
  const params=new URLSearchParams(Object.entries(query).filter(([,v])=>v!==undefined).map(([k,v])=>[k,String(v)]));
  window.history.replaceState(null,'',window.location.pathname+'?'+params.toString());
  request<DashboardSnapshot>('?'+params,undefined,req.signal).then(result=>{if(req.current())setData(result);}).catch(e=>{if(req.current())setError(e.message);}).finally(()=>{if(req.current())setLoading(false);});
  return ()=>latest.current.cancel();
 },[query,revision,first]);
 function patch(values:Partial<DashboardQuery>){latest.current.cancel();setData(null);setLoading(true);if(values.start||values.end)setPreset('custom');setMetric(null);setUpload(false);setQuery(q=>({...q,...values}));}
 function company(id:string){const c=companies.find(c=>c.id===id)!;patch({companyId:id,timezone:c.timezone,account:'',campaign:'',channel:'all',access:undefined});}
 async function exportCsv(print=false){
  setExporting(true);setError('');
  try{
   const r=await fetch('/api/dashboard/exports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filters:query,format:print?'pdf':'csv'})});
   if(!r.ok){const e=await r.json();throw new Error(e.message);}
   const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=print?'askadia-dashboard.pdf':'askadia-dashboard.csv';a.click();URL.revokeObjectURL(url);
  }catch(e){setError(e instanceof Error?e.message:'Exportação indisponível.');}finally{setExporting(false);}
 }
 const section=query.section;
 const active=companies.find(c=>c.id===query.companyId);
 return <div className="db-shell"><aside className="db-sidebar"><Link href="/workspace" className="brand"><BrandWordmark/></Link><div className="db-side-caption">DESEMPENHO DO NEGÓCIO</div><nav aria-label="Seções do dashboard">{tabs.map(([id,label])=><button key={id} className={section===id?'active':''} onClick={()=>patch({section:id,account:'',campaign:'',channel:'all'})} aria-current={section===id?'page':undefined}><span>{label}</span><ArrowUpRight size={14}/></button>)}</nav><div className="db-side-bottom"><Link href="/workspace"><ShieldCheck size={15}/>Empresas e permissões</Link><small>Dados com origem.<br/>Decisões com contexto.</small></div></aside>
 <main className="db-main"><header className="db-top"><span>Resultados / {tabs.find(t=>t[0]===section)?.[1]}</span><span><ShieldCheck size={13}/>Acesso por empresa</span></header>
 <div className="db-body"><div className="db-heading"><div><p className="db-eyebrow">UMA VISÃO CLARA DO SEU NEGÓCIO</p><h1>Os números. E o que eles dizem.</h1><p>Presença digital, investimento e aquisição, com os limites de cada fonte.</p></div><Button variant="outline" onClick={()=>setRevision(n=>n+1)} disabled={loading||!first}><RefreshCw size={15}/>Atualizar leitura</Button></div>
 {!first?<section className="panel"><Empty title="Comece selecionando sua empresa." text="Cadastre uma empresa ou aceite um convite para consultar indicadores autorizados."/><Link href="/workspace" className="button button-primary">Ir para empresas</Link></section>:<>
 <form className="db-filters" onSubmit={e=>e.preventDefault()}><label>Empresa<select value={query.companyId} onChange={e=>company(e.target.value)}>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Período<select value={preset} onChange={e=>{if(e.target.value!=='custom')patch(presetPeriod(e.target.value,dateInZone(new Date(),query.timezone)));setPreset(e.target.value);}}><option value="today">Hoje</option><option value="yesterday">Ontem</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option><option value="month">Mês atual até hoje</option><option value="last_month">Mês anterior</option><option value="custom">Personalizado</option></select></label><label>De<input type="date" value={query.start} onChange={e=>patch({start:e.target.value})}/></label><label>Até<input type="date" value={query.end} onChange={e=>patch({end:e.target.value})}/></label><label>Comparação<select value={query.comparison} onChange={e=>patch({comparison:e.target.value as DashboardQuery['comparison']})}><option value="previous">Período anterior equivalente</option><option value="year">Mesmo período do ano anterior</option><option value="none">Sem comparação</option></select></label></form>
 <div className="db-period"><span>{active?.name} · {query.start} a {query.end} · {query.timezone}</span>{data?.inProgress&&<span className="tag">Período em andamento</span>}</div>
 {['traffic','finance','overview'].includes(section)&&<div className="db-secondary-filters"><label>Canal<select value={query.channel} onChange={e=>patch({channel:e.target.value as DashboardQuery['channel']})}><option value="all">Todos</option><option value="meta_ads">Meta Ads</option><option value="google_ads">Google Ads</option><option value="organic">Orgânico</option><option value="unknown">Origem desconhecida</option></select></label><label>Conta<input value={query.account} onChange={e=>patch({account:e.target.value})} placeholder="ID da conta (opcional)"/></label><label>Campanha<input value={query.campaign} onChange={e=>patch({campaign:e.target.value})} placeholder="ID da campanha (opcional)"/></label></div>}
 {error&&<div className="error-banner" role="alert">{error}</div>}{loading?<section className="panel"><Empty title="Conferindo as fontes…" text="Consultando apenas os dados autorizados para esta empresa."/></section>:data&&<>
 <div className="db-actions"><span>{data.sources.length?'Fontes importadas e auditadas':'Sem fontes de métricas conectadas'}</span>{(data.permissions.writeDigital||data.permissions.writeFinance)&&<Button variant="outline" onClick={()=>setUpload(true)}><FileUp size={15}/>Importar dados</Button>}<Button variant="outline" disabled={!data.permissions.finance||exporting} onClick={()=>void exportCsv()} title={!data.permissions.finance?'Exportação financeira requer permissão específica.':undefined}><Download size={15}/>CSV executivo</Button><Button variant="outline" disabled={!data.permissions.finance||exporting} onClick={()=>void exportCsv(true)}>PDF executivo</Button></div>
 {(section==='overview'||section==='finance')&&<>
 {section==='finance'&&<div className="db-secondary-filters"><label>Leitura<select value={query.mode} onChange={e=>patch({mode:e.target.value as DashboardQuery['mode']})}><option value="period">Operacional do período</option><option value="cohort">Coorte de aquisição</option></select></label>{query.mode==='cohort'&&<label>Observar recebimentos até<input type="date" min={query.end} value={query.observationEnd??query.end} onChange={e=>patch({observationEnd:e.target.value})}/></label>}<span>Regime: caixa realizado</span></div>}
 <details className="db-customize"><summary>Escolher de 6 a 8 indicadores</summary><div>{data.metrics.map(m=><label key={m.id}><input type="checkbox" checked={selectedKpis.includes(m.id)} disabled={selectedKpis.includes(m.id)?selectedKpis.length<=6:selectedKpis.length>=8} onChange={e=>setSelectedKpis(ids=>e.target.checked?[...ids,m.id]:ids.filter(id=>id!==m.id))}/>{m.label}</label>)}</div></details>
 <section className="db-kpis">{data.metrics.filter(m=>selectedKpis.includes(m.id)).map(m=><button className="panel db-kpi" key={m.id} onClick={()=>setMetric(m)}><span className="db-kpi-label">{m.label}<Info size={14}/></span><strong>{value(m)}</strong><span className={'db-change '+(data.comparisons[m.id]?.direction??'neutral')}>{data.comparisons[m.id]?.label??quality[m.state]}</span><small>{m.reason??m.source}</small><span className="db-kpi-status">{quality[m.state]} · Ver cálculo</span></button>)}</section>
 <section className="panel db-chart-panel"><div className="db-section-heading"><div><h2>Investimento, aquisição e retorno</h2><p>Séries separadas por unidade. Valores desconhecidos permanecem vazios. Barras de estorno indicam magnitude; sinais e valores constam na tabela.</p></div><TrendingUp size={21}/></div>{data.series.length?<><div className="db-series">{[['mediaBRL','Investimento · R$'],['customers','Novos clientes · pessoas'],['attributedRevenueBRL','Receita atribuída · R$']].map(([field,label])=>{const key=field as 'mediaBRL'|'customers'|'attributedRevenueBRL';const max=Math.max(1,...data.series.map(p=>Math.abs(p[key]??0)));return <figure key={field}><figcaption>{label}</figcaption><div className="db-bars" role="img" aria-label={label+' por dia; valores na tabela abaixo'}>{data.series.map(p=><div key={p.date} title={p.date+': '+(p[key]??'indisponível')}><i data-negative={(p[key]??0)<0} style={{height:p[key]===null?'0%':Math.max(1,Math.abs(p[key]??0)/max*100)+'%'}}/></div>)}</div><small>{query.start} → {query.end}</small></figure>;})}</div><details><summary>Ver dados em tabela</summary><div className="db-table"><table><thead><tr><th>Data</th><th>Mídia (R$)</th><th>Novos clientes</th><th>Receita (R$)</th></tr></thead><tbody>{data.series.map(p=><tr key={p.date}><td>{p.date}</td><td>{p.mediaBRL??'—'}</td><td>{p.customers??'—'}</td><td>{p.attributedRevenueBRL??'—'}</td></tr>)}</tbody></table></div></details></>:<Empty title="Uma boa decisão começa com dados." text="Importe métricas verificadas ou conclua uma conexão para formar esta série."/>}</section>
 <p className="db-footnote">{data.financialNote} Cobertura de origem: {data.attributionCoverage===null?'indisponível':data.attributionCoverage.toFixed(1)+'% dos novos clientes elegíveis'}.</p>
 </>}
 {(section==='funnel'||section==='overview')&&<section className="panel db-chart-panel"><div className="db-section-heading"><div><h2>Da primeira conversa à aquisição</h2><p>{data.funnelNote}</p></div></div>{data.funnel?<div className="db-funnel">{data.funnel.map(stage=><div key={stage.stage}><span>{stage.label}</span><strong>{stage.count}</strong></div>)}</div>:<Empty title="Funil indisponível para este recorte." text="Atribuição de campanha e indicadores individuais dependem de vínculos verificáveis no CRM."/>}</section>}
 {(section==='traffic'||section==='overview')&&<section className="panel db-chart-panel"><div className="db-section-heading"><div><h2>Tráfego, conta por conta</h2><p>Taxas recalculadas pelos totais; conversões reportadas não são clientes únicos.</p></div></div>{data.ads.length?data.ads.map(group=><div key={group.key}><p className="db-footnote">{group.provider} · Conta {group.accountId} · {group.timezone} · Cliques: {group.clickType} · Data-base: {group.dateBasis}</p><div className="db-table"><table><thead><tr><th>Campanha</th><th>Data</th><th>Gasto</th><th>Impressões</th><th>Cliques</th><th>Conversões reportadas</th></tr></thead><tbody>{group.rows.map(r=><tr key={r.id}><td>{r.campaignName}</td><td>{r.date}</td><td>{(r.spendCents/100).toFixed(2)}</td><td>{r.impressions}</td><td>{r.clicks}</td><td>{r.reportedConversions??'—'}</td></tr>)}</tbody></table></div><p className="db-footnote">CTR {group.ctr?.toFixed(2)??'—'}% · CPC R$ {group.cpc?.toFixed(2)??'—'} · CPM R$ {group.cpm?.toFixed(2)??'—'}</p></div>):<Empty title="Contas de anúncio ainda sem dados." text="A integração de leitura exige conta autorizada e homologação. Você pode importar um relatório validado."/>}</section>}
 {(section==='instagram'||section==='overview')&&<section className="panel db-chart-panel"><div className="db-section-heading"><div><h2>Conteúdos do Instagram</h2><p>Alcances individuais não são somados como audiência única.</p></div><select aria-label="Temporalidade Instagram" value={query.socialMode} onChange={e=>patch({socialMode:e.target.value as DashboardQuery['socialMode']})}><option value="published">Publicados no período</option><option value="activity">Atividade ocorrida no período</option></select></div>{data.social.length?<div className="db-table"><table><thead><tr><th>Conteúdo</th><th>Escopo</th><th>Alcance</th><th>Interações / alcance</th><th>Coleta</th></tr></thead><tbody>{data.social.map(p=><tr key={p.id}><td><a href={p.permalink} target="_blank" rel="noreferrer">{p.caption.slice(0,100)||p.format}<ArrowUpRight size={12}/></a></td><td>{p.scope}</td><td>{p.reach??'—'}</td><td>{p.engagementRate?.toFixed(2)??'—'}%</td><td>{new Date(p.collectedAt).toLocaleDateString('pt-BR')}</td></tr>)}</tbody></table></div>:<Empty title="O desempenho precisa de contexto." text="Nenhuma publicação com cobertura compatível. Métricas lifetime não viram resultados mensais por subtração."/>}</section>}
 {section==='trends'&&<section className="panel db-chart-panel"><h2>20 palavras-chave prioritárias</h2>{data.permissions.writeDigital&&<KeywordProfile key={data.company.id+String(data.keywordProfile?.revision??0)} companyId={data.company.id} city={data.company.city} profile={data.keywordProfile} onSaved={()=>setRevision(n=>n+1)}/>}<details className="db-customize" open={!data.trends.length}><summary>Candidatos editoriais — pesquisa pendente</summary>{data.keywordCandidates.length?<div className="db-table"><table><thead><tr><th>Prioridade editorial</th><th>Termo sugerido</th><th>Situação</th></tr></thead><tbody>{data.keywordCandidates.map(candidate=><tr key={candidate.term}><td>{candidate.priority}</td><td>{candidate.term}</td><td>Não medido · <a target="_blank" rel="noreferrer" href={'https://trends.google.com/trends/explore?q='+encodeURIComponent(candidate.term)}>Pesquisar</a></td></tr>)}</tbody></table></div>:<p>Confirme o perfil de serviços e a cidade para gerar candidatos sem presumir modalidades.</p>}</details><p className="db-footnote">Ranking somente dos candidatos pesquisados. Interesse relativo não é volume absoluto. Canal e campanha não filtram Trends.</p>{data.trends.length?data.trends.map(group=><section className="db-trend-group" key={group.key}><h3>{group.region} · Lote {group.batchId}</h3><p>Escala: {group.scale}. Lotes independentes não são consolidados.</p><div className="db-table"><table><thead><tr><th>Posição no lote</th><th>Termo / tópico</th><th>Interesse médio</th><th>Origem</th></tr></thead><tbody>{group.ranking.slice(0,20).map((r,i)=><tr key={r.termType+r.term}><td>{r.interest===null?'—':i+1}</td><td>{r.term}<small>{r.termType}</small></td><td>{r.interest??'Dados insuficientes'}</td><td><a href={r.points[0]!.sourceUrl} target="_blank" rel="noreferrer">Abrir pesquisa</a></td></tr>)}</tbody></table></div></section>):<Empty title="Pesquisa pendente." text="Importe o CSV temporal do Google Trends com região, período e lote. As sugestões dependem dos serviços confirmados no onboarding; nenhum termo é apresentado como medido sem fonte."/>}</section>}
 {section==='site'&&<section className="panel db-chart-panel"><h2>Site e busca orgânica</h2><p className="db-footnote">GA4, Search Console e formulários são fontes distintas. Usuários únicos não são somados por dia. Filtros de campanha dependem da dimensão coletada.</p>{data.web.length?<div className="db-table"><table><thead><tr><th>Fonte</th><th>Data</th><th>Recurso</th><th>Métrica</th><th>Valor</th><th>Cobertura</th></tr></thead><tbody>{data.web.map(w=><tr key={w.id}><td>{w.provider}</td><td>{w.date}</td><td>{w.resource}</td><td>{w.metric}</td><td>{w.value}</td><td>{w.coverage}</td></tr>)}</tbody></table></div>:<Empty title="As fontes do site ainda não estão disponíveis." text="GA4 exige instrumentação e propriedade autorizada; Search Console exige uma propriedade validada. Não há histórico retroativo presumido."/>}</section>}
 <section className="panel db-chart-panel"><h2>Fontes, cobertura e próximos passos</h2>{data.sources.length?<div className="db-source-list">{data.sources.map((s,i)=><div key={i}><strong>{s.source}</strong><span>{s.start} a {s.end} · {s.complete?'Declarada completa':'Parcial'}</span><small>Atualização: {new Date(s.updatedAt).toLocaleString('pt-BR',{timeZone:query.timezone})} · {s.note}</small></div>)}</div>:<p className="db-footnote">Instagram, Meta Ads, Google Ads, GA4, Search Console e gestão: conexões de leitura ainda não homologadas. O Google Trends depende de acesso aprovado ou CSV.</p>}{data.limitations.map((text,i)=><p className="db-alert" key={i}><Info size={15}/>{text}</p>)}<p className="db-footnote">Diagnóstico de IA: configuração pendente. Nenhuma análise paga é executada ao abrir esta página.</p></section>
 </>}</>}
 </div></main>
 <Modal open={Boolean(metric)} onOpenChange={v=>{if(!v)setMetric(null);}} title={metric?.label??'Memória de cálculo'} description="Mesmos filtros aplicados ao card, à série e ao relatório.">{metric&&<div className="db-memory"><strong>{value(metric)}</strong><p>{metric.formula}</p><dl>{Object.entries(metric.bases).map(([key,v])=><div key={key}><dt>{baseLabels[key]??key}</dt><dd>{v===null?'Não informado':key.endsWith('Cents')?(v/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):v.toLocaleString('pt-BR')}</dd></div>)}</dl><p>{metric.reason}</p><small>{metric.source} · {query.start} a {query.end}</small></div>}</Modal>
 <Modal open={upload} onOpenChange={setUpload} title="Dados reais, com origem." description={'Importação para '+(active?.name??'empresa')+'. O arquivo será validado antes de salvar.'}>{upload&&data&&<ImportPanel key={query.companyId} query={query} finance={data.permissions.writeFinance} onComplete={()=>{setUpload(false);setRevision(n=>n+1);}}/>}</Modal>
 </div>;
}
function ImportPanel({query,finance,onComplete}:{query:DashboardQuery;finance:boolean;onComplete:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[csv,setCsv]=useState(''),[preview,setPreview]=useState<{count:number;source:string;domain:string}|null>(null),[payload,setPayload]=useState<unknown>(null);
 const [domain,setDomain]=useState('digital');
 async function submit(e:FormEvent<HTMLFormElement>){
  e.preventDefault();setBusy(true);setError('');setPreview(null);const f=new FormData(e.currentTarget);
  const body={companyId:query.companyId,csv,metadata:{source:String(f.get('source')),domain,coverageStart:query.start,coverageEnd:query.end,coverage:String(f.get('coverage')),note:String(f.get('note'))},format:domain==='trends'?'google_trends':'facts',...(domain==='trends'?{trends:{batchId:crypto.randomUUID(),region:String(f.get('region')),collectedAt:new Date().toISOString(),sourceUrl:'https://trends.google.com/trends/explore',language:'pt-BR',searchType:'web',termType:'search_term'}}:{})};
  try{const result=await request<{count:number;source:string;domain:string}>('/imports/preview',body);setPreview(result);setPayload(body);}catch(e){setError(e instanceof Error?e.message:'Arquivo inválido.');}finally{setBusy(false);}
 }
 async function confirm(){setBusy(true);setError('');try{await request('/imports',payload);onComplete();}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar.');}finally{setBusy(false);}}
 return <form className="form" onSubmit={submit} onChange={()=>setPreview(null)}><fieldset disabled={busy}><label>Tipo<select value={domain} onChange={e=>setDomain(e.target.value)}><option value="digital">Relatório digital normalizado</option><option value="trends">CSV do Google Trends</option>{finance&&<option value="finance">Gestão / custos financeiros</option>}</select></label><label>Identificador estável da fonte<input name="source" required minLength={2} maxLength={100} placeholder="Ex.: gestão-unidade-centro"/></label>{domain==='trends'&&<label>Região efetiva do CSV<input name="region" required placeholder="Ex.: Brasil ou São Paulo"/></label>}<label>Cobertura<select name="coverage"><option value="partial">Parcial</option><option value="complete">Declaro o período completo</option></select></label><label>Origem e limitações<input name="note" required minLength={5} maxLength={500} placeholder="Arquivo exportado em…; contém…"/></label><label>Arquivo CSV<input type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];if(file){if(file.size>1500000){setError('Arquivo acima de 1,5 MB.');return;}setCsv(await file.text());}}}/></label><label>Conteúdo do CSV<textarea required rows={6} value={csv} onChange={e=>setCsv(e.target.value)} placeholder="kind,id,date,…"/></label><p className="form-note">Baixe um modelo vazio: {Object.entries({ads:"anúncios",payment:"pagamentos",refund:"estornos",cost:"custos",social:"Instagram",web:"site"}).map(([kind,label])=><span key={kind}> <a href={"/templates/dashboard/"+kind+".csv"} download>{label}</a> · </span>)} Até 1.000 registros. Valores monetários em centavos, booleanos true/false, datas AAAA-MM-DD. Repetir a mesma chave externa corrige o registro e preserva a versão anterior. Importar não conecta uma API.</p><Button type="submit">Validar e revisar</Button>{preview&&<div className="db-import-confirm"><strong>{preview.count} registros válidos · {preview.source}</strong><p>Destino: empresa selecionada. Período: {query.start} a {query.end}. Confirme somente após conferir o arquivo.</p><Button type="button" onClick={()=>void confirm()} disabled={busy}>Confirmar importação</Button></div>}{error&&<div className="form-error" role="alert">{error}</div>}</fieldset></form>;
}

function KeywordProfile({companyId,city,profile,onSaved}:{companyId:string;city:string;profile:DashboardSnapshot['keywordProfile'];onSaved:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);try{await request('/keywords',{companyId,services:form.getAll('services'),neighborhood:String(form.get('neighborhood')),confirmed:form.get('confirmed')==='on'});onSaved();}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar.');}finally{setBusy(false);}}
 return <details className="db-customize"><summary>{profile?'Revisar serviços confirmados':'Confirmar serviços para gerar 20 candidatos'}</summary><form className="db-keyword-profile" onSubmit={save}><p>Cidade do cadastro: {city||'Não informada — atualize o perfil da empresa'}. Selecione somente serviços e benefícios realmente oferecidos.</p><fieldset disabled={busy||!city}>{['musculação','pilates','funcional','spinning','dança','personal','24 horas','totalpass','wellhub'].map(service=><label key={service}><input type="checkbox" name="services" value={service} defaultChecked={profile?.services.includes(service)}/>{service}</label>)}<label>Bairro (opcional)<input name="neighborhood" defaultValue={profile?.neighborhood??''} maxLength={100}/></label><label><input name="confirmed" type="checkbox" required/>Confirmo que esses serviços correspondem à empresa.</label><Button type="submit">Salvar perfil da pesquisa</Button></fieldset>{error&&<p role="alert" className="form-error">{error}</p>}</form></details>;
}
