'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Button} from '@askadia/ui';
import {type CalendarItem,type CreativeAsset,type DetailedPost} from '@askadia/contracts';
import {journeyApi} from '../lib/journey-api';
import styles from './journey.module.css';
type Snapshot={materials:{id:string;name:string;mime:string;size:number}[];items:CalendarItem[];assets:CreativeAsset[];current:{id:string;generation:number;status:string}|null};
export function EditorialCalendar({companyId,write,approve}:{companyId:string;write:boolean;approve:boolean}){
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[showHistory,setShowHistory]=useState(false);const lock=useRef(false);const [selectedMaterials,setSelectedMaterials]=useState<string[]>([]);const materialSeed=useRef(false);
 const load=useCallback(async(signal?:AbortSignal)=>{const r=await journeyApi<Snapshot>('companies/'+companyId+'/calendar',undefined,signal);if(!signal?.aborted){setData(r);if(!materialSeed.current){setSelectedMaterials(r.materials.slice(0,3).map(m=>m.id));materialSeed.current=true;}}},[companyId]);
 useEffect(()=>{const c=new AbortController();load(c.signal).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[load]);
 async function action(path:string,body:unknown,label:string){if(lock.current)return false;lock.current=true;setBusy(label);setError('');try{await journeyApi('companies/'+companyId+'/calendar/'+path,path==='design'?{...(body as Record<string,unknown>),materials:selectedMaterials}:body);await load();return true;}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir.');return false;}finally{lock.current=false;setBusy('');}}
 const active=(item:CalendarItem)=>data?.current?.status==='approved'&&item.brief_id===data.current.id&&item.generation===data.current.generation;
 const items=data?.items.filter(i=>showHistory||active(i))??[];const pending=items.filter(i=>active(i)&&!i.details).length;
 return <section className={styles.moduleCard}><div className={styles.cardHeading}><div><h2>Calendário editorial</h2><p>Ideia aprovada → conteúdo detalhado → criativo → aprovação da peça.</p></div><Link href={'/empresa/'+companyId+'/estrategia'}>Ver estratégia</Link></div>{error&&<p className="form-error" role="alert">{error}</p>}{busy&&<p role="status">{busy}</p>}
 {data&&<><details className={styles.moduleCard}><summary>Materiais de referência do designer ({selectedMaterials.length})</summary><p>Selecione até 5 imagens: logo, fotos reais e referências enviadas pela empresa. As imagens selecionadas serão enviadas ao Gemini junto com o briefing. Cores e tom de voz vêm do perfil confirmado.</p>{data.materials.length?data.materials.map(m=><label style={{display:'block',marginBottom:10}} key={m.id}><input type="checkbox" checked={selectedMaterials.includes(m.id)} disabled={!!busy||(!selectedMaterials.includes(m.id)&&selectedMaterials.length>=5)} onChange={e=>setSelectedMaterials(v=>e.target.checked?[...v,m.id]:v.filter(id=>id!==m.id))}/> {m.name}</label>):<p>Nenhuma imagem enviada. Adicione logo e fotos no perfil para o designer trabalhar com seus materiais.</p>}<Link href={'/empresa/'+companyId+'/perfil'}>Enviar ou revisar materiais da empresa</Link></details><div className={styles.cardHeading}><p>{items.length} publicações {showHistory?'no histórico':'na estratégia atual'} · {pending} aguardando detalhamento</p><label><input type="checkbox" checked={showHistory} onChange={e=>setShowHistory(e.target.checked)}/> Mostrar versões anteriores</label></div>{pending>0&&write&&<Button disabled={!!busy} onClick={()=>void action('generate',{requestId:crypto.randomUUID()},'Detalhando as ideias aprovadas com OpenAI…')}>Detalhar publicações pendentes</Button>}{!items.length&&<p>As ideias entram aqui quando a estratégia é aprovada. Nenhuma publicação é criada antes da aprovação.</p>}
 {[1,2,3,4,5].filter(week=>items.some(i=>i.week===week)).map(week=><section className={styles.calendarWeek} key={week}><h3>Semana {week}</h3><div className={styles.calendarGrid}>{items.filter(i=>i.week===week).sort((a,b)=>a.position-b.position).map(item=><CalendarPost key={item.id} item={item} assets={data.assets.filter(a=>a.item_id===item.id&&a.revision===item.revision)} companyId={companyId} current={active(item)} write={write} approve={approve} busy={!!busy} action={action}/>)}</div></section>)}</>}
 <p className={styles.provider}>Datas são propostas de planejamento, não agendamento de envio. Publicar exige conta Meta conectada e aprovação da peça final. Vídeos recebem roteiro; a produção e o arquivo final são do cliente.</p></section>;
}
function CalendarPost({item,assets,companyId,current,write,approve,busy,action}:{item:CalendarItem;assets:CreativeAsset[];companyId:string;current:boolean;write:boolean;approve:boolean;busy:boolean;action:(path:string,body:unknown,label:string)=>Promise<boolean>}){
 const [editing,setEditing]=useState(false),[draft,setDraft]=useState<DetailedPost|null>(item.details),[date,setDate]=useState(item.planned_date??'');
 const frames=item.format==='carrossel'?item.details?.slides.length??0:1;const completeMedia=item.format!=='video'&&Array.from({length:frames},(_,f)=>assets.some(a=>a.frame===f)).every(Boolean)&&frames>0;
 return <article className={styles.calendarPost}><small>#{item.position} · {item.format} · {current?'Estratégia atual':'Versão anterior'} · v{item.revision}</small><h4>{item.idea}</h4><p>{item.planned_date??'Data a definir'}</p><span className="tag">{item.status==='approved'?'Peça aprovada':item.details?'Em produção':'Aguardando detalhamento'}</span>
 {!item.details?<p>O conteúdo será desenvolvido a partir desta ideia e da direção aprovada.</p>:<details><summary>Texto e orientação criativa</summary>{editing&&draft?<form className="form" onSubmit={async e=>{e.preventDefault();if(await action('edit',{id:item.id,revision:item.revision,details:draft,date:date||null},'Salvando nova versão do conteúdo…'))setEditing(false);}}><label>Data proposta<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{(['title','caption','cta','designBrief','videoScript'] as const).map(key=><label key={key}>{{title:'Título',caption:'Legenda',cta:'Chamada para ação',designBrief:'Briefing para o designer',videoScript:'Roteiro de vídeo'}[key]}<textarea rows={key==='caption'||key==='designBrief'?5:2} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} maxLength={key==='caption'?2200:key==='designBrief'?4000:key==='videoScript'?6000:key==='title'?300:500}/></label>)}{draft.slides.map((slide,index)=><div key={index}><label>Texto do slide {index+1}<textarea value={slide.text} maxLength={500} onChange={e=>setDraft({...draft,slides:draft.slides.map((s,i)=>i===index?{...s,text:e.target.value}:s)})}/></label><label>Visual do slide {index+1}<textarea value={slide.visual} maxLength={1500} onChange={e=>setDraft({...draft,slides:draft.slides.map((s,i)=>i===index?{...s,visual:e.target.value}:s)})}/></label></div>)}<Button disabled={busy} type="submit">Salvar nova versão</Button><Button type="button" variant="ghost" onClick={()=>setEditing(false)}>Cancelar</Button><p>Editar invalida a aprovação e exige criativos para a nova versão.</p></form>:<><h5>{item.details.title}</h5><p className={styles.preserveText}>{item.details.caption}</p><p>{item.details.cta}</p><p>{item.details.hashtags.join(' ')}</p><h5>Briefing do designer</h5><p className={styles.preserveText}>{item.details.designBrief}</p>{item.details.slides.map((s,i)=><div key={i}><h5>Slide {i+1}</h5><p>{s.text}</p><p>{s.visual}</p></div>)}{item.details.videoScript&&<><h5>Roteiro e edição</h5><p className={styles.preserveText}>{item.details.videoScript}</p></>}{item.details.clientMaterials.length>0&&<><h5>Materiais do cliente</h5><ul>{item.details.clientMaterials.map((s,i)=><li key={i}>{s}</li>)}</ul></>}{item.details.unknowns.length>0&&<><h5>Informações a confirmar</h5><ul>{item.details.unknowns.map((s,i)=><li key={i}>{s}</li>)}</ul></>}{current&&write&&<Button variant="outline" disabled={busy} onClick={()=>{setDraft(item.details);setDate(item.planned_date??'');setEditing(true);}}>Editar conteúdo e data</Button>}</>}</details>}
 {item.details&&<div className={styles.creativeList}>{item.format==='video'?<p>Roteiro pronto para gravação. A entrega do vídeo final no calendário ainda está em implantação; a aprovação fica bloqueada até o arquivo existir.</p>:Array.from({length:frames},(_,frame)=>{const asset=assets.find(a=>a.frame===frame);return <div key={frame}><p>{frames>1?'Slide '+(frame+1):'Criativo da publicação'}</p>{asset&&<a href={'/api/onboarding/companies/'+companyId+'/creatives/'+asset.id} target="_blank" rel="noreferrer">Abrir criativo · {asset.model}</a>}{current&&write&&<Button variant="outline" disabled={busy} onClick={()=>void action('design',{requestId:crypto.randomUUID(),id:item.id,frame},'Designer criando a arte a partir do briefing aprovado…')}>{asset?'Gerar nova opção':'Gerar criativo com Gemini'}</Button>}</div>;})}</div>}
 {current&&approve&&item.status!=='approved'&&<Button disabled={busy||!completeMedia} onClick={()=>void action('approve',{id:item.id,revision:item.revision},'Registrando aprovação da peça…')}>Aprovar peça final</Button>}
 </article>;
}
