'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Button} from '@askadia/ui';
import {type CalendarItem,type CreativeAsset,type DetailedPost} from '@askadia/contracts';
import {journeyApi} from '../lib/journey-api';
import styles from './journey.module.css';
type FinalVideo={id:string;item_id:string;revision:number;name:string;size:number};
type Snapshot={videos:FinalVideo[];materials:{id:string;name:string;mime:string;size:number}[];items:CalendarItem[];assets:CreativeAsset[];current:{id:string;generation:number;status:string;output?:{planningMonth?:string}}|null};
export function EditorialCalendar({companyId,write,approve,day}:{companyId:string;write:boolean;approve:boolean;day?:string}){
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[month,setMonth]=useState((day&&day!=='sem-data'?day.slice(0,7):undefined)??new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date()).slice(0,7));const lock=useRef(false),stop=useRef(false);const [selectedMaterials,setSelectedMaterials]=useState<string[]>([]);const materialSeed=useRef(false);
 const load=useCallback(async(signal?:AbortSignal)=>{const r=await journeyApi<Snapshot>('companies/'+companyId+'/calendar',undefined,signal);if(!signal?.aborted){setData(r);if(!materialSeed.current){setSelectedMaterials(r.materials.slice(0,3).map(m=>m.id));materialSeed.current=true;if(!day&&r.current?.output?.planningMonth)setMonth(r.current.output.planningMonth);}}return r;},[companyId,day]);
 useEffect(()=>{const c=new AbortController();load(c.signal).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>{c.abort();stop.current=true;};},[load]);
 async function action(path:string,body:unknown,label:string){if(lock.current)return false;lock.current=true;setBusy(label);setError('');try{await journeyApi('companies/'+companyId+'/calendar/'+path,path==='design'?{...(body as Record<string,unknown>),materials:selectedMaterials}:body);await load();return true;}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir.');return false;}finally{lock.current=false;setBusy('');}}
 const active=(item:CalendarItem,snap=data)=>snap?.current?.status==='approved'&&item.brief_id===snap.current.id&&item.generation===snap.current.generation;
 const items=data?.items.filter(i=>active(i))??[];const pendingDates=items.some(i=>!i.planned_date);
 async function generateMonth(design=false){if(lock.current)return;lock.current=true;stop.current=false;setError('');try{let snap=data!;if(snap.items.some(i=>active(i,snap)&&!i.planned_date)){setBusy('IA organizando as datas do mês…');await journeyApi('companies/'+companyId+'/calendar/plan-dates',{requestId:crypto.randomUUID(),month});snap=await load();}if(stop.current)return;if(snap.items.some(i=>active(i,snap)&&!i.details&&i.planned_date?.startsWith(month))){setBusy('Estrategista detalhando as publicações…');await journeyApi('companies/'+companyId+'/calendar/generate',{requestId:crypto.randomUUID()});snap=await load();}if(!design)return;const tasks=snap.items.filter(i=>active(i,snap)&&i.planned_date?.startsWith(month)&&i.details&&i.format!=='video').flatMap(i=>Array.from({length:i.format==='carrossel'?i.details!.slides.length:1},(_,frame)=>({item:i,frame}))).filter(t=>!snap.assets.some(a=>a.item_id===t.item.id&&a.revision===t.item.revision&&a.frame===t.frame));for(let n=0;n<tasks.length;n++){if(stop.current)break;const t=tasks[n]!;setBusy('Askadia Image 1.0 criando arte '+(n+1)+' de '+tasks.length+' · '+t.item.idea);await journeyApi('companies/'+companyId+'/calendar/design',{requestId:crypto.randomUUID(),id:t.item.id,frame:t.frame,materials:selectedMaterials});await load();}}catch(e){setError((e instanceof Error?e.message:'Geração interrompida.')+' As peças já concluídas estão salvas. Ao retomar, somente as que faltam serão geradas.');}finally{lock.current=false;setBusy('');}}
 const first=new Date(month+'-01T12:00:00'),offset=(first.getDay()+6)%7,totalDays=new Date(first.getFullYear(),first.getMonth()+1,0).getDate();const cells=Array.from({length:Math.ceil((offset+totalDays)/7)*7},(_,n)=>n-offset+1);const shown=day==='sem-data'?items.filter(i=>!i.planned_date):items.filter(i=>i.planned_date===day);
 return <section className={styles.moduleCard}><div className={styles.cardHeading}><div><h2>{day?(day==='sem-data'?'Publicações sem data':new Date(day+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})):'Calendário editorial'}</h2><p>Planejar → criar → revisar → aprovar → programar.</p></div>{day?<Link href={'/empresa/'+companyId+'/conteudo'}>Voltar ao calendário</Link>:<Link href={'/empresa/'+companyId+'/estrategia'}>Ver estratégia</Link>}</div>{error&&<p className="form-error" role="alert">{error}</p>}{busy&&<div role="status"><p>{busy}</p><Button size="small" variant="outline" onClick={()=>{stop.current=true;setBusy('Concluindo a peça atual para pausar…');}}>Pausar após esta peça</Button></div>}
 {data&&<><details className={styles.moduleCard}><summary>Identidade e referências do designer ({selectedMaterials.length})</summary><p>Selecione até 5 imagens: logo, fotos reais e referências. O designer usa os materiais selecionados, a identidade confirmada e o briefing do estrategista em cada arte.</p>{data.materials.map(m=><label style={{display:'block',marginBottom:10}} key={m.id}><input type="checkbox" checked={selectedMaterials.includes(m.id)} disabled={!!busy||(!selectedMaterials.includes(m.id)&&selectedMaterials.length>=5)} onChange={e=>setSelectedMaterials(v=>e.target.checked?[...v,m.id]:v.filter(id=>id!==m.id))}/> {m.name}</label>)}<Link href={'/empresa/'+companyId+'/perfil'}>Enviar ou revisar materiais</Link></details>
 {!day?<><div className={styles.calendarToolbar}><label>Mês<input type="month" value={month} disabled={!!busy} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label>{write&&<Button disabled={!!busy||!items.length} onClick={()=>void generateMonth()}>Gerar textos e roteiros do mês</Button>}{write&&items.some(i=>i.details)&&<Button variant="outline" disabled={!!busy||items.some(i=>!i.details)} onClick={()=>void generateMonth(true)}>Criar designs · Askadia Image 1.0</Button>}{write&&pendingDates&&<Button variant="outline" disabled={!!busy} onClick={()=>void action('plan-dates',{requestId:crypto.randomUUID(),month},'IA distribuindo as publicações no calendário…')}>Organizar datas com IA</Button>}</div><p>{items.filter(i=>i.planned_date?.startsWith(month)).length} publicação(ões) neste mês. A geração preserva peças prontas; vídeos recebem roteiro e aguardam o arquivo final.</p><div className={styles.monthGrid}>{['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(d=><div className={styles.weekday} key={d}>{d}</div>)}{cells.map((n,index)=>{if(n<1||n>totalDays)return <div className={styles.calendarBlank} key={'blank'+index}/>;const date=month+'-'+String(n).padStart(2,'0'),posts=items.filter(i=>i.planned_date===date);return <Link className={styles.calendarDay} href={'/empresa/'+companyId+'/conteudo/'+date} key={date} aria-label={n+' · '+posts.length+' publicações'}><span>{n}</span>{posts.map(i=>{const a=data.assets.find(a=>a.item_id===i.id&&a.revision===i.revision&&a.frame===0);return <div className={styles.monthPost} key={i.id}>{a?<img alt="Miniatura do criativo" src={'/api/onboarding/companies/'+companyId+'/creatives/'+a.id}/>:<span className={styles.thumbnail}>{i.format==='video'?'▶':'✦'}</span>}<strong>{i.details?.title??i.idea}</strong><small>{i.status==='approved'?'Aprovada':i.format==='video'?'Vídeo':'Em produção'}</small></div>;})}</Link>;})}</div>{pendingDates&&<p><Link href={'/empresa/'+companyId+'/conteudo/sem-data'}>{items.filter(i=>!i.planned_date).length} publicação(ões) aguardam datas → organizar com IA ou ajustar individualmente</Link></p>}{!items.length&&<p>Aprove a estratégia para trazer as ideias para este calendário.</p>}</>:<><p>{shown.length} publicação(ões). Abra os detalhes, revise a legenda, confira o criativo e aprove a versão final.</p><div className={styles.dayPosts}>{shown.map(item=><CalendarPost key={item.id+':'+item.revision} item={item} assets={data.assets.filter(a=>a.item_id===item.id&&a.revision===item.revision)} videos={data.videos.filter(v=>v.item_id===item.id&&v.revision===item.revision)} companyId={companyId} current={active(item)} write={write} approve={approve} busy={!!busy} action={action} reload={load}/>)}</div></>}
 </>}<p className={styles.provider}>Datas no calendário representam o planejamento. Publicar exige aprovação da peça final e autorização do canal Meta.</p></section>;
}
function CalendarPost({item,assets,videos,reload,companyId,current,write,approve,busy,action}:{item:CalendarItem;assets:CreativeAsset[];videos:FinalVideo[];reload:()=>Promise<Snapshot>;companyId:string;current:boolean;write:boolean;approve:boolean;busy:boolean;action:(path:string,body:unknown,label:string)=>Promise<boolean>}){
 const [editing,setEditing]=useState(false),[draft,setDraft]=useState<DetailedPost|null>(item.details),[date,setDate]=useState(item.planned_date??'');
 const [uploading,setUploading]=useState(false),[fileError,setFileError]=useState(''),[videoUrl,setVideoUrl]=useState('');
 async function uploadVideo(file:File){if(file.size>50*1024*1024){setFileError('Use um MP4 de até 50 MB.');return;}setUploading(true);setFileError('');try{const r=await fetch('/api/onboarding/companies/'+companyId+'/calendar/video/'+item.id+'/'+crypto.randomUUID(),{method:'POST',headers:{'Content-Type':'video/mp4','X-File-Name':encodeURIComponent(file.name),'X-Revision':String(item.revision)},body:file});const body=await r.json();if(!r.ok)throw new Error(body.message??'Falha no envio.');await reload();}catch(e){setFileError(e instanceof Error?e.message:'Falha no envio.');}finally{setUploading(false);}}
 const frames=item.format==='carrossel'?item.details?.slides.length??0:1;const completeMedia=item.format==='video'?videos.length>0:Array.from({length:frames},(_,f)=>assets.some(a=>a.frame===f)).every(Boolean)&&frames>0;
 return <article className={styles.calendarPost}><small>#{item.position} · {item.format} · {current?'Estratégia atual':'Versão anterior'} · v{item.revision}</small><h4>{item.idea}</h4><p>{item.planned_date??'Data a definir'}</p>{current&&write&&<form className="form" onSubmit={e=>{e.preventDefault();void action('date',{id:item.id,revision:item.revision,date},'Atualizando data…');}}><label>Data da publicação<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><Button size="small" variant="outline" disabled={busy||date===item.planned_date||!date}>Ajustar data</Button></form>}<span className="tag">{item.status==='approved'?'Peça aprovada':item.details?'Em produção':'Aguardando detalhamento'}</span>
 {!item.details?<p>O conteúdo será desenvolvido a partir desta ideia e da direção aprovada.</p>:<details open><summary>Texto e orientação criativa</summary>{editing&&draft?<form className="form" onSubmit={async e=>{e.preventDefault();if(await action('edit',{id:item.id,revision:item.revision,details:draft,date:date||null},'Salvando nova versão do conteúdo…'))setEditing(false);}}><label>Data proposta<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{(['title','caption','cta','designBrief','videoScript'] as const).map(key=><label key={key}>{{title:'Título',caption:'Legenda',cta:'Chamada para ação',designBrief:'Briefing para o designer',videoScript:'Roteiro de vídeo'}[key]}<textarea rows={key==='caption'||key==='designBrief'?5:2} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})} maxLength={key==='caption'?2200:key==='designBrief'?4000:key==='videoScript'?6000:key==='title'?300:500}/></label>)}{draft.slides.map((slide,index)=><div key={index}><label>Texto do slide {index+1}<textarea value={slide.text} maxLength={500} onChange={e=>setDraft({...draft,slides:draft.slides.map((s,i)=>i===index?{...s,text:e.target.value}:s)})}/></label><label>Visual do slide {index+1}<textarea value={slide.visual} maxLength={1500} onChange={e=>setDraft({...draft,slides:draft.slides.map((s,i)=>i===index?{...s,visual:e.target.value}:s)})}/></label></div>)}<Button disabled={busy} type="submit">Salvar nova versão</Button><Button type="button" variant="ghost" onClick={()=>setEditing(false)}>Cancelar</Button><p>Editar invalida a aprovação e exige criativos para a nova versão.</p></form>:<><h5>{item.details.title}</h5><p className={styles.preserveText}>{item.details.caption}</p><p>{item.details.cta}</p><p>{item.details.hashtags.join(' ')}</p><h5>Briefing do designer</h5><p className={styles.preserveText}>{item.details.designBrief}</p>{item.details.slides.map((s,i)=><div key={i}><h5>Slide {i+1}</h5><p>{s.text}</p><p>{s.visual}</p></div>)}{item.details.videoScript&&<><h5>Roteiro e edição</h5><p className={styles.preserveText}>{item.details.videoScript}</p></>}{item.details.clientMaterials.length>0&&<><h5>Materiais do cliente</h5><ul>{item.details.clientMaterials.map((s,i)=><li key={i}>{s}</li>)}</ul></>}{item.details.unknowns.length>0&&<><h5>Informações a confirmar</h5><ul>{item.details.unknowns.map((s,i)=><li key={i}>{s}</li>)}</ul></>}{current&&write&&<Button variant="outline" disabled={busy} onClick={()=>{setDraft(item.details);setDate(item.planned_date??'');setEditing(true);}}>Editar conteúdo e data</Button>}</>}</details>}
 {item.details&&<div className={styles.creativeList}>{item.format==='video'?<div>{videos.map(v=><Button key={v.id} variant="outline" size="small" onClick={async()=>{try{const r=await journeyApi<{url:string}>('companies/'+companyId+'/videos/'+v.id);setVideoUrl(r.url);}catch(e){setFileError(e instanceof Error?e.message:'Vídeo indisponível.');}}}>Ver vídeo final · {v.name}</Button>)}{videoUrl&&<video controls src={videoUrl} style={{width:'100%',maxHeight:480}}/>}{write&&current&&<label className="form">{uploading?'Enviando vídeo…':'Enviar vídeo editado (MP4, até 50 MB)'}<input type="file" accept="video/mp4,.mp4" disabled={busy||uploading} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadVideo(file);e.target.value='';}}/></label>}<p>Ao substituir o vídeo, a aprovação anterior é invalidada. Revise o arquivo final antes de aprovar.</p>{fileError&&<p className="form-error" role="alert">{fileError}</p>}</div>:Array.from({length:frames},(_,frame)=>{const asset=assets.find(a=>a.frame===frame);return <div key={frame}><p>{frames>1?'Slide '+(frame+1):'Criativo da publicação'}</p>{asset&&<><img alt="Criativo gerado para esta publicação" style={{width:'100%',maxHeight:540,objectFit:'contain',borderRadius:12}} src={'/api/onboarding/companies/'+companyId+'/creatives/'+asset.id}/><a href={'/api/onboarding/companies/'+companyId+'/creatives/'+asset.id} target="_blank" rel="noreferrer">Abrir criativo · {asset.model}</a></>}{current&&write&&<Button variant="outline" disabled={busy} onClick={()=>void action('design',{requestId:crypto.randomUUID(),id:item.id,frame},'Designer criando a arte a partir do briefing aprovado…')}>{asset?'Gerar nova opção':'Criar design · Askadia Image 1.0'}</Button>}</div>;})}</div>}
 {current&&approve&&item.status!=='approved'&&<Button disabled={busy||uploading||!completeMedia} onClick={()=>void action('approve',{id:item.id,revision:item.revision},'Registrando aprovação da peça…')}>Aprovar peça final</Button>}
 </article>;
}
