'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {Button} from '@askadia/ui';
import type {OnboardingState,ProfileFacts} from '@askadia/contracts';
import {journeyApi} from '../lib/journey-api';
import {ProfileSummary} from './onboarding-chat';
export function FollowupPanel({sessionId}:{sessionId:string}){
 type Context={profile:OnboardingState|null;confirmedProfile:{version:number;facts:ProfileFacts}|null;meetings:{id:string;meeting_date:string;participants:string;decisions:string;next_actions:string}[]};
 const [data,setData]=useState<Context|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[expanded,setExpanded]=useState(false);
 useEffect(()=>{const c=new AbortController();journeyApi<Context>('access/'+sessionId,undefined,c.signal).then(r=>{if(!c.signal.aborted)setData(r);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[sessionId]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget,fields=new FormData(form);setBusy(true);setError('');try{await journeyApi('access/'+sessionId+'/meetings',{requestId:crypto.randomUUID(),date:new Date(String(fields.get('date'))+'T12:00:00Z').toISOString(),participants:String(fields.get('participants')),decisions:String(fields.get('decisions')),nextActions:String(fields.get('nextActions'))});setData(await journeyApi<Context>('access/'+sessionId));form.reset();}catch(e){setError(e instanceof Error?e.message:'Não foi possível registrar.');}finally{setBusy(false);}}
 return <section className="panel" style={{padding:26,marginTop:24}}><h2>Perfil e acompanhamento</h2>{error&&<p className="form-error" role="alert">{error}</p>}{data&&<><p>{data.confirmedProfile?'Perfil confirmado · versão '+data.confirmedProfile.version:'O cliente ainda está apresentando a empresa.'}</p><Button variant="outline" onClick={()=>setExpanded(v=>!v)}>{expanded?'Recolher perfil':'Consultar perfil'}</Button>{expanded&&<ProfileSummary facts={data.confirmedProfile?.facts??data.profile?.facts??{}}/>}<h3 style={{marginTop:25}}>Registrar encontro com o cliente</h3><p>Registre a participação, as decisões e quem fará cada próxima ação. Isso não aprova publicação nem orçamento.</p><form className="form" onSubmit={save}><fieldset disabled={busy}><label>Data do encontro<input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Participantes, incluindo o cliente<input name="participants" required minLength={2} maxLength={1000}/></label><label>Decisões tomadas<textarea name="decisions" required minLength={2} maxLength={6000} rows={3}/></label><label>Próximas ações, responsáveis e prazos<textarea name="nextActions" required minLength={2} maxLength={6000} rows={3}/></label><Button type="submit">{busy?'Registrando…':'Registrar encontro'}</Button></fieldset></form>{data.meetings.map(m=><article key={m.id} style={{padding:'22px 0',borderTop:'1px solid #e4e6eb'}}><h3>{m.meeting_date.split('-').reverse().join('/')}</h3><p><strong>Participantes: </strong>{m.participants}</p><p style={{whiteSpace:'pre-wrap'}}><strong>Decisões: </strong>{m.decisions}</p><p style={{whiteSpace:'pre-wrap'}}><strong>Próximas ações: </strong>{m.next_actions}</p></article>)}</>}</section>;
}
