'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {Button} from '@askadia/ui';
import {Check,ArrowRight,MousePointer2} from 'lucide-react';
import type {OnboardingSnapshot,LaunchRecommendations,InstagramWatch} from '@askadia/contracts';
import {StrategyWorkspace} from './strategy-workspace';
import {InstagramProfiles} from './instagram-profiles';
import {journeyApi} from '../lib/journey-api';
import styles from './guided-strategy.module.css';
export type JourneyStage={stage:number;basis:string;approved:boolean;approvedAt:string|null;data:unknown};
export type MarketingJourney={profileVersion:number;confirmed:boolean;canApprove:boolean;competitorReview?:{basis:string;watches:InstagramWatch[]};stages:JourneyStage[]};
const titles=['Concorrentes e análise','Diagnóstico e planos','Publicações e datas','Relacionamento e vendas','Tráfego pago'];
const instructions=['Confira os perfis e os dados coletados. Depois, aprove a análise que orientará o diagnóstico.','Leia o diagnóstico e os planos macro, de médio e curto prazo. Peça ajustes ou aprove para continuar.','Revise os temas, formatos e datas. A aprovação libera este calendário para a produção após concluir as cinco etapas.','Confira as sugestões de atendimento e de campanhas para alunos e novos clientes.','Revise as propostas de aquisição. Depois das cinco aprovações, a Askadia prepara as entregas.'];
type PlanItem={id:string;date:string|null;idea:string;direction:string;format:string};
export function GuidedStrategy({companyId,data,write,approve,compact=false,onComplete}:{companyId:string;data:OnboardingSnapshot|null;write:boolean;approve:boolean;compact?:boolean;onComplete?:()=>void}){
 const [journey,setJourney]=useState<MarketingJourney|null>(null),[selected,setSelected]=useState<number|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[limitations,setLimitations]=useState('');const base='companies/'+companyId;
 const load=useCallback(async(signal?:AbortSignal)=>{const value=await journeyApi<MarketingJourney>(base+'/launch/journey',undefined,signal);if(!signal?.aborted)setJourney(value);},[base]);
 useEffect(()=>{const c=new AbortController();let timer:ReturnType<typeof setTimeout>;async function refresh(){try{await load(c.signal);}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Não foi possível carregar as etapas.');}finally{if(!c.signal.aborted)timer=setTimeout(()=>void refresh(),7000);}}void refresh();return()=>{c.abort();clearTimeout(timer);};},[load]);
 const current=journey?.stages.find(s=>!s.approved)?.stage??5;const active=selected??current;const stage=journey?.stages.find(s=>s.stage===active);const previousApproved=journey?.stages.filter(s=>s.stage<active).every(s=>s.approved);
 async function accept(){if(busy||!stage)return;setBusy(true);setError('');try{await journeyApi(base+'/launch/approve',{stage:active,basis:stage.basis,limitations:active===1?limitations:'',...(active===1?{evidenceBasis:journey?.competitorReview?.basis}:{})});setSelected(null);await load();if(active===5){if(onComplete)onComplete();else window.location.assign('/empresa/'+companyId+'/preparacao');}}catch(e){setError(e instanceof Error?e.message:'Não foi possível aprovar.');await load().catch(()=>{});}finally{setBusy(false);}}
 return <section className={compact?`${styles.root} ${styles.compact}`:styles.root}><header><p className="page-eyebrow">ESTRATÉGIA GUIADA</p><h2>{compact?'Revise sua estratégia, etapa por etapa.':'Você decide. A Askadia executa o que foi aprovado.'}</h2><p>Cinco etapas para alinhar seu marketing. Cada proposta fica vinculada ao perfil e à versão que você revisou.</p></header>{error&&<p className="error-banner" role="alert">{error}</p>}
 {!journey&&<p role="status">Carregando seu plano…</p>}{journey&&!journey.confirmed&&<p>Primeiro, <Link href={'/empresa/'+companyId+'/onboarding'}>conclua o onboarding</Link>.</p>}
 {journey?.confirmed&&<><ol className={styles.steps} aria-label="Etapas da estratégia">{titles.map((title,i)=><li key={title}><button disabled={i+1>current} aria-current={active===i+1?'step':undefined} onClick={()=>setSelected(i+1)}><span>{journey.stages[i]?.approved?<Check size={17}/>:i+1}</span>{title}</button></li>)}</ol>
 <aside className={styles.guide}><MousePointer2 size={24}/><div><strong>Seu próximo clique · etapa {active}</strong><p>{instructions[active-1]}</p><a href="#approve-stage">Ir para a aprovação desta etapa ↓</a></div></aside>
 {active===1&&<><InstagramProfiles companyId={companyId} reviewWatches={journey.competitorReview?.watches} onChanged={()=>load()}/><div className={styles.limitations}><h3>Análise de concorrentes</h3><p>Compare seguidores, interações públicas e amostra de posts acima. O diagnóstico usará uma cópia desses dados com a data da coleta. Dados indisponíveis serão tratados como lacunas.</p><label>Se ainda faltam dados, registre a limitação antes de continuar<textarea value={limitations} onChange={e=>setLimitations(e.target.value)} maxLength={1000} placeholder="Ex.: o concorrente usa conta pessoal e suas métricas não estão disponíveis. Quero continuar com essa limitação registrada."/></label></div></>}
 {active===2&&<>{stage?.data&&(stage.data as {analysisCurrent?:boolean}).analysisCurrent===false&&<p className="info-note">A análise de concorrentes mudou. Use Pedir para refazer abaixo para atualizar o diagnóstico antes de aprovar.</p>}<StrategyWorkspace companyId={companyId} data={data} write={write} approve={approve} guided/></>}
 {active===3&&<section className={styles.panel}><h3>Seu calendário proposto</h3><p>As primeiras datas precisam estar a pelo menos sete dias de hoje. Depois de aprovado, o sistema prepara os criativos na semana anterior e solicita a aprovação de cada peça.</p>{Array.isArray(stage?.data)&&stage.data.length>0?<div className={styles.calendar}>{(stage.data as PlanItem[]).map(i=><article key={i.id}><small>{i.date?new Date(i.date+'T12:00:00').toLocaleDateString('pt-BR'):'Data pendente'} · {i.format}</small><h4>{i.idea}</h4><p>{i.direction}</p></article>)}</div>:<p role="status">Organizando os temas e as datas a partir da estratégia…</p>}<Link href={'/empresa/'+companyId+'/conteudo'}>Ajustar datas no calendário →</Link>{onComplete&&<p>Depois do ajuste, use Voltar à configuração para continuar por aqui.</p>}</section>}
 {active===4&&<section className={styles.panel}><h3>Campanhas de relacionamento e vendas</h3><p>As sugestões definem a direção. Para envio, a aprovação da campanha deve conter público elegível, texto e programação.</p>{stage?.data?<><SuggestionList title="Atendimento no WhatsApp" items={(stage.data as Pick<LaunchRecommendations,'whatsapp'|'messages'>).whatsapp}/><SuggestionList title="Campanhas de mensagens" items={(stage.data as Pick<LaunchRecommendations,'whatsapp'|'messages'>).messages}/></>:<p role="status">Preparando as sugestões com base no plano aprovado…</p>}</section>}
 {active===5&&<section className={styles.panel}><h3>Aquisição com tráfego pago</h3><p>A programação deverá respeitar o orçamento, público e criativos aprovados. A Askadia prepara as campanhas nos formatos disponíveis. Após a aprovação final de orçamento, público, criativos e programação, a execução depende das contas conectadas e da disponibilidade de saldo.</p>{stage?.data?<SuggestionList title="Propostas de campanhas" items={stage.data as LaunchRecommendations['traffic']}/>:<p role="status">Preparando as sugestões de aquisição…</p>}</section>}
 <section id="approve-stage" className={styles.approval}><div><strong>{stage?.approved?'Esta versão foi aprovada':'Sua aprovação é o próximo passo'}</strong><p>{active===3?'Você aprova ideias e datas agora. Cada criativo terá outra revisão antes de ser publicado.':active>=4?'Aprovação da direção proposta. Pendências de público, verba, criativo e conexão continuam visíveis na campanha antes de autorizar a execução.':'Leia a proposta e confira se está alinhada ao seu negócio.'}</p></div>{journey.canApprove&&<Button disabled={busy||!previousApproved||stage?.approved||(active>1&&!stage?.data)} onClick={()=>void accept()}>{busy?'Registrando…':active===5?'Aprovar plano e preparar entregas':'Aprovar e continuar'}<ArrowRight size={17}/></Button>}{stage?.approved&&active<5&&<Button variant="outline" onClick={()=>setSelected(active+1)}>Ver próxima etapa</Button>}{journey.stages.every(s=>s.approved)&&(onComplete?<Button onClick={onComplete}>Entrar na Askadia<ArrowRight size={17}/></Button>:<Link className="button button-primary" href={'/empresa/'+companyId+'/preparacao'}>Acompanhar entregas</Link>)}</section></>}
 </section>;
}
function SuggestionList({title,items}:{title:string;items:LaunchRecommendations['traffic']}){return <section><h4>{title}</h4>{items?.map((s,i)=><article className={styles.suggestion} key={i}><h4>{s.title}</h4><p>{s.objective}</p><p><strong>Público:</strong> {s.audience}</p><ol>{s.steps.map((step,n)=><li key={n}>{step}</li>)}</ol>{s.message&&<blockquote>{s.message}</blockquote>}<p><strong>Como acompanhar:</strong> {s.successMetric}</p>{s.requirements.length>0&&<><strong>Pendências para executar</strong><ul>{s.requirements.map((r,n)=><li key={n}>{r}</li>)}</ul></>}</article>)}</section>;}
