'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Button} from '@askadia/ui';
import {instagramEngagement,type InstagramCandidate,type InstagramWatch} from '@askadia/contracts';
import {journeyApi} from '../lib/journey-api';
import styles from './journey.module.css';
type Data={watches:InstagramWatch[];canEdit:boolean;monitoringAvailable:boolean;searchAvailable:boolean};
export function InstagramProfiles({companyId,initialQuery='',onboarding=false,manualOnly=false,reviewWatches,onChanged}:{companyId:string;initialQuery?:string;onboarding?:boolean;manualOnly?:boolean;reviewWatches?:InstagramWatch[];onChanged?:()=>Promise<void>}){
 const [data,setData]=useState<Data|null>(null),[query,setQuery]=useState(initialQuery.slice(0,300)),[profile,setProfile]=useState(''),[kind,setKind]=useState<'local'|'inspiration'>('local'),[candidates,setCandidates]=useState<InstagramCandidate[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[searched,setSearched]=useState(false);const lock=useRef(false),auto=useRef(false);
 const base='companies/'+companyId+'/instagram';
 const load=useCallback(async(signal?:AbortSignal)=>{const d=await journeyApi<Data>(base,undefined,signal);if(!signal?.aborted)setData(d);},[base]);
 useEffect(()=>{const c=new AbortController();let timer:ReturnType<typeof setTimeout>;async function refresh(){try{await load(c.signal);}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Não foi possível consultar os perfis.');}finally{if(!c.signal.aborted)timer=setTimeout(()=>void refresh(),15000);}}void refresh();return()=>{c.abort();clearTimeout(timer);};},[load]);
 const search=useCallback(async(value:string,local:boolean)=>{if(lock.current||value.trim().length<2)return;lock.current=true;setBusy(true);setError('');setCandidates([]);setSearched(false);try{const r=await journeyApi<{profiles:InstagramCandidate[]}>(base+'/search',{requestId:crypto.randomUUID(),query:value,local});setCandidates(r.profiles);setSearched(true);}catch(e){setError(e instanceof Error?e.message:'Busca indisponível.');}finally{lock.current=false;setBusy(false);}},[base]);
 useEffect(()=>{if(manualOnly||!onboarding||!data?.canEdit||!data.searchAvailable||!initialQuery.trim()||auto.current)return;auto.current=true;const key='askadia-instagram-search:'+companyId+':'+initialQuery;try{if(sessionStorage.getItem(key))return;sessionStorage.setItem(key,'1');}catch{/* Search remains usable without browser storage. */}void search(initialQuery.slice(0,300),true);},[manualOnly,onboarding,data?.canEdit,data?.searchAvailable,initialQuery,companyId,search]);
 async function select(username:string,label:string,category:'local'|'inspiration',remove=false){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await journeyApi(base+'/select',{profile:username,label:label.slice(0,160),kind:category,remove});setProfile('');await load();await onChanged?.();}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar o perfil.');}finally{lock.current=false;setBusy(false);}}
 return <section className={styles.moduleCard}><h2>{onboarding?'Encontre os concorrentes no Instagram':'Concorrentes e referências no Instagram'}</h2><p>Confirme os perfis correspondentes aos concorrentes locais e às marcas que inspiram sua comunicação. Nomes parecidos precisam de conferência.</p>{error&&<p role="alert" className="error-banner">{error}</p>}{data?.canEdit&&<><form className="form" onSubmit={e=>{e.preventDefault();void search(query,kind==='local');}}><label>Tipo de referência<select value={kind} onChange={e=>{setKind(e.target.value as typeof kind);setCandidates([]);setSearched(false);setQuery('');}}><option value="local">Concorrente local</option><option value="inspiration">Marca de inspiração</option></select></label><label>Nome do negócio<input value={query} onChange={e=>setQuery(e.target.value)} maxLength={300} placeholder="Nome da academia ou marca"/></label><Button type="submit" variant="outline" disabled={manualOnly||busy||query.trim().length<2||!data.searchAvailable}>{busy?'Consultando…':'Buscar perfis'}</Button></form>{manualOnly&&<p>A busca com IA será liberada após confirmar o plano. Você já pode adicionar os perfis conhecidos abaixo.</p>}{searched&&!candidates.length&&<p role="status">Não encontramos um perfil verificável. Você pode informar o @ abaixo.</p>}<div className={styles.overview}>{candidates.map(c=><article className={styles.moduleCard} key={c.username}><h3>{c.name}</h3><a href={c.url} target="_blank" rel="noreferrer">@{c.username} ↗</a><p>{c.context}</p><Button disabled={busy||(reviewWatches??data.watches).some(w=>w.username===c.username)} variant="outline" onClick={()=>void select(c.username,c.name,kind)}>Confirmei, acompanhar perfil</Button></article>)}</div><form className="form" onSubmit={e=>{e.preventDefault();void select(profile,query.trim()||profile,kind);}}><label>Já sabe o perfil?<input value={profile} onChange={e=>setProfile(e.target.value)} maxLength={2000} placeholder="@academia ou https://instagram.com/academia/"/></label><Button disabled={busy||!profile.trim()} type="submit" variant="outline">Adicionar perfil confirmado</Button></form></>}
 <p className="info-note">{data?.monitoringAvailable?'Coleta programada aproximadamente a cada hora, sujeita ao acesso e aos limites da Meta.':'A coleta automática ainda não está disponível para esta conta.'} Somente perfis profissionais acessíveis pela API. Curtidas e comentários públicos não revelam alcance, salvamentos ou vendas.</p>
 <div className={styles.overview}>{(reviewWatches??data?.watches)?.map(w=>{const s=w.snapshot,m=s?instagramEngagement(s):null;const growth=s?.followers!=null&&w.previous?.followers!=null?s.followers-w.previous.followers:null;return <article key={w.id} className={styles.moduleCard}><small>{w.kind==='local'?'CONCORRENTE LOCAL':'INSPIRAÇÃO'}</small><h3>{w.label}</h3><a href={'https://www.instagram.com/'+w.username+'/'} target="_blank" rel="noreferrer">@{w.username} ↗</a>{s&&m?<><p><strong>{s.followers?.toLocaleString('pt-BR')??'Indisponível'}</strong> seguidores{growth!==null?' · '+(growth>=0?'+':'')+growth+' desde a coleta anterior':''}</p><p>Interações por seguidores: <strong>{m.engagementPercent===null?'Indisponível':m.engagementPercent.toFixed(2)+'%'}</strong></p><p><small>Média de curtidas + comentários ÷ seguidores. {m.measuredPosts} posts com contagem completa entre {m.sampleSize} posts retornados (até 25 recentes). Não é taxa por alcance.</small></p><p><small>Coletado em {new Date(s.collectedAt).toLocaleString('pt-BR')}{w.previous?' · comparação com '+new Date(w.previous.collectedAt).toLocaleString('pt-BR'):''}</small></p></>:<p>{w.status==='running'?'Consultando perfil…':'Aguardando primeira coleta.'}</p>}{w.error&&<p className="info-note">{w.error}</p>}<p><a href={'https://www.facebook.com/ads/library/?active_status=active&ad_type=all&country=BR&q='+encodeURIComponent(w.label)+'&search_type=keyword_unordered'} target="_blank" rel="noreferrer">Consultar anúncios na Biblioteca Meta ↗</a></p><small>Consulta manual. A API não cobre todos os anúncios comerciais brasileiros; nenhum resultado de anúncios é presumido.</small>{data?.canEdit&&<p><Button disabled={busy} variant="ghost" onClick={()=>void select(w.username,w.label,w.kind,true)}>Remover acompanhamento</Button></p>}</article>;})}</div>{data&&!(reviewWatches??data.watches).length&&<p>Nenhum perfil selecionado.</p>}</section>;
}
