'use client';
import Link from 'next/link';
import {PlacesMap} from './places-map';
import { useCallback,useEffect,useRef,useState } from 'react';
import { ArrowUp,Paperclip,Check,MapPin,RefreshCw } from 'lucide-react';
import { Button } from '@askadia/ui';
import { essentialKeys,interviewKeys,labels,missingEssentials,profileKeys,type FactInput,type OnboardingSnapshot,type PlaceSearchResult,type ProfileKey,type ProfileFacts,type onboardingActions } from '@askadia/contracts';
import { journeyApi,JourneyError } from '../lib/journey-api';
import styles from './journey.module.css';
export function OnboardingChat({companyId,readOnly=false,summaryOnly=false}:{companyId:string;readOnly?:boolean;summaryOnly?:boolean}){
 const [uploadProgress,setUploadProgress]=useState('');
 const [mapView,setMapView]=useState(true),[radius,setRadius]=useState(3000);
 const [data,setData]=useState<OnboardingSnapshot|null>(null),[text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState<PlaceSearchResult|null>(null),[searching,setSearching]=useState(false),[selected,setSelected]=useState<string[]>([]),[showSummary,setShowSummary]=useState(summaryOnly);
 const [website,setWebsite]=useState(''),[websiteResult,setWebsiteResult]=useState<{message:string;facts:{key:ProfileKey;value:string;source:string}[]}|null>(null),[readingWebsite,setReadingWebsite]=useState(false);
 const alive=useRef(true),lock=useRef(false),lastStep=useRef(''),end=useRef<HTMLDivElement>(null),pending=useRef<{fingerprint:string;requestId:string}|null>(null);
 const load=useCallback(async(signal?:AbortSignal)=>{const r=await journeyApi<OnboardingSnapshot>('companies/'+companyId,undefined,signal);if(!signal?.aborted&&alive.current)setData(r);},[companyId]);
 useEffect(()=>{alive.current=true;const c=new AbortController();load(c.signal).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>{alive.current=false;c.abort();};},[load]);
 useEffect(()=>{if(!data)return;if(lastStep.current!==data.step){setSearch(null);setSelected([]);lastStep.current=data.step;}end.current?.scrollIntoView({block:'nearest',behavior:'smooth'});},[data]);
 async function send(message:string,action:typeof onboardingActions[number]='reply',answers:Partial<Record<ProfileKey,FactInput>>={}){
  if(!data||lock.current||readOnly)return false;lock.current=true;setBusy(true);setError('');
  const fingerprint=JSON.stringify({companyId,revision:data.state.revision,message,action,answers});if(pending.current?.fingerprint!==fingerprint)pending.current={fingerprint,requestId:crypto.randomUUID()};
  try{const r=await journeyApi<OnboardingSnapshot>('companies/'+companyId+'/answers',{requestId:pending.current.requestId,revision:data.state.revision,message,action,answers});if(!alive.current)return false;setData(r);setText('');if(action==='reopen')setShowSummary(false);pending.current=null;if(action==='confirm')window.location.assign('/empresa/'+companyId+'/conteudo');return true;}
  catch(e){if(!alive.current)return false;if(e instanceof JourneyError&&e.status===409){try{await load();}catch{/* Keep the original conflict and the user's correction visible. */}pending.current=null;}setError(e instanceof Error?e.message:'Não foi possível salvar. Sua resposta continua no campo.');return false;}finally{lock.current=false;if(alive.current)setBusy(false);}
 }
 async function searchPlaces(){if(!data||searching)return;const requestedStep=data.step;setSearching(true);setError('');try{const r=await journeyApi<PlaceSearchResult>('companies/'+companyId+'/places',{requestId:crypto.randomUUID(),kind:data.step==='location'?'location':'competitors',radius});if(alive.current&&lastStep.current===requestedStep){setSearch(r);setSelected([]);}}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Pesquisa indisponível.');}finally{if(alive.current)setSearching(false);}}
 async function readWebsite(){if(readingWebsite||busy)return;setReadingWebsite(true);setError('');try{const r=await journeyApi<NonNullable<typeof websiteResult>>('companies/'+companyId+'/website',{url:website,requestId:crypto.randomUUID()});if(alive.current)setWebsiteResult(r);}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Não foi possível consultar.');}finally{if(alive.current)setReadingWebsite(false);}}
 async function upload(files:File[]){if(lock.current||!files.length)return;lock.current=true;setBusy(true);setError('');const failures:string[]=[];let saved=0;try{for(const [i,file] of files.entries()){if(!alive.current)break;setUploadProgress('Enviando '+(i+1)+' de '+files.length+' · '+file.name);try{if(file.size>10485760)throw new Error('limite de 10 MB');const response=await fetch('/api/onboarding/companies/'+companyId+'/attachments/'+crypto.randomUUID(),{method:'POST',headers:{'Content-Type':file.type,'X-File-Name':encodeURIComponent(file.name)},body:file});const r=await response.json();if(!response.ok)throw new Error(r.message??'falha no envio');saved++;}catch(e){failures.push(file.name+': '+(e instanceof Error?e.message:'falha no envio'));}}if(alive.current){await load();setUploadProgress(saved+' de '+files.length+' arquivo(s) enviado(s).');if(failures.length)setError('Não enviados: '+failures.join('; '));}}catch{if(alive.current)setError('Os envios concluídos foram salvos. Atualize a página para consultar os materiais.');}finally{lock.current=false;if(alive.current)setBusy(false);}}

 if(!data)return <section className="panel internal-empty" role={error?'alert':'status'}><p>{error||'Retomando a conversa…'}</p>{error&&<Button onClick={()=>{setError('');void load().catch(e=>setError(e.message));}}>Tentar novamente</Button>}</section>;
 const stage=data.step==='complete'?5:!data.state.location_confirmed?0:!data.state.competitors_reviewed?1:!data.state.references_reviewed?2:data.step==='review'?4:3;
 const completed=interviewKeys.filter(k=>data.state.facts[k]).length;
 const optional=!essentialKeys.includes(data.step as typeof essentialKeys[number])&&data.step!=='identity';
 const canConfirm=missingEssentials(data.state.facts).length===0&&data.state.location_confirmed&&data.state.competitors_reviewed&&data.state.references_reviewed;
 return <section className={styles.onboarding}>
  {uploadProgress&&<p role="status" aria-live="polite">{uploadProgress}</p>}<header className={styles.chatHeader}><div><p className="page-eyebrow">CONHECER MINHA EMPRESA</p><h1>{data.state.facts.name?.value??'Vamos cadastrar sua empresa.'}</h1><p>Uma conversa para colocar seu marketing em movimento.</p></div><Button variant="outline" onClick={()=>setShowSummary(v=>!v)}>{showSummary?'Ver conversa':'Revisar perfil'}</Button></header>
  <ol className={styles.steps} aria-label="Etapas do cadastro">{['Localização','Concorrentes','Referências','Seu negócio','Confirmação'].map((s,i)=><li key={s} aria-current={stage===i?'step':undefined} data-done={stage>i}>{stage>i?<Check size={13}/>:i+1}<span>{s}</span></li>)}</ol>
  <p className={styles.provider} role="status">{data.provider.message}</p>
  {error&&<div className="error-banner" role="alert">{error}</div>}
  {data.state.facts.placeId?.value&&<p className={styles.provider}><a href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(data.state.facts.name?.value??'Estabelecimento')+'&query_place_id='+encodeURIComponent(data.state.facts.placeId.value)} target="_blank" rel="noreferrer">Ver local selecionado no Google Maps</a></p>}{data.state.facts.competitorPlaceIds?.value&&<div className={styles.attachments}>{data.state.facts.competitorPlaceIds.value.split('\n').map((id,i)=><a key={id} href={'https://www.google.com/maps/search/?api=1&query=Estabelecimento&query_place_id='+encodeURIComponent(id)} target="_blank" rel="noreferrer">Concorrente selecionado {i+1}</a>)}</div>}{showSummary?<ProfileSummary facts={data.state.facts} disabled={busy||readOnly} onSave={(key,fact)=>send('Atualização de '+labels[key],'edit',{[key]:fact})}/>:<div className={styles.messages} aria-label="Histórico da conversa">{data.messages.map(m=><article key={m.id} className={m.role==='user'?styles.userMessage:styles.agentMessage}><small>{m.role==='user'?'Sua empresa':'Askadia'}</small><p>{m.body}</p></article>)}<div ref={end}/></div>}
  {data.attachments.length>0&&<div className={styles.attachments}><strong>Materiais da empresa</strong>{data.attachments.map(a=><a key={a.id} href={'/api/onboarding/companies/'+companyId+'/attachments/'+a.id} target="_blank" rel="noreferrer"><Paperclip size={13}/>{a.name}</a>)}</div>}
  {data.step==='complete'&&!readOnly&&!showSummary&&<div className={styles.confirmBar}><p>O perfil está confirmado. Retome a entrevista para atualizar as informações sem perder o histórico.</p><Button disabled={busy} onClick={()=>void send('Quero atualizar as informações da empresa.','reopen')}>Refazer onboarding pela conversa <RefreshCw size={16}/></Button></div>}{!readOnly&&data.step!=='complete'&&<>
   {(data.step==='location'||data.step==='competitors')&&<div className={styles.placePanel}><div className={styles.cardHeading}><MapPin size={18}/><strong>{data.step==='location'?'Local do estabelecimento':'Concorrentes da região'}</strong><Button variant="outline" disabled={busy||searching} onClick={searchPlaces}>{searching?'Pesquisando…':'Pesquisar no Google'}</Button></div><label>Raio de pesquisa<select value={radius} disabled={searching||busy} onChange={e=>{setRadius(Number(e.target.value));setSearch(null);setSelected([]);}}>{[1000,3000,5000,10000,20000].map(r=><option key={r} value={r}>{r/1000} km</option>)}</select></label><p>Você também pode informar os dados abaixo. Não é necessário liberar sua localização pessoal.</p><p><a href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent([data.step==='location'?data.state.facts.name?.value:data.state.facts.businessType?.value,data.state.facts.city?.value,data.state.facts.address?.value?.slice(0,150)].filter(Boolean).join(' '))} target="_blank" rel="noreferrer">Abrir busca no Google Maps</a> · Abre em outra aba. Depois, informe e confirme os dados aqui.</p>
    {search&&<><p role="status">{search.message}</p>{search.status==='available'&&<><p className={styles.attribution}>Google Maps · resultados consultados agora</p>{!search.places.length&&<p>Nenhum resultado encontrado. Informe manualmente.</p>}<div className={styles.actions}><Button variant={mapView?"default":"outline"} onClick={()=>setMapView(true)}>Mapa</Button><Button variant={!mapView?"default":"outline"} onClick={()=>setMapView(false)}>Lista</Button></div>{mapView&&<PlacesMap search={search} selected={selected} disabled={busy} onSelect={id=>{if(data.step==='location'){setSelected([id]);}else setSelected(v=>v.includes(id)?v.filter(p=>p!==id):[...v,id]);}}/>}{mapView&&data.step==='location'&&selected[0]&&<Button disabled={busy} onClick={()=>void send('Local selecionado no mapa; confirmo este estabelecimento.','confirm_location',{placeId:{value:selected[0]!,status:'provided'}})}>Confirmar local selecionado: {search.places.find(p=>p.id===selected[0])?.name}</Button>}<div className={styles.places} style={{display:mapView&&search.mapKey?'none':undefined}}>{search.places.map(p=><article key={p.id}><h3>{p.name}</h3><p>{p.address}</p><a href={p.url} target="_blank" rel="noreferrer">Ver local no Google Maps</a>{p.attributions.map((a,i)=><small key={i}>{a.uri?<a href={a.uri} target="_blank" rel="noreferrer">{a.displayName}</a>:a.displayName}</small>)}{data.step==='location'?<><Button disabled={busy} variant="outline" onClick={()=>void send('Local selecionado no Google; confirmo este estabelecimento.','confirm_location',{placeId:{value:p.id,status:'provided'}})}>Confirmar este local</Button>{search.mapKey&&<iframe title={'Mapa de '+p.name} loading="lazy" referrerPolicy="no-referrer-when-downgrade" src={'https://www.google.com/maps/embed/v1/place?key='+encodeURIComponent(search.mapKey)+'&q=place_id:'+encodeURIComponent(p.id)+'&language=pt-BR'}/>}</>:<label><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,p.id]:v.filter(id=>id!==p.id))}/>É concorrente</label>}</article>)}</div></> }</>}
    {data.step==='location'&&<Button disabled={busy||(!data.state.facts.address&&!data.state.facts.city)} variant="outline" onClick={()=>void send('Confirmo manualmente a localização ou região informada.','confirm_location')}>Confirmar localização informada</Button>}
    {data.step==='competitors'&&<Button disabled={busy} variant="outline" onClick={()=>void send(search?.status==='available'?'Revisei os concorrentes selecionados.':'Continuar com pesquisa de concorrentes pendente.','review_competitors',{competitorPlaceIds:{value:selected.length?selected.join('\n'):null,status:selected.length?'provided':'deferred'},...(!data.state.facts.competitors?{competitors:{value:null,status:'deferred' as const}}:{})})}>Concluir revisão e continuar</Button>}
   </div>}
   {data.step==='channels'&&<div className={styles.placePanel}><h3>Aproveitar informações do seu site</h3><p>As sugestões só entram no perfil depois de você conferir. Se não tiver site, informe na conversa para registrar a necessidade de criação.</p><label className="form">Endereço público do site<input type="url" placeholder="https://suaempresa.com.br" value={website} onChange={e=>{setWebsite(e.target.value);setWebsiteResult(null);}} maxLength={2000}/></label><Button variant="outline" disabled={busy||readingWebsite||!website} onClick={readWebsite}>{readingWebsite?'Consultando…':'Consultar site'}</Button>{websiteResult&&<><p role="status">{websiteResult.message}</p>{websiteResult.facts.map((f,i)=><article className={styles.brief} key={i}><div><h3>{labels[f.key]}</h3><p>{f.value}</p><a href={f.source} target="_blank" rel="noreferrer">Ver fonte</a><Button disabled={busy} variant="outline" size="small" onClick={()=>void send('Conferi esta informação sugerida pelo site: '+f.source,'edit',{[f.key]:{value:f.value+'\nFonte conferida: '+f.source,status:'provided'}})}>Conferi e quero usar</Button></div></article>)}</>}</div>}
   {data.step==='references'&&<Button variant="outline" disabled={busy} onClick={()=>void send(data.state.facts.references?'Concluí a revisão das referências.':'Não tenho referências.','review_references',data.state.facts.references?{}:{references:{value:null,status:'unknown'}})}>Concluir referências e continuar</Button>}
   {!showSummary&&<form className={styles.composer} onSubmit={e=>{e.preventDefault();if(text.trim())void send(text.trim());}}><label htmlFor="onboarding-answer">{data.step==='review'?'Quais informações da empresa você quer atualizar? Conte aqui ou use Revisar perfil.':data.question}</label><textarea id="onboarding-answer" value={text} onChange={e=>setText(e.target.value)} rows={3} maxLength={6000} required disabled={busy} placeholder="Conte do seu jeito…"/><div className={styles.composerActions}><label className={styles.upload}><Paperclip size={17}/>Anexar material<input type="file" multiple accept="image/png,image/jpeg,image/webp,application/pdf" disabled={busy} onChange={e=>{const files=Array.from(e.target.files??[]);if(files.length)void upload(files);e.target.value='';}}/></label><Button type="submit" disabled={busy||!text.trim()}>{busy?'Salvando…':'Enviar'}<ArrowUp size={16}/></Button></div>{optional&&<div className={styles.quickReplies}><button type="button" disabled={busy} onClick={()=>void send('Não sei')}>Não sei</button><button type="button" disabled={busy} onClick={()=>void send('Não tenho')}>Não tenho</button><button type="button" disabled={busy} onClick={()=>void send('Responder depois')}>Responder depois</button></div>}</form>}
   {stage===3&&<p className={styles.provider}>{completed} de {interviewKeys.length} assuntos registrados. Materiais e conexões podem ficar para depois.</p>}
   {canConfirm&&<div className={styles.confirmBar}><p>{data.step==='review'?'Revise as informações acima antes de confirmar.':'O essencial já está registrado. Você pode revisar e confirmar, deixando os complementos para depois.'}</p>{showSummary||data.step==='review'?<Button disabled={busy} onClick={()=>void send('Confirmo o perfil da minha empresa para orientar os agentes.','confirm')}>Confirmar perfil<Check size={16}/></Button>:<Button variant="outline" disabled={busy} onClick={()=>setShowSummary(true)}>Revisar e concluir</Button>}</div>}
   {(data.step==='review'||showSummary)&&!canConfirm&&<p className="info-note">Ainda falta confirmar localização, concorrentes e referências, além de: {missingEssentials(data.state.facts).map(k=>labels[k]).join(', ')||'revisar as etapas da conversa'}.</p>}
  </>}
  {data.step==='complete'&&!readOnly&&<label className={styles.upload}><Paperclip size={17}/>Adicionar materiais ao perfil<input type="file" multiple accept="image/png,image/jpeg,image/webp,application/pdf" disabled={busy} onChange={e=>{const files=Array.from(e.target.files??[]);if(files.length)void upload(files);e.target.value='';}}/></label>}{data.step==='complete'&&<div className={styles.confirmBar}><div><strong>Perfil confirmado · versão {data.state.profile_version}</strong><p>Atualizações geram uma nova versão e sinalizam a revisão do planejamento.</p></div><Link className="button button-primary" href={'/empresa/'+companyId+'/conteudo'}>Acompanhar publicações</Link>{!readOnly&&<Button variant="outline" onClick={()=>void send('Quero atualizar as informações da empresa.','reopen')}><RefreshCw size={15}/>Atualizar pela conversa</Button>}</div>}
 </section>;
}
export function ProfileSummary({facts,disabled=true,onSave}:{facts:ProfileFacts;disabled?:boolean;onSave?:(key:ProfileKey,fact:FactInput)=>Promise<boolean>}){
 const [editing,setEditing]=useState<ProfileKey|null>(null),[value,setValue]=useState(''),[status,setStatus]=useState<FactInput['status']>('provided');
 return <div className={styles.summary}>{profileKeys.filter(k=>k!=='placeId'&&k!=='competitorPlaceIds').map(key=><article key={key}><div className={styles.cardHeading}><h3>{labels[key]}</h3>{!disabled&&<button onClick={()=>{setEditing(key);setValue(facts[key]?.value??'');setStatus(facts[key]?.status??'provided');}}>Corrigir</button>}</div>{editing===key?<form className="form" onSubmit={async e=>{e.preventDefault();const saved=await onSave?.(key,{value:status==='provided'?value:null,status});if(saved)setEditing(null);}}><label className="sr-only" htmlFor={'edit-'+key}>{labels[key]}</label><textarea id={'edit-'+key} value={value} onChange={e=>setValue(e.target.value)} maxLength={['name','city','businessType'].includes(key)?100:6000} required={status==='provided'} disabled={disabled||status!=='provided'}/><select aria-label={'Situação de '+labels[key]} value={status} onChange={e=>setStatus(e.target.value as FactInput['status'])}><option value="provided">Informado</option><option value="unknown">Não sei / não tenho</option><option value="deferred">Responder depois</option></select><div className="row"><Button size="small" disabled={disabled} type="submit">Salvar correção</Button><Button size="small" variant="ghost" onClick={()=>setEditing(null)} type="button">Cancelar</Button></div></form>:<><p>{facts[key]?.status==='provided'?facts[key]?.value:facts[key]?.status==='unknown'?'Declarado desconhecido ou não disponível':facts[key]?.status==='deferred'?'Responder depois':'Não informado'}</p>{facts[key]&&<small>Origem: {facts[key]?.source==='existing'?'cadastro existente':facts[key]?.source==='assistant_suggestion'?'interpretação a conferir':'informado na conversa'}</small>}</>}</article>)}</div>;
}
