'use client';
import {useEffect,useRef,useState} from 'react';
import type {PlaceSearchResult} from '@askadia/contracts';
type MapHandle={fitBounds:(bounds:unknown)=>void};
type Marker={addListener:(event:string,handler:()=>void)=>{remove:()=>void};map:MapHandle|null};
type Maps={Map:new(el:HTMLElement,options:Record<string,unknown>)=>MapHandle;Circle:new(options:Record<string,unknown>)=>{getBounds:()=>unknown;setMap:(map:null)=>void};LatLngBounds:new()=>{extend:(position:{lat:number;lng:number})=>void};marker:{AdvancedMarkerElement:new(options:Record<string,unknown>)=>Marker}};
declare global {interface Window {google?:{maps:Maps};gm_authFailure?:()=>void}}
let loading:Promise<Maps>|null=null;
let authorizationFailed=false;
function loadMaps(key:string){if(window.google?.maps.marker)return Promise.resolve(window.google.maps);if(!loading)loading=new Promise<Maps>((resolve,reject)=>{const script=document.createElement('script');const u=new URL('https://maps.googleapis.com/maps/api/js');u.search=new URLSearchParams({key,v:'weekly',libraries:'marker',language:'pt-BR'}).toString();script.src=u.href;script.async=true;script.onload=()=>window.google?.maps?resolve(window.google.maps):reject(new Error('Mapa indisponível'));script.onerror=()=>reject(new Error('Mapa indisponível'));document.head.append(script);}).catch(e=>{loading=null;throw e;});return loading;}
export function PlacesMap({search,selected,onSelect,disabled}:{search:PlaceSearchResult;selected:string[];onSelect:(id:string)=>void;disabled:boolean}){
 const container=useRef<HTMLDivElement>(null),callback=useRef(onSelect);callback.current=onSelect;const [error,setError]=useState('');
 useEffect(()=>{const fail=()=>setError('O Google bloqueou o mapa. Habilite Maps JavaScript API no projeto da chave e confira os domínios autorizados. Selecione Lista para continuar.');window.gm_authFailure=()=>{authorizationFailed=true;window.dispatchEvent(new Event('askadia-map-auth-error'));};window.addEventListener('askadia-map-auth-error',fail);if(authorizationFailed)fail();return()=>window.removeEventListener('askadia-map-auth-error',fail);},[]);
 useEffect(()=>{let canceled=false;const markers:Marker[]=[];const listeners:{remove:()=>void}[]=[];let circle:{setMap:(map:null)=>void}|undefined;setError('');if(authorizationFailed){setError('O Google bloqueou o mapa. Habilite Maps JavaScript API e recarregue a página. Selecione Lista para continuar.');return;}if(!search.mapKey){setError('Mapa interativo pendente: habilite Maps JavaScript API na chave de navegador. A seleção pela lista continua disponível.');return;}
 void loadMaps(search.mapKey).then(maps=>{if(canceled||!container.current)return;const places=search.places.filter(p=>p.latitude!==null&&p.longitude!==null);const center=search.center??(places[0]?{latitude:places[0].latitude!,longitude:places[0].longitude!}:null);if(!center){setError('Coordenadas indisponíveis. Use a lista.');return;}const map=new maps.Map(container.current,{center:{lat:center.latitude,lng:center.longitude},zoom:13,mapId:'DEMO_MAP_ID',renderingType:'RASTER',streetViewControl:false,mapTypeControl:false});const bounds=new maps.LatLngBounds();if(search.radius&&search.center){const ring=new maps.Circle({map,center:{lat:center.latitude,lng:center.longitude},radius:search.radius,strokeColor:'#30363b',strokeOpacity:0.7,strokeWeight:2,fillColor:'#667d72',fillOpacity:0.12});circle=ring;map.fitBounds(ring.getBounds());const own=document.createElement('span');own.textContent='Sua empresa';own.style.cssText='background:#25292d;color:white;padding:8px;border-radius:12px';markers.push(new maps.marker.AdvancedMarkerElement({map,position:{lat:center.latitude,lng:center.longitude},content:own,title:'Sua empresa'}));}
 for(const [i,p] of places.entries()){const pin=document.createElement('button');pin.type='button';pin.textContent=(selected.includes(p.id)?'✓ ':'')+(i+1);pin.setAttribute('aria-label',(selected.includes(p.id)?'Desmarcar ':'Selecionar ')+p.name);pin.disabled=disabled;pin.style.cssText='border:2px solid white;border-radius:50%;width:36px;height:36px;background:'+(selected.includes(p.id)?'#2c6950':'#30363b')+';color:white;font-weight:600;cursor:pointer';const position={lat:p.latitude!,lng:p.longitude!};bounds.extend(position);const marker=new maps.marker.AdvancedMarkerElement({map,position,content:pin,title:p.name,gmpClickable:true});pin.addEventListener('click',()=>{if(!disabled)callback.current(p.id);});markers.push(marker);}
 if(!search.radius)map.fitBounds(bounds);
 }).catch(()=>{if(!canceled)setError('Não foi possível carregar o mapa. Confira Maps JavaScript API, faturamento e restrição de domínio da chave. Use a lista para continuar.');});return()=>{canceled=true;listeners.forEach(l=>l.remove());markers.forEach(m=>{m.map=null;});circle?.setMap(null);};},[search,selected,disabled]);
 return <div>{error&&<p role="status">{error}</p>}<div ref={container} style={{display:error?'none':undefined,height:380,minHeight:300,borderRadius:16,overflow:'hidden',background:'#edf0f2'}} aria-label="Mapa dos estabelecimentos; selecione pelos marcadores ou pela lista"/>{!error&&search.radius&&<p>Raio de pesquisa: {(search.radius/1000).toLocaleString('pt-BR')} km. Marcadores selecionados ficam destacados.</p>}</div>;
}
